### PR TITLE
KT-41615 "Unused equals expression" inspection: highlight whole expression with yellow background

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-41615

### CODE REVIEW

**Comment by vladimirdolzhenko** [comment]
Thank you for the PR.

Could you please extend test data to cover this case ?

**Comment by t-kameyama** [comment]
PTAL

**Comment by vladimirdolzhenko** [comment]
Thanks, LGTM

Waiting for CI

**Comment by vladimirdolzhenko** [comment]
Merged manually

**Pull request closed without merging**
