### PR TITLE
FIR checker: report VAL_REASSIGNMENT on value parameter

### PR DESCRIPTION
**Pull request by jsjeon**
E.g.,

```kt
fun reassignFunParams(a: Int) {
    <!VAL_REASSIGNMENT!>a<!> = 1
} 
```

This doesn't require CFA. We can simply visit variable assignment, and check if the lvalue is value parameter.

2nd commit refactors existing `FirValReassignmentViaBackingFieldChecker` to a general form, and 3rd commit adds that new part. 1st commit is a simple cleanup while revisiting CFA.

### CODE REVIEW

**Review by tgeng — APPROVED** [review]

**Review by punzki — APPROVED** [review]

**Comment by jsjeon** [comment]
Gentle ping.

**Comment by jsjeon** [comment]
There would be a merge conflict with https://github.com/JetBrains/kotlin/pull/4379. Whichever comes first, I can deal with that conflict on the remaining one.

**Comment by jsjeon** [comment]
> There would be a merge conflict with #4379. Whichever comes first, I can deal with that conflict on the remaining one.

Conflict resolved.

**Comment by jsjeon** [comment]
Another ping, @semoro

**Comment by jsjeon** [comment]
Yet another ping, @semoro 

I've been working on FIR UAST for past several weeks, but since the repo is migrated next week, it'd be good time to be back to checkers/dignostics (until the migration is done). On my to-do list, I want to extend property initializer checkers to member properties, and it is highly likely that this one will be conflict. This is really simple PR I believe, so PTAL.

**Comment by jsjeon** [comment]
I saw these are merged, thanks!

**Pull request closed without merging**
