### PR TITLE
FIR2IR: honor user-contributed members in data class if any

### PR DESCRIPTION
**Pull request by jsjeon**
User may define their own, e.g., `componentN` (which may be intentionally out of bound, like `component2` for the data class with only one value parameter). Currently, we unconditionally generate function body for synthetic members. If the body came from user's code, it's no longer synthetic.

### CODE REVIEW

**Comment by mglukhikh** [comment]
It looks great but as I can see some Fir2IrText / FirBlackBoxCodegen tests are broken in your build: https://teamcity.jetbrains.com/buildConfiguration/Kotlin_KotlinForGoogle_CompilerWithTests/2979216?buildTab=tests&pager.currentPage=1.

**Comment by jsjeon** [comment]
Hm, didn't see them in `firCompilerTest`. Something wrong in my local setting. Let me check.

**Comment by jsjeon** [comment]
Aha, now I remember. I saw three failures like these:

```
> Task :compiler:fir:fir2ir:test

org.jetbrains.kotlin.codegen.ir.FirBlackBoxCodegenTestGenerated$Reflection$Mapping$Types > testCreateType FAILED
    org.jetbrains.kotlin.TestsRuntimeError at FirBlackBoxCodegenTestGenerated.java:26078
        Caused by: kotlin.NotImplementedError at FirBlackBoxCodegenTestGenerated.java:26078

org.jetbrains.kotlin.codegen.ir.FirBlackBoxCodegenTestGenerated$Reflection$Mapping$Types > testTypeParameters FAILED
    org.jetbrains.kotlin.TestsRuntimeError at FirBlackBoxCodegenTestGenerated.java:26078
        Caused by: kotlin.NotImplementedError at FirBlackBoxCodegenTestGenerated.java:26078

org.jetbrains.kotlin.fir.Fir2IrTextTestGenerated$Expressions > testJvmFieldReferenceWithIntersectionTypes FAILED
    java.lang.RuntimeException at Fir2IrTextTestGenerated.java:708
        Caused by: java.io.FileNotFoundException at Fir2IrTextTestGenerated.java:708
```

and... they are broken on `master` too. 😱

**Comment by mglukhikh** [comment]
Then Ok, I merged it.

**Pull request merged**
