### PR TITLE
Presence of (transient) delegated field in the serialized class breaks deserialization

### PR DESCRIPTION
**Pull request by AngryGami**
https://github.com/Kotlin/kotlinx.serialization/issues/2091

Do not include delegated field into generated constructor even though it
might have backing field.

Test that shows issue was added. Properties that are explicitly marked as delegated are now excluded.

### CODE REVIEW

**Comment by sandwwraith** [comment]
Hi, thanks for your PR! Two things:

1. You have outdated copyright. Seems you need to re-run `./gradlew :kotlinx-serialization-compiler-plugin:generateTests` for build to pass.
2. As far as I remember, problem with delegated fields appears for fields that were optimized away (https://kotlinlang.org/docs/whatsnew1720.html#more-optimized-cases-of-delegated-properties). In the code, you ignore all properties with `isDelegated = true`. Can you make sure that even non-optimized properties are still working correctly? Please add the corresponding class to your `delegatedProperty.kt` test .

**Comment by AngryGami** [comment]
I've added tests for other examples of optimized properties/fields. 
You are saying that this problem appeared because generated `$delegate` field was removed by optimization while serialization still tries to add initialization for them in constructor, am I correct?
I don't quite understand why serialization is bothered at all by such fields. Documentation explicitly says that delegated fields (of any variety) are not part of serialization/deserialization processes (i.e. transient). Hence this check I've added should have been there from very beginning isn't it?

**Comment by sandwwraith** [comment]
> You are saying that this problem appeared because generated $delegate field was removed by optimization while serialization still tries to add initialization for them in constructor

Yes, that's the problem

> I don't quite understand why serialization is bothered at all by such fields. Documentation explicitly says that delegated fields (of any variety) are not part of serialization/deserialization processes (i.e. transient)

Serialization plugin generates specific constructor, which (unlike Kotlin constructors) does not delegate to any other constructors except superclass. Therefore, all properties initializers and init blocks should be executed in it, regardless whether they're transient or not.

**Comment by AngryGami** [comment]
Ah.. that makes sense. Thanks for explanation.

**Pull request closed without merging**
