### PR TITLE
JVM_IR: Do not transform irBranch if tableswitch can't be generated

### PR DESCRIPTION
**Pull request by scaventz**
issue: https://youtrack.jetbrains.com/issue/KT-34466

### CODE REVIEW

**Comment by scaventz** [comment]
Difference between `1.6.20-M1(old-backend)` and `this branch(jvm_ir)`:
image


Difference between `1.6.20-M1(jvm_ir)` and this `branch(jvm_ir)`:
image

**Comment by dnpetrov** [comment]
LGTM. I'll run tests and push.

**Comment by dnpetrov** [comment]
Bootstrap build failed with an exception:

File being compiled: .../kotlin/libraries/tools/kotlin-stdlib-gen/src/templates/dsl/CommonTypes.kt

Relevant part of the stack trace:

java.lang.AssertionError: org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl@4e6ee764: No such value argument slot: 1
at org.jetbrains.kotlin.ir.expressions.IrMemberAccessExpression.getValueArgument(IrMemberAccessExpression.kt:39)
at org.jetbrains.kotlin.backend.common.lower.EnumWhenLowering.allEntriesAreConstants(EnumWhenLowering.kt:87)
at org.jetbrains.kotlin.backend.common.lower.EnumWhenLowering.visitBlock(EnumWhenLowering.kt:76)

**Comment by scaventz** [comment]
Updated:
1. added a if-statement to make sure `symbol` of `condition` is `context.irBuiltIns.eqeqSymbol`
2. a new test case, `notAllConditionsAreEqEqExceptElse.kt`
3. changed the function name from `allEntriesAreConstants` to `conditionsAreEqEqsAndEntriesAreConstants`

**Comment by dnpetrov** [comment]
One more failing test (JS_IR): org.jetbrains.kotlin.js.test.ir.IrJsCodegenBoxTestGenerated$When$EnumOptimization.testNullableEnum

```
    java.lang.AssertionError(Function test contains 0 nodes of type org.jetbrains.kotlin.js.backend.ast.JsCase, but expected count is 3 expected:<3> but was:<0>)
    java.lang.AssertionError(Function test contains 3 nodes of type org.jetbrains.kotlin.js.backend.ast.JsIf, but expected count is 0 expected:<0> but was:<3>)
 ```

@broadwaylamb please, check if that's acceptable

**Comment by dnpetrov** [comment]
Pushed ( 4277827506d74285b07449928a46e3a18927838c )

**Pull request closed without merging**
