### PR TITLE
KT-32163: Open Quick Documentation when cursor inside function / constructor brackets

### PR DESCRIPTION
**Pull request by Monchi**
https://youtrack.jetbrains.com/issue/KT-32163

### CODE REVIEW

**Comment by Monchi** [comment]
@darthorimar I'm sorry for late response!
I added some tests, but I need help.

`QuickDocProviderTestGenerated.testJavaClassConstructorUsedInKotlin` and `QuickDocProviderTestGenerated.testJavaMethodUsedInKotlinInParen` failed due to the error below.
```
java.lang.NullPointerException: Parameter specified as non-null is null: method org.jetbrains.kotlin.idea.KotlinDocumentationProviderCompatBase.generateDoc, parameter element
java.lang.IllegalStateException: java.lang.NullPointerException: Parameter specified as non-null is null: method org.jetbrains.kotlin.idea.KotlinDocumentationProviderCompatBase.generateDoc, parameter element
	at org.jetbrains.kotlin.test.KotlinTestUtils.lambda$runTestWithThrowable$4(KotlinTestUtils.java:729)
	at org.jetbrains.kotlin.test.MuteWithDatabaseKt.runTest(muteWithDatabase.kt:279)
	at org.jetbrains.kotlin.test.KotlinTestUtils.runTestWithThrowable(KotlinTestUtils.java:724)
	at org.jetbrains.kotlin.idea.test.KotlinLightCodeInsightFixtureTestCaseBase.runTest(KotlinLightCodeInsightFixtureTestCaseBase.java:108)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:391)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:18)
	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:13)
	at com.intellij.testFramework.EdtTestUtilKt$runInEdtAndWait$3.run(EdtTestUtil.kt:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:398)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method org.jetbrains.kotlin.idea.KotlinDocumentationProviderCompatBase.generateDoc, parameter element
	at org.jetbrains.kotlin.idea.KotlinDocumentationProviderCompatBase.generateDoc(KotlinDocumentationProvider.kt)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:136)
	at org.jetbrains.kotlin.idea.editor.quickDoc.AbstractQuickDocProviderTest.doTest(AbstractQuickDocProviderTest.java:36)
	at org.jetbrains.kotlin.test.KotlinTestUtils.lambda$testWithCustomIgnoreDirective$6(KotlinTestUtils.java:794)
	at org.jetbrains.kotlin.test.MuteWithFileKt$testWithMuteInFile$1.invoke(muteWithFile.kt:41)
	at org.jetbrains.kotlin.test.KotlinTestUtils.runTestImpl(KotlinTestUtils.java:777)
	at org.jetbrains.kotlin.test.KotlinTestUtils.runTest(KotlinTestUtils.java:715)
	at org.jetbrains.kotlin.idea.editor.quickDoc.QuickDocProviderTestGenerated.runTest(QuickDocProviderTestGenerated.java:24)
	at org.jetbrains.kotlin.idea.editor.quickDoc.QuickDocProviderTestGenerated.testJavaClassConstructorUsedInKotlin(QuickDocProviderTestGenerated.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at com.intellij.testFramework.UsefulTestCase.lambda$runTest$12(UsefulTestCase.java:337)
	at com.intellij.testFramework.UsefulTestCase.lambda$invokeTestRunnable$13(UsefulTestCase.java:374)
	at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:44)
	at com.intellij.testFramework.UsefulTestCase.invokeTestRunnable(UsefulTestCase.java:373)
	at com.intellij.testFramework.UsefulTestCase.runTest(UsefulTestCase.java:356)
	at org.jetbrains.kotlin.idea.test.KotlinLightCodeInsightFixtureTestCaseBase.lambda$runTest$0(KotlinLightCodeInsightFixtureTestCaseBase.java:108)
	at org.jetbrains.kotlin.test.KotlinTestUtils.lambda$runTestWithThrowable$4(KotlinTestUtils.java:726)
	... 22 more
```

However, actually the document could be fetched on running IDEA.


Do you have any idea to solve this error?

**Comment by darthorimar** [comment]
Hey @Monchi, it looks like `AbstractQuickDocProviderTest` is not ready for the caret being placed inside parameters lists, but real DocumentationManager is. The code responsible for that is here `com.intellij.codeInsight.documentation.DocumentationManager#showJavaDocInfo`. Feel free to fix `AbstractQuickDocProviderTest` behaviour, so it will correspong to a `DocumentationManager` one

**Comment by Monchi** [comment]
@darthorimar Hi, thanks for your help! Now, all new tests are passed.

**Comment by darthorimar** [comment]
Thank you!

**Pull request merged**
