### PR TITLE
#KT-26965 Add inspection + quickfix for replacing Collection<T>.count() with .size

### PR DESCRIPTION
**Pull request by devbridie**
YouTrack: https://youtrack.jetbrains.com/issue/KT-26965.

Covers all cases of [`kotlin-stdlib/kotlin.collections.count`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/count.html).

### CODE REVIEW

**Comment by devbridie** [comment]
Please see the improvements.

**Comment by devbridie** [comment]
Maybe `enabledByDefault="false"` should be `true`? Leaving it up to you.

**Comment by dimonchik0036** [comment]
Thank you! Your commit in master  [`4156a76`](https://github.com/JetBrains/kotlin/commit/4156a76129a5f785d85ea93e9076b0e8ff88f383).

**Comment by dimonchik0036** [comment]
Oh, my mistake

**Comment by devbridie** [comment]
Related commit: 2a940f5b0a7979d8d0a02a61fc7e620e4a9d9cd8

**Pull request closed without merging**
