### PR TITLE
KT-20357 Add sample code for Text.Char

### PR DESCRIPTION
**Pull request by takattata**
https://youtrack.jetbrains.com/issue/KT-20357

### CODE REVIEW

**Comment by ilya-g** [comment]
Note, there's already a pull request with `Char` functions samples #1526, however it looks abandoned.

**Comment by takattata** [comment]
What should I do?

**Comment by ilya-g** [comment]
@takattata You could take the branch from that PR and try to implement the proposed approach to demonstrate how these `Char` extensions work https://github.com/JetBrains/kotlin/pull/1526#issuecomment-382585961

**Comment by ilya-g** [comment]
I think I can extract sample for `Char.equals` function from this PR and merge it separately.

**Comment by takattata** [comment]
@ilya-g Thank you for your reply. I tried to change it, is this correct?

**Comment by takattata** [comment]
@ilya-g Sorry to bother you again. Did this fix code differ from what you intended?

**Comment by ilya-g** [comment]
Thanks, I've merged these samples, except the following:
- isDefined() — doesn't illustrate what this method is for
- isSurrogate(), isHighSurrogate(), isLowSurrogate(), isIdentifierIgnorable() — these tests contains non-printable characters and wouldn't look good in docs. Need to find some other approach how to show them.

**Pull request closed without merging**
