### PR TITLE
KT-14570 Remove support of MutableList/MutableSet/MutableMap of RemoveRedundantCallsOfConversionMethodsIntention

### PR DESCRIPTION
**Pull request by shiraji**
#KT-14570 Fixed

https://youtrack.jetbrains.com/issue/KT-14570

### CODE REVIEW

**Comment by cypressious** [comment]
@shiraji You remove the mutable collections alltogether. KT-14570 is about platform types only. Sorry, if that wasn't clear from the slack discussion.

**Comment by shiraji** [comment]
Oh...I see. I thought you guys want to remove all mutable collections for platform types.

Let me figure out how to fix this.

**Comment by shiraji** [comment]
Here is the line that detects `Collections.unmodifiableList(listOf(1))` is `MutableList`.

https://github.com/shiraji/kotlin/blob/a77b9747c228183c197506744bbf9b4effeac4c6/idea/src/org/jetbrains/kotlin/idea/intentions/RemoveRedundantCallsOfConversionMethodsIntention.kt#L74

I have no idea how to figure out if the element is platform type or not. Do you have any suggestion?

**Comment by cypressious** [comment]
Take a look at `type.isFlexible()` and `type.asFlexibleType()`

**Comment by shiraji** [comment]
Thanks!

**Comment by shiraji** [comment]
By the way, how did you find this problem? I don't even notice this until I write `Collections.unmodifiableList(listOf(1))`

**Comment by cypressious** [comment]
I thought of it when I saw `toMutableList()` in my code being flagged and I knew that I wanted to make a defensive copy in this case.

**Comment by shiraji** [comment]
Good catch. Thanks a lot of your help! Your contribution amazes me a lot.

**Comment by shiraji** [comment]
I think I fixed the code for platform type. I'm not sure for "defensive copy" part.

**Comment by cypressious** [comment]
That was just a remark regarding my project's codebase, it had nothing to do with your code.

**Comment by mglukhikh** [comment]
Pushed into master & 1.0.5, thanks for your efforts

**Pull request closed without merging**
