### PR TITLE
KT-35757 Inspection: convert initialized val to non-null type

### PR DESCRIPTION
**Pull request by kvirolainen**
https://youtrack.jetbrains.com/issue/KT-35757

### CODE REVIEW

**Comment by t-kameyama** [comment]
False positive:
```
fun foo() {
    val s1: String? = bar()
    val s2: String? = null
}

fun bar(): String? = ""
```

**Comment by kvirolainen** [comment]
Fixed

**Comment by vladimirdolzhenko** [comment]
Thank you for the contribution.

Sorry for the delay, LGTM

Resolved small conflict in `plugin-common.xml` (inspections have been migrated to `inspections.xml`) and merge PR manually.

**Comment by vladimirdolzhenko** [comment]
My bas I missed some case: it produces false positive for vars

**Comment by vladimirdolzhenko** [comment]
Reverted back as duplicate of https://youtrack.jetbrains.com/issue/KT-19321 / https://github.com/JetBrains/kotlin/pull/3657

**Pull request closed without merging**
