### PR TITLE
Add missing FIR test cases for the parcelize plugin

### PR DESCRIPTION
**Pull request by gala377**
All the files under testData have been autogenerated by the test generator and will be used as golden files from now on to diff against in the future tests.

YT Bug: https://youtrack.jetbrains.com/issue/KT-64454

### CODE REVIEW

**Comment by madsager** [comment]
Looks good to me.

@semoro @udalov could one of you take a look and help land this?

**Comment by mglukhikh** [comment]
Looks like Ok, I will rebase the branch and merge it.

**Comment by mglukhikh** [comment]
I will merge this PR anyway but I reviewed the test data and found two suspicious places when K1 and K2 behavior differs:
- `ParcelizeCreatorKt.test1` function from `plugins/parcelize/parcelize-compiler/testData/codegen/parcelableCreator.asm.fir.txt`. Its K2 version is much longer than a K1 version.
- `createFromParcel` and `writeToParcel` functions inside `efficientParcelable.asm.fir.txt` and `customParcelablesSameModule.asm.fir.txt`

It may be an evidence of some Parcelize bugs / backend bugs. @gala377 Do you by any chance have some comments here? You can find the rebased version of this test data in https://github.com/JetBrains/kotlin/tree/rr/mg/kt67014/plugins/parcelize/parcelize-compiler/testData/codegen.

**Comment by udalov** [comment]
@mglukhikh I've fixed the first problem and pushed the commit to your branch. Also, I've pushed it to this PR.

As for the second problem, I'm not sure yet, still investigating.

**Comment by mglukhikh** [comment]
For the second problem, a separate issue (https://youtrack.jetbrains.com/issue/KT-67354/K1-K2-Parcelize-investigate-differences-in-createFromParcel-writeToParcel-bytecode) was created. This PR is merged manually.

**Pull request closed without merging**
