### PR TITLE
FIR: improve inference of implicit type arguments in casts

### PR DESCRIPTION
**Pull request by pyos**
Type parameters do not necessarily match one-to-one, or preserve order.

### CODE REVIEW

**Comment by demiurg906** [comment]
Hy @pyos, thanks for PR

There are many failing tests in `org.jetbrains.kotlin.test.runners.FirOldFrontendDiagnosticsTestGenerated` and some in `org.jetbrains.kotlin.test.runners.codegen.FirBlackBoxCodegenTestGenerated`, please fix them

Your changes breaks casts to enums and some simple cases with bare types

**Review by demiurg906 — CHANGES_REQUESTED** [review]
Hy @pyos, thanks for PR

There are many failing tests in `org.jetbrains.kotlin.test.runners.FirOldFrontendDiagnosticsTestGenerated` and some in `org.jetbrains.kotlin.test.runners.codegen.FirBlackBoxCodegenTestGenerated`, please fix them

Your changes breaks casts to enums and some simple cases with bare types

**Comment by pyos** [comment]
So FirBlackBoxCodegenTestGenerated is now in `:compiler:fir:analysis-tests:test` instead of `:compiler:fir:fir2ir:test`? Can't say this makes any more sense...

Most of the changes in diagnostics tests look fine (other than the error type, which should really be NO_TYPE_ARGUMENTS_ON_RHS - I've changed it to at least WRONG_NUMBER_OF_TYPE_ARGUMENTS for now).

>Your changes breaks casts to enums and some simple cases with bare types

If you're referring to the diagnostics tests, those *should* be broken because it's not possible to infer the type parameters there. (Though I've not noticed any enums anywhere?..)

**Comment by demiurg906** [comment]
Thanks for fixes

> So FirBlackBoxCodegenTestGenerated is now in :compiler:fir:analysis-tests:test instead of :compiler:fir:fir2ir:test? Can't say this makes any more sense...

This is temporary decision which was made for period of migrating all FIR tests to new infrastructure which uses JUnit 5 instead of JUnit 4, because mixing two frameworks versions in one module breaks IDEA integration with tests. I will return FIR BB tests to `:compiler:fir:fir2ir:tests` soon (I hope)

> If you're referring to the diagnostics tests, those should be broken because it's not possible to infer the type parameters there.

They should not be *broken* if you send PR. They shows new behavior which is more correct, so testdata of those tests should be updated accordingly to changes

> Though I've not noticed any enums anywhere?..

I've observed that `FirOldFrontendDiagnosticsTestGenerated$Tests.testEnumEntryAsType` failed but in current version of PR it is OK

**Comment by demiurg906** [comment]
Merged manually

**Pull request closed without merging**
