### PR TITLE
Make folding if to return/assignment work with if-else-if-else

### PR DESCRIPTION
**Pull request by cypressious**
Fixes: #KT-13452

### CODE REVIEW

**Comment by mglukhikh** [comment]
It handles the following case incorrectly:
```
fun test(n: Int) {
    var a: String = ""
//  v Replace if with assignment: incorrect
    if (n == 1)
        a = "one"
    else if (n == 2)
        a = "two"
}
```

**Comment by cypressious** [comment]
I handle it for return but forgot to copy it over for assignments.

**Comment by mglukhikh** [comment]
It should be enough to check here that last `if` in branches has `else`.

**Comment by cypressious** [comment]
I'll fix it later today.

**Comment by cypressious** [comment]
Done

**Comment by mglukhikh** [comment]
OK thanks, pushed manually into master, will push into 1.0.4 a bit later.

**Pull request closed without merging**
