### PR TITLE
FIR: generate destructurings for more than one parameter

### PR DESCRIPTION
**Pull request by pyos**

### CODE REVIEW

**Review by mglukhikh — CHANGES_REQUESTED** [review]
Looks good but you have to change lighter AST counterpart accordingly.

**Comment by mglukhikh** [comment]
Please add also a test in `FirDiagnosticTestGenerated` group for this case, to be sure that PSI-based builder and lighter AST based builder works in the same way.

**Comment by pyos** [comment]
Done, I think

**Review by mglukhikh — APPROVED** [review]

**Comment by mglukhikh** [comment]
Ok, I will do some additional tests and merge it.

**Comment by mglukhikh** [comment]
Thank you.

**Comment by mglukhikh** [comment]
Merged manually 👍

**Pull request closed without merging**
