### PR TITLE
KT-27184 "Replace with safe call" is not suggested for nullable var property that is impossible to smart cast

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-27184

### CODE REVIEW

**Comment by mglukhikh** [comment]
I think (not exactly sure) that existing local quick fix and intention can be just re-used here, without modifying their source code. You can try to do this yourself, or I will think about it more attentively later.

**Comment by t-kameyama** [comment]
I'll try to do.

**Comment by mglukhikh** [comment]
I think it should be accepted now.

**Comment by mglukhikh** [comment]
Merged 👍 and then modified a bit

**Pull request closed without merging**
