### PR TITLE
Added info about JDK 1.6 into "Building" section of ReadMe.md

### PR DESCRIPTION
**Pull request by artem-zinnatullin**
I wanted to fix [#KT-6729](https://youtrack.jetbrains.com/issue/KT-6729) "Kotlin Gradle Plugin v0.10.195 + Android Gradle Plugin v1.1.0-rc1 -> build error"

And spent ~1 hour on figuring out build problem of Project Kotlin, finally I decided to go to your TeamCity CI and there I ~~found~~ investigated that it uses JDK 1.6 and when I switched to JDK 1.6 I was able to build Project Kotlin.

So.. I decided to make a notice about it in ReadMe.md.

Here is stacktrace of `ant -f build.xml` with **JDK 1.8**:

````
BUILD FAILED
/Users/artem/projects/open-source/kotlin/build.xml:732: The following error occurred while executing this line:
/Users/artem/projects/open-source/kotlin/build.xml:689: Java returned: 1
	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:111)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.MacroInstance.execute(MacroInstance.java:396)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 1 minute 21 seconds
````

### CODE REVIEW

**Comment by geevee** [comment]
Is that all error log you have?

**Comment by artem-zinnatullin** [comment]
@geevee you want full log? It will be pretty huge

Anyway, try to build Project Kotlin with JDK 1.8, maybe it's problem of my environment, but I don't think so

**Comment by geevee** [comment]
You're right, that is caused by JDK 8. There is compilation error:
`` ERROR: libraries/stdlib/src/kotlin/io/ReadWrite.kt: (156, 37) Type mismatch: inferred type is java.util.stream.Stream<kotlin.String!>! but kotlin.Stream<kotlin.String> was expected``

Thank you!

**Comment by artem-zinnatullin** [comment]
@geevee no problem, go Kotlin!

**Pull request merged**
