### PR TITLE
Strings: Add add{Prefix,Suffix}() extension functions

### PR DESCRIPTION
**Pull request by sschuberth**
This is for symmetry with the existing remove{Prefix,Suffix}() functions.

### CODE REVIEW

**Comment by ilya-g** [comment]
Related issue: https://youtrack.jetbrains.com/issue/KT-19805

**Comment by sschuberth** [comment]
@ilya-g what does it take to accept this PR? Do I need to add implementations for all other platforms Kotlin supports?

**Comment by sschuberth** [comment]
Any update @ilya-g?

**Comment by sschuberth** [comment]
Closing this due to a lack of feedback.

**Comment by ttntrifork** [comment]
Would really like to have this in stdlib 😢

**Pull request closed without merging**
