### PR TITLE
KT-34696 Wrong 'Redundant qualifier name' for 'MyEnum.values' usage

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-34696
https://youtrack.jetbrains.com/issue/KT-37181

### CODE REVIEW

**Comment by vladimirdolzhenko** [comment]
I have couple notes here:

-  using test data `notApplicableEnumCompanion.kt`: `value1?.let { <caret>QueryOperation.Companion.from("AA") }` still suggests `Remove redundant qualified name`, while ticket describes avoid dropping qualified name for ref method - this case looks similar 
- please use neutral package names rather `com.*`

**Comment by t-kameyama** [comment]
PTAL

**Comment by vladimirdolzhenko** [comment]
LGTM, Thank you

**Comment by vladimirdolzhenko** [comment]
Merged

**Pull request closed without merging**
