### PR TITLE
KT-17735 Simplify boolean expression produces incorrect result for floats comparison

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-17735

### CODE REVIEW

**Comment by zarechenskiy** [comment]
Hi @t-kameyama !

Regardless of the correctness, this change can produce incompatible change.
For example, consider the following code
```
const val a = -0.0 < 0.0

fun main() {
    println(a)
}
```

Currently, it prints `true` and after your changes, it'll print `false` (actually, it's [KT-24565](https://youtrack.jetbrains.com/issue/KT-24565)), so, unfortunately, we can't just accept your PR :(

The common problem is a bit bigger: we don't use IEEE754 comparison for constant evaluation and before start using it we should understand all places, which can change, then all such places need to be discussed with the Language committee (see more in https://kotlinlang.org/foundation/language-committee-guidelines.html) and only then we might introduce changes in the major update of the Kotlin compiler (1.4, for example)

So, I see two options:
- postpone with the changes until we fix this issue in the compiler
- fix this issue only on the IDEA side without fixing this in the compiler, so it'll be a totally compatible change

What do you think?

**Comment by t-kameyama** [comment]
I will try to fix this issue only on the IDEA side.

**Comment by t-kameyama** [comment]
@yanex 
I found 9f192ba85e29c46e3364080d6b985b5c95c1a5e5. Do you no longer need this pull request?

**Comment by yanex** [comment]
@t-kameyama Well, yes. During internal discussions, we decided that turning off the inspection for this precise case is safer, considering that it's infrequent in real code. Thanks for your help anyway!

**Pull request closed without merging**
