### PR TITLE
KT-42364 JS. Configurable delegated properties

### PR DESCRIPTION
**Pull request by turansky**
Details - [KT-42364](https://youtrack.jetbrains.com/issue/KT-42364)

### CODE REVIEW

**Comment by romanart** [comment]
It looks like a missed part of https://github.com/JetBrains/kotlin/pull/3219

@bashor since you were reviewing the previous one could please take a look here as well?

**Comment by bashor** [comment]
@romanart sure.

**Comment by bashor** [comment]
@turansky could you please add a test?

**Comment by turansky** [comment]
@bashor test is added

**Comment by bashor** [comment]
Thank you for your contribution!

**Comment by turansky** [comment]
@bashor What is planned release version for this fix?

**Comment by bashor** [comment]
It will be available in 1.4.30

**Pull request merged**
