### PR TITLE
KT-18375: ConvertCamelCaseTestFunctionToSpacedIntention suggests to rename quoted test to the same name

### PR DESCRIPTION
**Pull request by vasily-kirichenko**
#KT-18375 Fixed

### CODE REVIEW

**Comment by yole** [comment]
Please provide a test for this change.

**Comment by vasily-kirichenko** [comment]
I cannot run the tests locally, JB rejected my issue on their you track.

**Comment by yole** [comment]
I didn't just reject the issue; I also left a comment telling you where to ask for help in getting the tests running.

**Comment by vasily-kirichenko** [comment]
I see, thanks.

**Comment by yole** [comment]
I've pushed https://github.com/JetBrains/kotlin/commit/0e2bdb8e6646667c12d0afc46485d4f2bb8ada45 which restores tests for this inspection and incorporates your fix for the bug. Thanks a lot for your contribution!

**Pull request closed without merging**
