### PR TITLE
KT-5271 Missing QuickFix for Multiple supertypes available

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-5271

### CODE REVIEW

**Comment by yanex** [comment]
Case 1: `X` is erroneously suggested.

```
interface X {
    fun foo() {}
}

open class Y: X {
    override fun foo() {}
}

interface Z {
    fun foo() {}
}

class Test : X, Y(), Z {
    override fun foo() {
        <caret>super.foo()
    }
}
```

**Comment by yanex** [comment]
Case 2: Type arguments should not be present in super<>.

```
interface X {}

open class Y<T> {
    open fun foo() {}
}

interface Z {
    fun foo() {}
}

class Test : X, Y<Int>(), Z {
    override fun foo() {
        <caret>super.foo()
    }
}
```

**Comment by yanex** [comment]
Case 3: `Z` is not a valid option.

```
interface Z {
    fun foo(): CharSequence = ""
}

open class Y: Z {
    override fun foo(): String = ""
}

class Test : Y(), Z {
    override fun foo(): String {
        return super.foo()
    }
}
```

**Comment by yanex** [comment]
Case 4: Labels are not treated properly.

```
class Test : Y(), Z {
    override fun foo() {}

    inner class Boo : Y(), Z {
        override fun foo() {
            super@Test.foo()
        }
    }
}
```

Should replace with `super<Y>@Test` instead of `super<Y>`.

**Comment by yanex** [comment]
Case 5, similar to 2: annotations should be removed.

```
interface Z {
    fun foo() {}
}

open class X {
    open fun foo() {}
}

class Test<T : CharSequence> : (@Suppress("foo") X)(), Z {
    override fun foo() {
        super.foo()
    }
}
```

**Comment by yanex** [comment]
Review 👍

**Comment by t-kameyama** [comment]
f6a13df388540d71ccdbc99f69f6d60dd4648810

**Pull request closed without merging**
