### PR TITLE
JVM IR: Avoid getTopLevelClass for performance and Fir

### PR DESCRIPTION
**Pull request by sfs**
We recently saw a performance regression after merging #2657 on a small benchmark where deserializing `java.lang.String` ended up being a bottleneck. There are currently several symbols in JvmSymbols which we hardcode and some which are deserialized from disk instead (and in Fir mode we always have to hardcode all dependencies).

This PR makes JvmSymbols consistent by hardcoding all dependencies for the IR backend, which results in slightly better performance and allows us to remove the special cases for the Fir backend.

### CODE REVIEW

**Comment by udalov** [comment]
Do you maybe have specific numbers, how the execution time changed on this benchmark (and what this benchmark consists of)?

**Comment by sfs** [comment]
Sure, the benchmark numbers are [on Mako](https://mako.dev/benchmark?benchmark_key=5336056912150528&xspread=1&~Kotlinc=mean&~KotlincUseIr=mean&~KotlincUseFir=mean&order=bid), revision number 54373. The change in question broke fir for a while, which is why the next data-point for fir is for revision 54412 - note that there is no performance degradation in fir mode.

The benchmark itself consists of a simple abstract class with 500 subclasses which each override the same method and a main file which instantiates all classes and calls the overridden method.

**Comment by max-kammerer** [comment]
@sfs I'm curious, is this change affects test execution time?

**Comment by sfs** [comment]
@max-kammerer I think so. I'm seeing the IR tests (`gradlew :compiler:test --tests '*.ir.*'`, excluding jar creation) run in a total time of about 1h13min without the PR and in 1h4m with the PR (but that amounts to 3 minutes real time compared to ~2:45 minutes real time, so take these numbers with a pinch of salt).

**Comment by max-kammerer** [comment]
@sfs could you run test via ```gradlew :compiler:test --tests '*.ir.*' -Pkotlin.test.maxParallelForks=X``` where X is 2, 4 and 8. Looks like I will get similar amount of real time with much less CPU time

**Comment by sfs** [comment]
@max-kammerer Thanks for the pointers! The sweet spot over here seems to be 14 threads, bringing the test time down to 2:22 minutes (compared to 2:41 on master).

**Comment by max-kammerer** [comment]
@sfs And how many cores do you have (are they hyperthreaded or not?)? Seems we should change default for parallelization

**Comment by udalov** [comment]
@sfs Thanks for the contribution!

**Comment by mglukhikh** [comment]
Looks like https://youtrack.jetbrains.com/issue/KT-34496 can be closed now. Thank you again!

**Pull request merged**
