### PR TITLE
[JVM IR] Do not put destructuring params or underscores in LVT.

### PR DESCRIPTION
**Pull request by madsager**
Putting them in the local variable table means that the debugger
needs to have special handling for parameters with specific names.
That forces us to generate mangled names for these.

Instead of also implementing the name mangling for FIR, this
change gets rid of the parameters from the LVT instead.

### CODE REVIEW

**Comment by madsager** [comment]
Alright, this is because of the new implementation of evaluate expression using the IR backend. That needs to set up the fragment compilation pipeline and correctly passes JvmNameProvider as the name provider. It just needs to use NameProvider.DEFAULT in the same way that this change does for the full compiler.

I made that change here: https://github.com/JetBrains/intellij-community/pull/1818

When changes hit which branches in the intellij repo is unclear to me. What would be the best way forward here? Should we temporarily add back the JvmNameProvider in this change? Or can we land this as soon as the intellij side change lands? @nikita-nazarov @zarechenskiy

**Comment by nikita-nazarov** [comment]
@madsager I will land the [JetBrains/intellij-community#1818](https://github.com/JetBrains/intellij-community/pull/1818) to `kt-212-master` branch asap. After that it should be safe to land the compiler changes, since `kt-212-master` is synced with compiler's `master`.

**Comment by nikita-nazarov** [comment]
Merged https://github.com/JetBrains/intellij-community/pull/1818

**Comment by dnpetrov** [comment]
Pushed ( 6622846bc145959331afe7fdbfa8859c0fa01a7c ).

**Comment by madsager** [comment]
Thank you both! :)

**Pull request closed without merging**
