### PR TITLE
Detect recursive property accessors

### PR DESCRIPTION
**Pull request by nd**
#KT-17221 Fixed

### CODE REVIEW

**Comment by mglukhikh** [comment]
@nd Looks good, but I'd say the second case like below (duplicating comment in the issue) is even more important. Not sure should it be the same inspection, probably the other one is better.

```
// JavaInterface.java
public interface JavaInterface {
    String getSmth();
}
// Test.kt
class Test {
    val smth: String
    fun createJavaInterface() = object : JavaInterface {
        override fun getSmth() = smth // expected this@smth, but synthetic property is used instead!
    }
}
```

**Comment by nd** [comment]
@mglukhikh sure, will try writing one.

**Comment by mglukhikh** [comment]
@nd At the moment I've almost done it myself. It can work almost in the same way as the first part. So thanks for your help

**Comment by mglukhikh** [comment]
Also, I've added a fix for the first part (done by you) which replaces recursive access with `field`.

**Comment by mglukhikh** [comment]
Merged into master and 1.0.3, thank you

**Pull request closed without merging**
