### PR TITLE
KT-31553 Complete Statement: Wrong auto-insertion of closing curly brace for a code block

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-31553

### CODE REVIEW

**Comment by yanex** [comment]
Review OK.

**Comment by klunnii** [comment]
1. Provided implementation covers only properties initialization with `run`/`when` functions. Would it be possible to support properties-and-variables + arbitrary functions?
2. If one places a whitespace after the left brace, handler cannot deal with the case. Could you fix it please?
`val prop = run{<whitespace><caret>computeProperty()`

**Comment by t-kameyama** [comment]
Fixed in a069839

**Comment by klunnii** [comment]
Commits were squashed before the merge. Thank you! Accepted.

**Pull request merged**
