### PR TITLE
Generalize getLightClassMethods name filtering

### PR DESCRIPTION
**Pull request by geralt-encore**
These changes are related to KT-44727. While original issues has been fixed by https://github.com/JetBrains/kotlin/commit/6331a135c8c7a966d2688326bf203b1873734dc5 I've noticed that similar scenario might happen in other places like https://github.com/JetBrains/kotlin/blob/29b23e79f32791e456a5b4a453277f0f0b3e984d/plugins/uast-kotlin/src/org/jetbrains/uast/kotlin/KotlinUastLanguagePlugin.kt#L659
Since `getLightClassMethod` and `getLightClassMethods` are taking `KtFunction` as a parameter we should be able to get name from it without introducing `getLightClassMethodsByName` function so all call sites could leverage it by default.

### CODE REVIEW

**Comment by vladimirdolzhenko** [comment]
Sorry, it would not work. 

At least there are some corner cases like `internal` methods - see https://github.com/JetBrains/kotlin/blob/ed9a0e514d897be853e3b66ce78500a00e60a32e/idea/tests/org/jetbrains/kotlin/idea/refactoring/introduce/ExtractionTestGenerated.java#L4128

Internal methods looks like `public` in jvm bytecode but they are not visible to java due using of specific chars (`$`) in a name of method - therefore it could not be used from java.

In case of https://github.com/JetBrains/kotlin/blob/bd88e0217281d96abdf5361b7ad9a18d1a4ab43a/idea/testData/refactoring/extractInterface/liftInternal.kt#L7 the LC method is named `internalFun$light_idea_test_case` while filter uses plain `internalFun`

**Comment by geralt-encore** [comment]
Thanks for the detailed explanation, @vladimirdolzhenko! Do you think this optimisation makes sense in general though? In theory we can skip name filtering for internal functions by checking their modality. I am not sure if there are any other corner cases which could be hard to account for.

**Comment by vladimirdolzhenko** [comment]
There is at least one more case I'd like to check: bridge methods e.g. `size` method for collections in Kotlin has as well extra method `getSize()`

**Comment by geralt-encore** [comment]
So I was trying to find a good place to test this change but I didn't find anything suitable so I ended up testing it as a part of UAST conversion. You were indeed correct regarding the problem with internal functions. Do you have an idea how/where I could test how my change affects bridge functions as well?

**Comment by vladimirdolzhenko** [comment]
I can suggest to play around this snippet 
```
abstract class CList<Elem> : List<Elem> by emptyList<Elem>()
```

Could you pls describe scenario where have you faced problems using `getLightClassMethods(KtFunction)` / `getLightClassMethod(KtParameter)` ?

**Comment by geralt-encore** [comment]
It was happening when I opened a big file (~4k LOC) which had few Android API level usage errors. Snapshot is similar to the issue you have fixed in https://github.com/JetBrains/kotlin/commit/6331a135c8c7a966d2688326bf203b1873734dc5.

Screenshot 2021-03-24 at 14 51 01

**Comment by geralt-encore** [comment]
Sorry, seems like it is more complicated than I initially thought and I can't find a clear repro and the way to test it properly so I'm going to close it for now.

**Pull request closed without merging**
