### PR TITLE
Add Merge ifs intention

### PR DESCRIPTION
**Pull request by cypressious**
https://youtrack.jetbrains.com/issue/KT-9912

### CODE REVIEW

**Comment by cypressious** [comment]
@valentinkip Could you tell me which bug you've spotted?

**Comment by valentinkip** [comment]
@cypressious comments can be easily lost. Anyway it makes sense to refactor the code to have one implementation of this feature.

**Comment by cypressious** [comment]
@valentinkip I rebased on master. Do you have time to review the changes?

**Comment by yole** [comment]
Thanks for your contribution!

**Pull request merged**
