### PR TITLE
KT-45777: Add integration tests for `kotlin.incremental.useClasspathSnapshot` feature

### PR DESCRIPTION
**Pull request by hungvietnguyen**

### CODE REVIEW

**Comment by nav-nav** [comment]
@hungvietnguyen
"KotlinCompile: Add kotlin.incremental.useClasspathSnapshot flag" commit is already in master

**Comment by hungvietnguyen** [comment]
> @hungvietnguyen
> "KotlinCompile: Add kotlin.incremental.useClasspathSnapshot flag" commit is already in master

@nav-nav Yup, I've just updated this PR.

**Comment by nav-nav** [comment]
merged into master

**Comment by hungvietnguyen** [comment]
Wonderful to hear, thank you!

**Pull request closed without merging**
