### PR TITLE
FIR CFG: handle loops and try/catch when analyzing smartcasts in lambdas

### PR DESCRIPTION
**Pull request by pyos**
See KT-50092

(Note: this code was written on top of #4967 and so includes a part of it.)

### CODE REVIEW

**Comment by demiurg906** [comment]
Everything looks fine, I'll merge this together with 4967 after remote run

**Comment by demiurg906** [comment]
There is one failing test and one piece of code in kotlin repo which stoped to compile:
- Test is `DiagnosisCompilerTestFE10TestdataTestGenerated.Tests.SmartCasts.testImplicitThisOrLocalVar`
- false positive error in [runtimeExceptionReporting.kt](https://github.com/JetBrains/kotlin/blob/b36d1be5f858fe09f673c7568fa97d3028ec5c6e/libraries/scripting/jvm/src/kotlin/script/experimental/jvm/util/runtimeExceptionReporting.kt#L41) file
```
 e: file:///mnt/agent/work/17e640964edd2053/kotlin/libraries/scripting/jvm/src/kotlin/script/experimental/jvm/util/runtimeExceptionReporting.kt:41:24 Assignment type mismatch: actual type is kotlin/Throwable? but kotlin/Throwable was expected
12:27:50   e: file:///mnt/agent/work/17e640964edd2053/kotlin/libraries/scripting/jvm/src/kotlin/script/experimental/jvm/util/runtimeExceptionReporting.kt:42:23 Smart cast to 'kotlin/Throwable' is impossible, because 'R|<local>/current|' is a local variable that is captured by a changing closure
```

Please fix those issues

You can take [push/demiurg906/fir-fixes-from-pyos](https://github.com/JetBrains/kotlin/tree/push/demiurg906/fir-fixes-from-pyos) branch as base, where I merged two your PRs and fixed `super.visit...` calls

**Comment by pyos** [comment]
>Test is DiagnosisCompilerTestFE10TestdataTestGenerated.Tests.SmartCasts.testImplicitThisOrLocalVar

Yeah, the error message for argument type mismatch when the expected type is a type parameter is somewhat unreadable. Changed the test, since that's not what it's supposed to check.

>false positive error in [runtimeExceptionReporting.kt](https://github.com/JetBrains/kotlin/blob/b36d1be5f858fe09f673c7568fa97d3028ec5c6e/libraries/scripting/jvm/src/kotlin/script/experimental/jvm/util/runtimeExceptionReporting.kt#L41) file

Fixed. I tried salvaging the liveness analysis, but it just doesn't work unfortunately - handling the fact that loops+break/continue and try/catch can jump over dead basic blocks is just too much for this simple analysis pass after all.

>You can take [push/demiurg906/fir-fixes-from-pyos](https://github.com/JetBrains/kotlin/tree/push/demiurg906/fir-fixes-from-pyos) branch as base, where I merged two your PRs and fixed super.visit... calls

Ok, but I don't have write access to that branch so I pushed the result here. #4967 is redundant now.

**Comment by demiurg906** [comment]
Meged manually. Thank you!

**Comment by demiurg906** [comment]
@pyos we discovered two cases in intellij codebase which were broken by your changes from this PR. Could you please check them out and send another PR with fixes?
```kotlin
// WITH_STDLIB
// FULL_JDK

import java.nio.file.Files
import java.nio.file.Path

fun Path.write(): Path = this
fun Path.delete() {}

fun test_1(amount: Int, tmp: Path) {
    for (i in 0 until amount) {
        Thread({
            var tmpFile: Path? = null
            try {
                tmpFile = Files.createTempFile(tmp, "", "")
                tmpFile.write() // <--------- SMARTCAST_IMPOSSIBLE
            }
            catch (e: Exception) {
                throw RuntimeException(e)
            }
            finally {
                tmpFile?.delete()
            }
        }, "Thread#$i").start()
    }
}
 ```
```kotlin
// WITH_STDLIB
// FULL_JDK

import java.io.BufferedReader
import java.io.File
import java.util.concurrent.Callable
import java.util.concurrent.ExecutionException
import java.util.concurrent.ExecutorService
import java.util.concurrent.TimeoutException

fun test_2(files: List<File>, executor: ExecutorService, out: BufferedReader) {
    for (file in files) {
        val future = executor.submit( Callable<List<String>> {
            val response: MutableList<String> = mutableListOf()
            var responseLine: String?
            while (true) {
                responseLine = out.readLine()
                if (responseLine == null || responseLine.isEmpty()) { // <--------- SMARTCAST_IMPOSSIBLE
                    break
                }
                response.add(responseLine) // <--------- SMARTCAST_IMPOSSIBLE
            }
            response
        })
        val response : List<String>
        try {
            response = future.get()
        } catch (e: TimeoutException) {
            continue
        } catch (e: ExecutionException) {
            continue
        }
    }
}
```

**Comment by pyos** [comment]
#4980

**Pull request closed without merging**
