### PR TITLE
provide samples for Comparisons (KT-20357)

### PR DESCRIPTION
**Pull request by sckm**

### CODE REVIEW

**Comment by ltongues** [comment]
@ilya-g 

> General notes:

This is useful, thanks. Maybe we should put this text inside `libraries/stdlib/samples/test/samples/README.md` ?

**Comment by ilya-g** [comment]
> Maybe we should put this text inside libraries/stdlib/samples/test/samples/README.md

@ltongues Sure, I'm going to write one soon.

**Comment by sckm** [comment]
Thank you for the review, I'll try to improve samples.

**Comment by sckm** [comment]
@ilya-g sorry for the late, please take a look.

In addition, at some samples like `thenBy`, a sorting result with comparator before applying the function is added. I hope this helps to understand functions. What do you think about this?

**Comment by ilya-g** [comment]
Very well, now it's much better. I'll just change `thenComparator` sample not to use `listOf(*array)`, since `sorted*` functions always create a copy of list, then squash all these commits and merge them.

**Comment by ilya-g** [comment]
Squashed and merged, thanks!

**Pull request closed without merging**
