### PR TITLE
Rr/cy/extract testing

### PR DESCRIPTION
**Pull request by cy6erGn0m**
Extract tests from stdlib

- added kotlin-test maven module
- added kotlin-test to kotlinc dist (required for IDEA tests) and as a module dependencies where required
- removed assert/fail usages from PROD code
- some tests were migrated to use another functions rather than `assertNNN` while the others now pick up kotlin-test.jar as a dependency 

remote builds: https://teamcity.jetbrains.com/viewType.html?buildTypeId=bt345&branch_Kotlin=rr%2Fcy%2Fextract-testing&tab=buildTypeStatusDiv

### CODE REVIEW

**Comment by cy6erGn0m** [comment]
@udalov haha, yes, thank you. I was looking at kotlin-reflect when was introducing kotlin-test.jar. Will fix

**Comment by cy6erGn0m** [comment]
merged manually

**Comment by udalov** [comment]
^ BTW manifest name still isn't fixed

**Comment by cy6erGn0m** [comment]
@udalov ops, fixed in master https://github.com/JetBrains/kotlin/commit/c5e43a132767af71331126cb98981d9318e6e3cd

**Pull request closed without merging**
