### PR TITLE
TotalOrderEquals: Handle nulls

### PR DESCRIPTION
**Pull request by ting-yuan**

### CODE REVIEW

**Comment by dnpetrov** [comment]
Looks good to me. I'll run tests and merge manually.

**Comment by max-kammerer** [comment]
@dnpetrov Could we use here optimized variant similar to 'genIEEE754EqualForNullableTypesCall'?

**Comment by dnpetrov** [comment]
@max-kammerer 
Ideally we should, especially since we know argument types.
Do we have bytecodeText tests for those specialized intrinsics?

**Comment by max-kammerer** [comment]
@dnpetrov seems not,
even equalsNull_withExplicitFlag.kt test in non-ir backend generates unoptimized variant

**Comment by dnpetrov** [comment]
Merged manually.

**Pull request closed without merging**
