### PR TITLE
KT-34770 JS. Configurable properties

### PR DESCRIPTION
**Pull request by turansky**
Both backends supported

### CODE REVIEW

**Comment by bashor** [comment]
@turansky could you please add some tests?

**Comment by turansky** [comment]
Is there existed related tests for such cases?

**Comment by bashor** [comment]
You can check it using `Object.getOwnPropertyDescriptor`, to get prperties' names you can use `Object.getOwnPropertyNames` or `Object.keys`.
The closest example what I can find is [js/js.translator/testData/box/propertyAccess/enumerable.kt](https://github.com/JetBrains/kotlin/blob/master/js/js.translator/testData/box/propertyAccess/enumerable.kt)

**Comment by turansky** [comment]
Is there possibility to run tests only for `js` or `js/js.translator` subprojects?

**Comment by turansky** [comment]
> @turansky could you please add some tests?

Done

**Comment by bashor** [comment]
I've rebased and pushed changed manually. 

Thank you for your contribution!

**Pull request closed without merging**
