### PR TITLE
KT-30343 Add new Quarkus preset to all-open compiler plugin

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by abelkov** [comment]
https://youtrack.jetbrains.com/issue/KT-30343

**Comment by geoand** [comment]
@yanex I saw that the status in YouTrack has been moved to `Fixed`. Was the fix done outside of the PR? Should I close this?

**Comment by yanex** [comment]
I merged the commit to master manually: https://github.com/JetBrains/kotlin/commit/f11c5a335a29a8082cedbc34efe447e3b860b9f7.
Thank you for the contribution!

**Comment by geoand** [comment]
Awesome, thanks!

**Pull request closed without merging**
