### PR TITLE
[ObjCExport] KT-70137 Add same function name in different classes and interfaces test cases

### PR DESCRIPTION
**Pull request by xiaobailong24**
https://youtrack.jetbrains.com/issue/KT-70137
Since Objective-C does not support overloading of methods/selectors with the same name but different return values, so when two Kotlin `interfaces` have methods with the same name but different return values(one `someMethodWithDiffReturnType` return `String`, another one return `Int`), in order to avoid method conflicts when Objective-C implements the protocols exported by the two Kotlin interfaces at the same time, the method of the second Kotlin interface will be added with a `_` suffix when it is exported to framework header(the second `someMethodWithDiffReturnType` is named `someMethodWithDiffReturnType_`). The same is true if there are more Kotlin interfaces with the same method name.

But,  that is not applicable to`class`, because of unsupporting for multiple inheritance.

Additional, the order of translation is there:
https://github.com/JetBrains/kotlin/blob/master/native%2Fobjcexport-header-generator%2FTranslationOrder.md

So, Add test case for the Objective-C hearder export rule.

### CODE REVIEW

**Comment by sbogolepov** [comment]
Hey! Sorry for the long answer. LGTM. Could you please rebase onto master?

**Comment by xiaobailong24** [comment]
@sbogolepov thanks for your reply. I have rebased my brach onto master. Please review the PR again.

**Comment by xiaobailong24** [comment]
@sbogolepov Sorry to force push for rebase onto master. And has this PR been merged?

**Comment by sbogolepov** [comment]
Yep, [merged](https://github.com/JetBrains/kotlin/commit/cf34f218cd823a24cb147149fd58b69271c3069a) manually

**Comment by xiaobailong24** [comment]
So, is there anything else I should do?

**Comment by sbogolepov** [comment]
> So, is there anything else I should do?

Nope, all good!

> I don't know why it was merged manually.

Don't worry, just a part of our internal process :)

**Comment by xiaobailong24** [comment]
GOOD! Thanks very much!

**Pull request closed without merging**
