### PR TITLE
KT-8597 ReplaceWith is not suggested for 'invoke'-convention usages

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-8597

### CODE REVIEW

**Comment by yanex** [comment]
Seems that `it is FunctionDescriptor && it.isOperator && it.name == OperatorNameConventions.INVOKE` appears several times in the commit. Maybe extract it to some utility function?

**Comment by yanex** [comment]
Broken case:

```
// "Replace with 'execute(action)'" "true"

@Deprecated("Use Executor.execute(Runnable) instead.", ReplaceWith("execute(action)"))
public operator fun Executor.invoke(action: () -> Unit) {}

class Executor {
    fun execute(action: () -> Unit) {}
}

fun usage(executor: Executor) {
    with (executor) {
        <cursor>invoke {
            // do something
        }
    }
}
```

**Comment by yanex** [comment]
Broken case 2 (`self` should not be removed):

```
// "Replace with 'execute(action)'" "true"

@Deprecated("Use Executor.execute(Runnable) instead.", ReplaceWith("execute(action)"))
public operator fun Executor.invoke(action: () -> Unit) {}

class Executor {
    val self: Executor
        get() = this

    fun execute(action: () -> Unit) {}
}

fun usage(executor: Executor) {
    executor.<caret>self {
        // do something
    }
}
```

**Comment by t-kameyama** [comment]
Fixed in 607d086, please take another look.

**Comment by yanex** [comment]
Review: OK.

**Comment by yanex** [comment]
PR breaks the following tests:

```
InlineTestGenerated$InlineVariableOrProperty$AddParenthesis.testCallee
InlineTestGenerated$InlineVariableOrProperty$AddParenthesis.testCallCorrected
```

**Comment by t-kameyama** [comment]
> PR breaks the following tests:
> 
> ```
> InlineTestGenerated$InlineVariableOrProperty$AddParenthesis.testCallee
> InlineTestGenerated$InlineVariableOrProperty$AddParenthesis.testCallCorrected
> ```

Fixed in dbb99a28e62d2215a9cc6fec1fcb9864a49ee411, PTAL.

**Comment by yanex** [comment]
Thank you for your contribution! Changes are merged to the kotlin-intellij repository:
- https://github.com/JetBrains/intellij-kotlin/commit/72620e24abdf0abf9a539f00ff4bdc8931d757c0
- https://github.com/JetBrains/intellij-kotlin/commit/ec8705af20646573158eb215758427c70e024939

**Pull request closed without merging**
