### PR TITLE
KT-31020 Confusing "Put arguments on separate lines"/"Put arguments on one line" at the same time

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-31020

### CODE REVIEW

**Comment by yanex** [comment]
Two intentions are still available in these caret positions:

```
fun foo() {
    f (
        1,
        2,
        g<caret>(3, 4, 5)<caret>,
    3
    )
}
```

**Comment by t-kameyama** [comment]
PTAL

**Comment by yanex** [comment]
`val offset = element.findExistingEditor()?.caretModel?.offset ?: return true`

I would not use `findExistingEditor()` in an applicability check as there might not be an open editor.

**Comment by t-kameyama** [comment]
> `val offset = element.findExistingEditor()?.caretModel?.offset ?: return true`
> 
> I would not use `findExistingEditor()` in an applicability check as there might not be an open editor.

Fixed in c82b7f20f88, please take another look.

**Comment by yanex** [comment]
Review: OK.

**Comment by yanex** [comment]
Merged to the intelli-kotlin repository:
- https://github.com/JetBrains/intellij-kotlin/commit/43312ec6f5ba01ddf736405eef7a807c6cd61c58

Thank you for your contribution!

**Pull request closed without merging**
