### PR TITLE
Fix some errors in JVM_IR inlining

### PR DESCRIPTION
**Pull request by pyos**

### CODE REVIEW

**Comment by pyos** [comment]
@max-kammerer ping?

**Comment by max-kammerer** [comment]
@pyos will look soon

**Comment by max-kammerer** [comment]
@pyos Is it possible to split this pr to smaller ones?

At least I would prefer to have separate pr that combine changes in old inliner core part  AnonymousObjectTransformer/InliningContext and so on, e.g. at least next commits:
JVM_IR: do not regenerate anonymous objects in lambdas. 
Shift parameter annotations on constructors of local classes
Always capture locals for inline IR lambdas directly 
Reset captured parameter indices when copying descriptions 
Remove the old copy of captured params after adding them to the end

**Comment by pyos** [comment]
@max-kammerer ok, I'll try to.

**Comment by pyos** [comment]
^ split into separate PRs.

**Pull request closed without merging**
