### PR TITLE
Optimize Float/Double.isFinite()

### PR DESCRIPTION
**Pull request by romainguy**
The current implementation calls !isInfinite() && !isNaN(), leading to code that tests both cases separately. However, floats and doubles are encoded such that any positive finite value is, under integer representation of the raw bits, less than positive infinity.

The new implementation masks out the sign bit, and simply applies that test (< infinity).

When compiling the existing code on Android, using R8 and AOT compilation on a Pixel 6 running Android 14, we obtain the following aarch64 assembly:

```
fmov w0, s0
eor  w0, w0, #0x7f800000
tst  w0, #0x7fffffff
cset w0, eq
cbnz w0, #+0x14 (addr 0x1034)
fcmp s0, s0
b.ne #+0xc (addr 0x1034)
mov  w0, #0x1
b    #+0x8 (addr 0x1038)
mov  w0, #0x0
ret
```

There is a total of 11 instructions, including 3 branches. The new implementation yields the following branchless code instead, using only 6 instructions:

```
fmov w0, s0
and  w0, w0, #0x7fffffff
mov  w16, #0x7f800000
cmp  w0, w16
cset w0, lt
ret
```

When benchmarking the original (`isFinite()`) and new (`fastIsFinite()`) implementation on a 2021 MacBook M1 Pro using OpenJDK 22, we obtain the following results:

```
Benchmark                      Mode  Cnt    Score   Error  Units
KotlinBenchmark.fastIsFinite  thrpt       180.699          ops/s
KotlinBenchmark.isFinite      thrpt        93.578          ops/s
KotlinBenchmark.fastIsFinite   avgt         5.601          ms/op
KotlinBenchmark.isFinite       avgt        10.746          ms/op
```

Measuring throughput or time, the new implementation is twice as fast as the existing implementation (the benchmark calls the implementation over 16,777,215 unique float values).

### CODE REVIEW

**Review by TSampley — COMMENTED** [review]
Since the slower originals were self-describing by virtue of their named functions, it might be worthwhile to add comments (not docs) to compensate for the lost clarity. Then again, anyone maintaining this code probably understands what's going on and has access to the commit history 🤷🏻

**Comment by JakeWharton** [comment]
Seems like at least Wasm has the same simple boolean conditional version and could benefit from the update, too.

**Comment by romainguy** [comment]
> Since the slower originals were self-describing by virtue of their named functions, it might be worthwhile to add comments (not docs) to compensate for the lost clarity. Then again, anyone maintaining this code probably understands what's going on and has access to the commit history 🤷🏻

I was debating whether adding comments. I erred on the side of keeping the implementation "consistent" with the rest of the file but I don't mind commenting it either.

**Comment by romainguy** [comment]
> Seems like at least Wasm has the same simple boolean conditional version and could benefit from the update, too.

And native too I assume? Actually unless JS does something weird here I see no reason why this couldn't be the common impl?

**Comment by JakeWharton** [comment]
JS has no way to go to/from bits, sadly (at least not without allocation).

**Comment by fzhinkin** [comment]
Hey @romainguy! Thanks for the proposed change. 
@sellmair have been looking into [KT-70695](https://youtrack.jetbrains.com/issue/KT-70695) for some time verifying what and how needs to be changed on different platforms, so we'll probably continue with Seb's patch (which is on internal review).

**Comment by romainguy** [comment]
Ha, I forgot I filed a bug for this 😅

**Pull request closed without merging**
