### PR TITLE
#KT-9938 Fixed

### PR DESCRIPTION
**Pull request by mcgee**

### CODE REVIEW

**Comment by mcgee** [comment]
Thanks for your comments

Fixed and amended the commit

**Comment by mcgee** [comment]
Sorry, false alarm, I forgot to fix resources and I need to fix some tests.

**Comment by mcgee** [comment]
Ok, I think I'm ready now 

What have been done:
* Check if caret position is on initializer
* Check if property is not an extension one
* Check if property is not a local variable or top level declaration
* Registered in ``plugin.xml``
* Added resources to ``idea/resources/intentionDescriptions`` directory

**Comment by mcgee** [comment]
@yole fixed, I've made an additional commit, it should be easier to review 

I can melt them into one if everything ok

**Comment by mcgee** [comment]
@yole, ok, done

**Comment by yole** [comment]
Merged. Thanks! Sorry that it took so long; to make this faster, consider joining #kontributors in the Kotlin Slack

**Comment by mcgee** [comment]
@yole, yay! :tada:
I've joined #kontributors a while ago

**Pull request merged**
