### PR TITLE
KT-41897 `Redundant nullable return type` inspection should not be applied to overridden methods

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-41897

### CODE REVIEW

**Comment by klunnii** [comment]
@t-kameyama issue seems to controversial. 
It's quite normal to narrow return type at override. Should one design the class for extension and mark it as `open` inspection won't be applied (there could be undesired consequences). Please, provide more details/examples for the case(s) you tried to solve.

**Comment by t-kameyama** [comment]
> It's quite normal to narrow return type at override

I think so, but it's also normal not to narrow return type. 
I don't think we should be forced to narrow return type at override.

**Comment by t-kameyama** [comment]
> It's quite normal to narrow return type at override.

I think so, but it's also normal not to narrow return type. I think this inspection should not force to narrow return type at override.

**Comment by klunnii** [comment]
> ... but it's also normal not to narrow return type.

The case in question is about nullability. Why should clients of class C be misleaded and handle `null`? Could you please provide as example where inspection is undesired?

``` kotlin
interface I {
    fun f(): String?
    val v: String?
}

class C : I {
    override fun f(): String?/*caret*/ {
        return ""
    }
    override val v: String?/*caret*/
        get() = ""
}

```

**Comment by t-kameyama** [comment]
I think the above case is undesired.
In general, is it better to remove nullability in overridden methods if nullability is unnecessary?
If yes, please close this PR and the ticket.

**Comment by klunnii** [comment]
Closing

**Pull request closed without merging**
