### PR TITLE
don't generate any bytecode for typecasts to Unit

### PR DESCRIPTION
**Pull request by yole**
#KT-4921 Fixed

### CODE REVIEW

**Comment by udalov** [comment]
This change breaks the following case for example:
```
fun box() = if (4 as? Unit != null) "Fail" else "OK"
```

The reason is that all cast-like operators go through this method, including `:`, `as`, `as?`, `is`

**Comment by yole** [comment]
Added this testcase, fixed the problem in a different way.

**Comment by udalov** [comment]
Ok, looks good to me. Also this seems to fix KT-3066, please add a test and merge

**Comment by yole** [comment]
Merged manually.

**Pull request closed without merging**
