### PR TITLE
[IR] Make IrGetObjectValue copyable to avoid duplicate IR nodes.

### PR DESCRIPTION
**Pull request by madsager**
Fixes KT-45170

### CODE REVIEW

**Comment by madsager** [comment]
@dnpetrov, does this look like the right fix to you? Construction looks fine, but needs to copy the IrGetObjectValueImpl to not have multiple references to the same IR object.

**Comment by dnpetrov** [comment]
> @dnpetrov, does this look like the right fix to you? Construction looks fine, but needs to copy the IrGetObjectValueImpl to not have multiple references to the same IR object.

I'm on vacation. I'll take a look at it next week.

**Comment by dnpetrov** [comment]
My intuition tells me that if it fixes KT-45170, then there's actually some issue with compound assignment receiver generation in PSI2IR that is hidden by this change. I'll take a look into it later. Overall - looks Ok to me. I'll run tests and push manually.

**Comment by dnpetrov** [comment]
master: 7dbb0c7d20a3a6435e5331a1afd48c5607c40917
1.5.0: ba0f8ed0271673f87b7736fe25427a483256c0b3
1.5.0-M2: 5684a55caa84f4027538801fad3d2b69cf013748

**Pull request closed without merging**
