### PR TITLE
KT-37213 "Move to top level" intention does not update imports for extension functions

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-37213

### CODE REVIEW

**Comment by vladimirdolzhenko** [comment]
looks good to me - the only question - is it possible to hide _Move to top level_ (or at least show some info popup like `Sorry, this intention could not be applied here`) if it is not applicable ?

**Comment by t-kameyama** [comment]
Could you please provide examples that is not applicable?

**Comment by t-kameyama** [comment]
Could you please provide a example that is not applicable?

**Comment by vladimirdolzhenko** [comment]
Sure, I assumed it is quite visible from the code you've submitted:

```
object A {
    private fun foo() {}
} 
```

actually for `foo()` intention is still available but does nothing

**Comment by t-kameyama** [comment]
When declaration is private, it is moved by following code:
https://github.com/t-kameyama/kotlin/blob/862789a23e464868c7c020c4e510c696e025c8dc/idea/src/org/jetbrains/kotlin/idea/intentions/MoveMemberOutOfObjectIntention.kt#L75-L81

Similar test case works correctly.
https://github.com/t-kameyama/kotlin/blob/31a1fb916af7a3de49c2b83c38118f7bcb68e1cc/idea/testData/intentions/moveMemberToTopLevel/function.kt

**Comment by vladimirdolzhenko** [comment]
Sorry, it's my fault - you're right and thanks for the extra details 👍

**Comment by vladimirdolzhenko** [comment]
Thank you for the contribution

**Pull request merged**
