### PR TITLE
Kt-9009 fix

### PR DESCRIPTION
**Pull request by semoro**
https://youtrack.jetbrains.com/issue/KT-9009
Added tests, fixed base problems.

### CODE REVIEW

**Comment by semoro** [comment]
Resolved testing problems, ready for review

**Comment by valentinkip** [comment]
I have integrated it and will merge it into master soon. Unfortunately you added 2 more commits later. I integrated the first one but dropped the last one as it was difficult to merge it with my changes.

**Comment by semoro** [comment]
@valentinkip Last commit contains bugfix and tests for it

**Comment by valentinkip** [comment]
@semoro The code which it fixes was rewritten completely. And the test data files changed too. Most likely the bugfix has already been done by my changes.

**Comment by valentinkip** [comment]
Changes have been pushed into master (rebased onto the head).

**Pull request closed without merging**
