### PR TITLE
Add quickfix for adding 'lateinit'

### PR DESCRIPTION
**Pull request by cypressious**
Fixes #KT-17650

### CODE REVIEW

**Comment by mglukhikh** [comment]
Sorry but it's not so easy :(. At least I should mention that `lateinit` is not applicable for `val`, nullable types, and primitive-in-Java types. Please check `DeclarationsChecker.checkPropertyLateInit` for more information about.

**Comment by cypressious** [comment]
Ok, I'll take another look.

**Comment by cypressious** [comment]
@mglukhikh I've added checks for `val`, nullable and primitive types.

**Comment by mglukhikh** [comment]
This time looks good to me. Will merge it soon.

**Pull request closed without merging**
