### PR TITLE
Pass current index to lambda in Int.times(() -> Unit).  #KT-7074 Fixed

### PR DESCRIPTION
**Pull request by mhshams**

### CODE REVIEW

**Comment by geevee** [comment]
This looks not very intuitive to me.

**Comment by cy6erGn0m** [comment]
Anyway it is not intuitive whether it will be 0 .. this -1   or 1 .. this

**Comment by mhshams** [comment]
Updated the pull request, using suggested "foo loop".

**Comment by mhshams** [comment]
"Int.times" has been deprecated and this functionality now is available in "repeat"function.

**Pull request closed without merging**
