### PR TITLE
KT-9228 Implement inspection to remove @ used as annotation argument

### PR DESCRIPTION
**Pull request by shiraji**
#KT-9228 Fixed

https://youtrack.jetbrains.com/issue/KT-9228

### CODE REVIEW

**Comment by mglukhikh** [comment]
IMO the solution is unnecessary complex. Why you do not want to take KtAnnotatedExpression (and not KtAnnotated) as the basic for your intention? You can mark each such expression separately if 'at' is unnecessary. I think it will be more clear for the user.

**Comment by shiraji** [comment]
I agree with you. When i first tried to use `KtAnnotatedExpression`, no events occur. Maybe some settings were wrong. Let me fix this up.

**Comment by shiraji** [comment]
Could you review again @mglukhikh ? Now use `KtAnnotatedExpression`. Let me know if you want me to squash the commit.

**Comment by mglukhikh** [comment]
By the way: files like IntentionTestGenerated.java (to be precise, *TestGenerated.java) should never be changed manually. To regenerate them, please use "Generate Tests" run configuration (I've already done it for your changes).

**Comment by shiraji** [comment]
> files like IntentionTestGenerated.java (to be precise, *TestGenerated.java) should never be changed manually. To regenerate them, please use "Generate Tests" run configuration (I've already done it for your changes).

i didn't know that. i will run it in next time. Thanks!

**Comment by mglukhikh** [comment]
Refactored and added manually to master and 1.0.4 branches.

**Comment by shiraji** [comment]
Thanks!

**Comment by mglukhikh** [comment]
Thank you for your help

**Pull request closed without merging**
