### PR TITLE
KT-31602: Improve log messages when failing to compile with daemon

### PR DESCRIPTION
**Pull request by hungvietnguyen**

### CODE REVIEW

**Review by gavra0 — COMMENTED** [review]
LGTM, can you please create a YT issue and references it?

**Comment by hungvietnguyen** [comment]
> LGTM, can you please create a YT issue and references it?

Done - I've referenced this existing bug https://youtrack.jetbrains.com/issue/KT-31602

I've also made a small update in the next commit.

**Review by Tapchicoma — APPROVED** [review]
cc @nav-nav KT issues is assigned to you

**Comment by Tapchicoma** [comment]
Merged into `master` as 17bf6be807e474de581d0d9659cffd9760c9d3f6 commit

**Pull request closed without merging**
