### PR TITLE
#KT-5115 Fixed

### PR DESCRIPTION
**Pull request by mcgee**
https://youtrack.jetbrains.com/issue/KT-5115

### CODE REVIEW

**Comment by mcgee** [comment]
I've fixed the comments except for the one about case with the only setter. If you still don't agree with me after explanation, I'll remove it.

**Comment by mcgee** [comment]
I've fixed all comments except for the case with the only setter. If you still don't agree with me that it could be useful case, I'll remove it.

**Comment by mcgee** [comment]
Sorry, I amended the commit, so comments are not visible in this pull request anymore. They can be seen here: https://github.com/mcgee/kotlin/commit/60cd5ae131f134dae9ae831b17fb6fe2e4b74fee

**Comment by yole** [comment]
Thanks for your contribution!

**Pull request merged**
