### PR TITLE
KT-24336 Kotlin/JS missing SVGMaskElement interface

### PR DESCRIPTION
**Pull request by neonailol**
https://youtrack.jetbrains.com/issue/KT-24336

### CODE REVIEW

**Comment by ilya-g** [comment]
Note that this file is generated. Have you obtained it by running the generator?

**Comment by neonailol** [comment]
@ilya-g I have troubles with the generator, so I did this by hand.

`mvn exec:java` says `'mainClass'` is not valid
And code generated by antler missing class `WebIDLBaseVisitor`

**Comment by Schahen** [comment]
@neonailol  as it've been told, this file is generated from and there are some reasons why it's not autocommited. From here we can do one of two things:

1. You create *.idl definition and add it to this PR, I'll  explain what would be the next step if we move in this direction.
2. In case you don't have time or interest in supporting this PR further, I'll just create new  one for supporting `SVGMaskElement`.

**Comment by neonailol** [comment]
@Schahen I'll try to figure out how to make an idl definitions

**Comment by Schahen** [comment]
[This commit](https://github.com/JetBrains/kotlin/commit/c1f75d2324fb0321cbcec1c1e3753f0c49a4e280) made this PR obsolete

**Pull request closed without merging**
