### PR TITLE
Avoid accidentally configuring the publications deferred configuration

### PR DESCRIPTION
**Pull request by DanielThomas**
Gradle projects that use the `maven-publish` plugin break when the Kotlin plugin is applied due to `project.getProperties` causing the extension holder to be configured:

```
> Cannot configure the 'publishing' extension after it has been accessed.
```

The configuration happens here (had to set a breakpoint to catch this, the exception doesn't indicate where it was first configured):

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
      at org.gradle.api.internal.plugins.ExtensionsStorage$DeferredConfigurableExtensionHolder.configureNow(ExtensionsStorage.java:181)
      at org.gradle.api.internal.plugins.ExtensionsStorage$DeferredConfigurableExtensionHolder.get(ExtensionsStorage.java:162)
      at org.gradle.api.internal.plugins.ExtensionsStorage.getAsMap(ExtensionsStorage.java:50)
      at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.getProperties(DefaultConvention.java:168)
      at org.gradle.api.internal.CompositeDynamicObject.getProperties(CompositeDynamicObject.java:130)
      at org.gradle.api.internal.project.AbstractProject$4.create(AbstractProject.java:747)
      at org.gradle.api.internal.project.AbstractProject$4.create(AbstractProject.java:745)
      at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:166)
      at org.gradle.api.internal.project.AbstractProject.getProperties(AbstractProject.java:745)
      at org.jetbrains.kotlin.gradle.plugin.GradleUtils.kotlinPluginVersion(KotlinPlugin.kt:533)
      at org.jetbrains.kotlin.gradle.plugin.GradleUtils.kotlinPluginArtifactCoordinates(KotlinPlugin.kt:534)
      at org.jetbrains.kotlin.gradle.plugin.GradleUtils.resolveKotlinPluginDependency(KotlinPlugin.kt:538)
      at org.jetbrains.kotlin.gradle.plugin.AbstractKotlinPlugin.apply(KotlinPlugin.kt:244)
      at org.jetbrains.kotlin.gradle.plugin.KotlinPlugin.apply(KotlinPlugin.kt:265)
      at org.jetbrains.kotlin.gradle.plugin.KotlinPlugin.apply(KotlinPlugin.kt:259)
      at org.jetbrains.kotlin.gradle.plugin.KotlinBasePluginWrapper.apply(KotlinPluginWrapper.kt:39)
      at org.jetbrains.kotlin.gradle.plugin.KotlinBasePluginWrapper.apply(KotlinPluginWrapper.kt:20)
      at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOn
```

I tried a build locally so I could test this change, but I ran into:

```
runner:
     [echo] Cleaning /Users/dannyt/Projects/github/JetBrains/kotlin/dist/classes/runner
    [mkdir] Created dir: /Users/dannyt/Projects/github/JetBrains/kotlin/dist/classes/runner
  [kotlinc] Compiling [/Users/dannyt/Projects/github/JetBrains/kotlin/compiler/cli/cli-runner/src] => [/Users/dannyt/Projects/github/JetBrains/kotlin/dist/classes/runner]
  [kotlinc] /Users/dannyt/Projects/github/JetBrains/kotlin/compiler/cli/cli-runner/src/org/jetbrains/kotlin/runner/Classpath.kt:19:8: error: unresolved reference: java
  [kotlinc] import java.io.File
  [kotlinc]        ^
  [kotlinc] /Users/dannyt/Projects/github/JetBrains/kotlin/compiler/cli/cli-runner/src/org/jetbrains/kotlin/runner/Classpath.kt:20:8: error: unresolved reference: java
  [kotlinc] import java.net.URL
  [kotlinc]        ^
```

Not sure what I'm missing - must be something obvious I'm missing. I'm confident this will fix it, as extra properties are considered by this method:

https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#property(java.lang.String)

### CODE REVIEW

**Comment by ligee** [comment]
Thank you for the PR and sorry for the delay. I'll try to reproduce it first in order to check the fix, and then (if everything is ok) will merge it.

**Comment by DanielThomas** [comment]
Great, thanks.

**Comment by ligee** [comment]
Unfortunately, I cannot reproduce the problem, therefore cannot check the fix. I merged it into separate branch, and build results are available at https://teamcity.jetbrains.com/viewType.html?buildTypeId=bt345&branch_Kotlin=rr%2FDanielThomas-gradle-publish-compatibility&tab=buildTypeStatusDiv
Could you, please, take it and test whether it fixes the problem.

If you have any suggestions, how to reproduce it, it would be very nice. I used some simple config like:
```
buildscript {
  repositories {
    mavenCentral()
    maven {
        url 'file://' + pathToKotlinPlugin
    }
  }
  dependencies {
    classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:0.1-SNAPSHOT'
  }
}

apply plugin: "kotlin"
apply plugin: 'maven-publish'

repositories {
  maven {
     url 'file://' + pathToKotlinPlugin
  }
  mavenCentral()
}

dependencies {
    compile 'com.google.guava:guava:12.0'
    compile  'org.jetbrains.kotlin:kotlin-stdlib:0.1-SNAPSHOT'
}


publishing {
    publications {
        maven(MavenPublication) {
            groupId 'test'
            artifactId 'deploy.test'
            version '0.1'
        }
    }
    repositories {
        maven {
            url 'file://' + pathToTestMavenRepo
        }
    }
}
```

**Comment by h0tk3y** [comment]
Closing this PR as obsolete: the way the `kotlinPluginVersion()` is determined has been changed long ago, and now it doesn't cause the `publishing { ... }` extension configuration.

**Pull request closed without merging**
