### PR TITLE
Add inspections for implicit and explicit 'this'

### PR DESCRIPTION
**Pull request by cypressious**
Fixes #KT-4580
https://youtrack.jetbrains.com/issue/KT-4580

### CODE REVIEW

**Comment by mglukhikh** [comment]
Excellent counter-example found:
```
class Your(val x: Int)
fun Your.foo() = <caret>this.x // Add explicit 'this'
```

after it we get `fun Your.foo() = (this.this).x` together with NPE provoked by broken PSI :)

**Comment by mglukhikh** [comment]
Fixed, slightly simplified, and merged manually. Thank you. NB: I was not sure about `analyzeFully` vs `analyze` here, but looks like `analyze` also works.

**Comment by cypressious** [comment]
@mglukhikh I'm never sure about the difference between the two. Maybe someone should document this for external kontributers.

**Comment by mglukhikh** [comment]
It's too unclear to document it. I can only say you that `analyzeFully()` should have results equivalent to full compilation, and `analyze()` has no such guarantees. E.g., as I can remember `analyze()` will not produce CFG information.

**Pull request closed without merging**
