### PR TITLE
[IR] Do not generate line numbers for synthesized data class members.

### PR DESCRIPTION
**Pull request by madsager**
Fixes KT-41903.

### CODE REVIEW

**Comment by madsager** [comment]
@udalov Whether or not to generate line number information for synthesized items seems to be pretty inconsistent. Here, we do not want to generate them, but we are going to generate line numbers for synthesized bridge methods here: https://github.com/JetBrains/kotlin/pull/3725. 

Following the current backend is probably the right thing to do for now, but it would be nice to uniformly either generate line numbers or not for all of these.

**Comment by udalov** [comment]
I agree, it's inconsistent right now, but copying the old backend's behavior seems the safest option for now.

The change looks good, will merge it after a remote run!

**Comment by udalov** [comment]
Looks like this leads to errors in the composite build with Kotlin/Native on our build server. I can't reproduce them locally however, due to some irrelevant problem.

In particular, `:backend.native:tests:compileKonanCycle_detectorLinux_x64` fails, and the output contains lines:
```
Run tool: konanc with args: -output /mnt/agent/work/5d83bb1e6904a40a/kotlin-native/test.output/local/cycle_detector/linux_x64/cycle_detector.kexe -produce program -repo /mnt/agent/work/5d83bb1e6904a40a/kotlin-native/test.output/local/cycle_detector/linux_x64 -repo /mnt/agent/work/5d83bb1e6904a40a/kotlin-native/backend.native/tests/build/konan/libs/linux_x64 -target linux_x64 -tr -g -ea /mnt/agent/work/5d83bb1e6904a40a/kotlin-native/test.output/local/cycle_detector/cycle_detector.kt
Starting process 'command '/usr/lib/jvm/java-1.8.0-amazon-corretto/bin/java''. Working directory: /mnt/agent/work/5d83bb1e6904a40a/kotlin-native/backend.native/tests Command: /usr/lib/jvm/java-1.8.0-amazon-corretto/bin/java -Dawt.toolkit=sun.awt.X11.XToolkit -Dfile.encoding.pkg=sun.io -Dfile.separator=/ -Djava.awt.graphicsenv=sun.awt.X11GraphicsEnvironment -Djava.awt.headless=true -Djava.awt.printerjob=sun.print.PSPrinterJob -Djava.class.path=/mnt/cache/gradle/wrapper/dists/gradle-6.6.1-all/ejrtlte9hlw8v6ii20a9584rs/gradle-6.6.1/lib/gradle-launcher-6.6.1.jar -Djava.class.version=52.0 -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/lib/ext:/usr/java/packages/lib/ext -Djava.home=/usr/lib/jvm/java-1.8.0-amazon-corretto/jre -Djava.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib -Djava.runtime.name=OpenJDK Runtime Environment -Djava.runtime.version=1.8.0_265-b01 -Djava.specification.name=Java Platform API Specification -Djava.specification.vendor=Oracle Corporation -Djava.specification.version=1.8 -Djava.vendor=Amazon.com Inc. -Djava.vendor.url=https://aws.amazon.com/corretto/ -Djava.vendor.url.bug=https://github.com/corretto/corretto-8/issues/ -Djava.version=1.8.0_265 -Djava.vm.info=mixed mode -Djava.vm.name=OpenJDK 64-Bit Server VM -Djava.vm.specification.name=Java Virtual Machine Specification -Djava.vm.specification.vendor=Oracle Corporation -Djava.vm.specification.version=1.8 -Djava.vm.vendor=Amazon.com Inc. -Djava.vm.version=25.265-b01 -Dkotlin.environment.keepalive=true -Dlibrary.jansi.path=/mnt/cache/gradle/native/jansi/1.18/linux64 -Dline.separator=
 -Dorg.gradle.appname=gradlew -Dorg.gradle.daemon=false -Dos.arch=amd64 -Dos.detected.arch=x86_64 -Dos.detected.classifier=linux-x86_64 -Dos.detected.name=linux -Dos.detected.release=ubuntu -Dos.detected.release.like.debian=true -Dos.detected.release.like.ubuntu=true -Dos.detected.release.version=20.04 -Dos.name=Linux -Dos.version=5.4.0-1022-aws -Dpath.separator=: -Dsun.arch.data.model=64 -Dsun.boot.class.path=/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/lib/rt.jar:/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/lib/jfr.jar:/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/classes -Dsun.boot.library.path=/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/lib/amd64 -Dsun.cpu.endian=little -Dsun.cpu.isalist -Dsun.io.unicode.encoding=UnicodeLittle -Dsun.java.command=org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.6.1 -Dsun.java.launcher=SUN_STANDARD -Dsun.jnu.encoding=UTF-8 -Dsun.management.compiler=HotSpot 64-Bit Tiered Compilers -Dsun.os.patch.level=unknown -Duser.dir=/mnt/agent/work/5d83bb1e6904a40a/kotlin-native -Duser.home=/home/teamcity -Duser.name=teamcity -Duser.timezone -XX:TieredStopAtLevel=1 -Xmx3G -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/mnt/agent/temp/buildTmp -Duser.country=US -Duser.language=en -Duser.variant -ea -cp /mnt/agent/work/5d83bb1e6904a40a/kotlin-native/dist/konan/lib/trove4j.jar:/mnt/agent/work/5d83bb1e6904a40a/kotlin-native/dist/konan/lib/kotlin-native.jar org.jetbrains.kotlin.cli.utilities.MainKt konanc @/mnt/agent/temp/buildTmp/konancArgs513180107311125362.lst
Successfully started process 'command '/usr/lib/jvm/java-1.8.0-amazon-corretto/bin/java''
inlinable function call in a function with debug info must have a !dbg location
  invoke void @"kfun:kotlin.text.StringBuilder#<init>(){}"(%struct.ObjHeader* %11)
          to label %call_success unwind label %cleanup_landingpad
inlinable function call in a function with debug info must have a !dbg location
  %13 = invoke %struct.ObjHeader* @"kfun:kotlin.text.StringBuilder#append(kotlin.String){}kotlin.text.StringBuilder"(%struct.ObjHeader* %12, %struct.ObjHeader* bitcast ({ %struct.ArrayHeader, [20 x i16] }* @3265 to %struct.ObjHeader*), %struct.ObjHeader** %6)
          to label %call_success1 unwind label %cleanup_landingpad
inlinable function call in a function with debug info must have a !dbg location
  %16 = invoke %struct.ObjHeader* @"kfun:kotlinx.cinterop#<CPointer-box>(kotlinx.cinterop.CPointer<-1:0>?){}kotlin.Any?"(i8* %15, %struct.ObjHeader** %7)
          to label %call_success2 unwind label %cleanup_landingpad
inlinable function call in a function with debug info must have a !dbg location
  %17 = invoke %struct.ObjHeader* @"kfun:kotlin.text.StringBuilder#append(kotlin.Any?){}kotlin.text.StringBuilder"(%struct.ObjHeader* %14, %struct.ObjHeader* %16, %struct.ObjHeader** %8)
          to label %call_success3 unwind label %cleanup_landingpad
inlinable function call in a function with debug info must have a !dbg location
  %19 = invoke %struct.ObjHeader* @"kfun:kotlin.text.StringBuilder#append(kotlin.String){}kotlin.text.StringBuilder"(%struct.ObjHeader* %18, %struct.ObjHeader* bitcast ({ %struct.ArrayHeader, [1 x i16] }* @3266 to %struct.ObjHeader*), %struct.ObjHeader** %9)
          to label %call_success4 unwind label %cleanup_landingpad
...
```

Could you please see if this failure reproduces for you locally? It might be that Kotlin/Native relies on these line numbers for some reason, which I don't clearly understand.

@vvlevchenko Maybe you can help here? What do these errors mean and what would be the right way to fix this?

We could always resort to generating these line numbers for all platforms _except_ JVM, but I'd prefer to avoid introducing differences between backends if there's some other good solution.

**Comment by madsager** [comment]
Those native failures does reproduce locally for me. I'll have a look.

**Comment by madsager** [comment]
On the surface of things this looks like LLVM module verification errors. So we are probably asking LLVM to generate debugable code and then the missing line number information for these methods trips up verification because it cannot provide debug information for this.

**Comment by madsager** [comment]
Reading the kotlin-native code it looks like the best way to handle this is to use `SYNTHETIC_OFFSET` which I didn't know existed until today. That will generate the debug information that native needs (line 0, column 0) and as far as I can tell should not change the JVM behavior. I'll try that out.

**Comment by udalov** [comment]
According to @vvlevchenko, the problem appeared even after 05c662ec554 and can be reproduced on this sample:
```
import kotlin.time.*
@OptIn(kotlin.time.ExperimentalTime::class)
fun main() {
  TimeSource.Monotonic.markNow()
}
```

It looks like LLVM does need this info, so if the solution with `SYNTHETIC_OFFSET` doesn't work out, I guess we need to call into an extension point in several points in psi2ir, where JVM IR doesn't need line numbers.

**Comment by madsager** [comment]
> It looks like LLVM does need this info, so if the solution with `SYNTHETIC_OFFSET` doesn't work out (here and in delegated members), I guess we need to call into an extension point in several points in psi2ir, where JVM IR doesn't need line numbers.

Thanks for the heads up! `SYNTHETIC_OFFSET` does work here. I'll double check that it also works for the example provided here and prepare a patch to use it for the delegated members change as well.

**Comment by madsager** [comment]
I can confirm that using `SYNTHETIC_OFFSET` works for this issue as well. Fix is here: https://github.com/JetBrains/kotlin/pull/3771

**Comment by udalov** [comment]
Looks like this also fixes the newly added `IrKotlinEvaluateExpressionTestGenerated$SingleBreakpoint.testDataClassCopy`, could you please unmute it?

**Comment by madsager** [comment]
> Looks like this also fixes the newly added `IrKotlinEvaluateExpressionTestGenerated$SingleBreakpoint.testDataClassCopy`, could you please unmute it?

Done, thanks!

**Comment by udalov** [comment]
Thank you!

**Pull request merged**
