### PR TITLE
KT-20583 Report "redundant let" even for `it` in argument position

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-20583

### CODE REVIEW

**Comment by mglukhikh** [comment]
Looks good, but I'd like to test it on our code base first. I remember well enough that "redundant let" has a tendency of giving false positives :)

**Comment by mglukhikh** [comment]
BTW this case is not "false positive". Inspection is not reported when we expect, so it's "false negative".

**Comment by t-kameyama** [comment]
Sorry my mistake. This is "false negative".

**Comment by mglukhikh** [comment]
Merged, thank you. @t-kameyama I sent you an e-mail yesterday, have you received it?

**Comment by t-kameyama** [comment]
@mglukhikh I replied. Thank you.

**Pull request closed without merging**
