### PR TITLE
IR/Android: place the cache field first

### PR DESCRIPTION
**Pull request by pyos**
https://youtrack.jetbrains.com/issue/KT-49799

to avoid NPEs if it is used during instance initialization.

### CODE REVIEW

**Comment by chxchen** [comment]
May I ask when will release this commit?

**Comment by udalov** [comment]
Thanks!

**Comment by udalov** [comment]
@chxchen 1.6.10

**Comment by lwld** [comment]
For anyone watching this, it's now working fine again when updating to Kotlin `1.6.10` (released yesterday: https://github.com/JetBrains/kotlin/releases/tag/v1.6.10).

**Comment by Mathbl** [comment]
Hi, 

I still get random crashes like these:
```
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
        at com.agendrix.android.views.widgets.RequestStatusPill._$_findCachedViewById(Unknown Source:6)
        at com.agendrix.android.views.widgets.Badge.init(Badge.kt:56)
        at com.agendrix.android.views.widgets.Badge.<init>(Badge.kt:48)
        at com.agendrix.android.views.widgets.RequestStatusPill.<init>(RequestStatusPill.kt:29)
        at com.agendrix.android.views.widgets.RequestStatusPill.<init>(RequestStatusPill.kt:25)
        at com.agendrix.android.views.widgets.RequestStatusPill.<init>(Unknown Source:11)
```

Using Kotlin 1.6.10, Android Studio Chipmunk | 2021.2.1 Canary 7.

Any ideas why?

**Comment by udalov** [comment]
@Mathbl Most likely this is [KT-50627](https://youtrack.jetbrains.com/issue/KT-50627), which is going to be fixed in the upcoming Kotlin 1.6.20.

**Pull request merged**
