### PR TITLE
KT-20357 Add samples for padStart() and padEnd()

### PR DESCRIPTION
**Pull request by gen0083**
https://youtrack.jetbrains.com/issue/KT-20357

### CODE REVIEW

**Comment by gen0083** [comment]
Thank you for reviewing.
I updated to wrap single quotes before printing, is this ok?

**Comment by ilya-g** [comment]
Now it's better, thanks. I'd rather rename `padWithoutChar` to `padWithSpace`, because it still is padded with char, just that char is space by default.

**Comment by gen0083** [comment]
ok, done it 👍

**Comment by gen0083** [comment]
hi, this pr seems to be already merged. so what should I do? should i close this?

**Comment by ilya-g** [comment]
Thanks for the samples, we've merged them manually.
Now it's ok to close this.

**Pull request closed without merging**
