### PR TITLE
#KT-1396 Fixed

### PR DESCRIPTION
**Pull request by mcgee**
https://youtrack.jetbrains.com/issue/KT-1396

### CODE REVIEW

**Comment by abreslav** [comment]
Thanks for your contribution, we will review it soon.

Next time please let us know in the issue tracker before starting to work on an issue, it will help us avoid possible duplicated effort. This time it went ok, and nobody else has been working on this simultaneously.

**Comment by abreslav** [comment]
Thanks for your contribution. It will be reviewed and integrated soon

**Comment by yole** [comment]
Could you please send a new pull request from a branch containing only this commit, and not from master? I'll merge it then.

**Comment by mcgee** [comment]
:ok_hand: 
https://github.com/JetBrains/kotlin/pull/786

**Pull request closed without merging**
