### PR TITLE
Example of allowing pure virtual files as JVM content roots

### PR DESCRIPTION
**Pull request by aragos**
For the Kotlin compiler to work with non-physical file systems it needs to allow `JvmContentRoot` entries that don't require a `java.io.File` property. This PR introduces `PhysicalJvmContentRoot` (equivalent to the existing `JvmContentRoot`, which becomes an interface), `PhysicalJvmClasspathRoot` (the same as the existing `JvmClasspathRoot`) as well as the new `VirtualJvmContentRoot`.

There are a variety of usages of the old `JvmClasspathRoot` that assume its containing a `java.io.File`, typically for interacting with non-core parts of the compiler, such as the CLI or KAPT3. All of them were already guarded against the presence of other types of content roots so guarding them specifically for physical files will continue to work. When using `VirtualJvmClasspathRoot` however one should be aware that such integrations may not work as expected because they will not have access to those virtual files.

### CODE REVIEW

**Comment by udalov** [comment]
Could you please
1) keep the current `JvmContentRoot` as is, to prevent any sort of unnecessary breaking changes for tools that might depend on kotlinc, and rather rename the base interface to something like `JvmContentRootBase` (maybe the name can be improved)?
2) reopen the pull request against the `master` branch of the repo. `-release` branches have a whole separate process and we're not able to merge to them from the GitHub. Also, 1.6.0 is basically scheduled for release already (and 1.6.10 is coming right after it), so the earliest this can end up in is 1.6.20.

**Comment by aragos** [comment]
Thanks for taking a look! I've reverted `PhysicalJvmContentRoot` to its original name (`JvmContentRoot`). Would you like me to do the same with `PhysicalJvmClasspathRoot`? 

Also reset the PR to be based on `master` as requested.

**Comment by udalov** [comment]
> Would you like me to do the same with `PhysicalJvmClasspathRoot`?

Yes, please! Thank you.

**Comment by aragos** [comment]
Alright, any changes but the introduction and use of `VirtualJvmClasspathRoot` should be reverted by the subsequent commits.

**Comment by udalov** [comment]
Thanks! Merged to master (1.6.20). I've also removed kdocs in 38273e6b3ce, since we don't usually document things that are mostly apparent from quick reading. Also added a `@Suppress("unused")` to prevent the class from being accidentally deleted.

**Pull request merged**
