### PR TITLE
KT-39602 Allow external interface companion

### PR DESCRIPTION
**Pull request by turansky**
Related issues:
* [KT-39602](https://youtrack.jetbrains.com/issue/KT-39602)
* [KT-40235](https://youtrack.jetbrains.com/issue/KT-40235)

cc @romanart

### CODE REVIEW

**Comment by aerialist7** [comment]
Hooray! Restriction will be removed!

**Comment by bashor** [comment]
Sorry, but we can't accept this change now for the following reasons:
* It requires more investigations and discussions use cases
* In the future we probably will have a “namespace” and maybe it will better cover existing use cases.
* It's not about feature parity with old BE, so no reason to rush.

**Comment by bashor** [comment]
Thank you for your effort!

**Comment by turansky** [comment]
> In the future we probably will have a “namespace” and maybe it will better cover existing use cases.

`namespace` is fine for simple cases, but it's not enought
Class frameworks (like yFiles) require both:
* `companion object` for class and interface meta (objects implement common interface) 
* `namespace` for enums and unions (no meta)

**Comment by bashor** [comment]
@turansky please add more details for your use-cases in [the issue](https://youtrack.jetbrains.com/issue/KT-39602).

**Pull request closed without merging**
