### PR TITLE
Add new expressions to template

### PR DESCRIPTION
**Pull request by NitroG42**
Added two missing expressions for live-templates, the className(), and
the functionName().

### CODE REVIEW

**Comment by yole** [comment]
The names of these functions conflict with the standard Java live template macro function names. You need to add the "kotlin" prefix to the names to ensure they don't conflict.

**Comment by NitroG42** [comment]
They are only available in the kotlin context, will the conflict still risk to occurs ?

**Comment by yole** [comment]
Yes, the names still need to be distinct to ensure the templates are parsed correctly.

**Comment by yole** [comment]
A test would be nice.

**Comment by yole** [comment]
Rewritten and merged manually.

**Comment by NitroG42** [comment]
Hello, I'm sorry for the lack of news, I planned to make the modifications (I updated the code), but wanted to learn how to make test for macro, and I just didn't have the time to do that right now.
Thank you for the rewriting, I'm glad it could be merged to the project though.

**Comment by yole** [comment]
It turns out that there's no really good way to test a live template macro in the IntelliJ Platform, so I pushed the change without tests.

**Pull request closed without merging**
