### PR TITLE
JVM IR: Avoid redundant coercions in ExpressionCodegen 

### PR DESCRIPTION
**Pull request by sfs**
CC @kandersen 

This PR changes `ExpressionCodegen` to only coerce `PromisedValues` right before materialization. This is closer to what the JVM backend did and fixes some tests. It's also cleaner. Here's what's changed:
- We now produce correct owners for field accesses. Previously we would sometimes produce owners referring to a superclass of the current class. The JVM was fine with this, *unless* you also introduce an unnecessary CHECKCAST...
- The java Class to KClass coercions are now properly restricted to annotation classes.
- We no longer produce redundant casts for constants (`bipush 8; i2l`, etc...)
- We generally produce fewer casts, which probably fixes more Java interoperability bugs. Since we cannot reliably identify platform types in Kotlin due to erased generics and the absence of platform types in the IR backend, we have to be careful about introducing casts. Ideally, we should only add casts when it is necessary to produce valid bytecode.

### CODE REVIEW

**Comment by dnpetrov** [comment]
Looks good to me. I'll run tests and merge manually.

**Comment by kandersen** [comment]
Just noticed this hit (at least) 3 issues in FIR:
```
INCORRECT IRSETVARIABLE EXPRESSION TYPE
org.jetbrains.kotlin.codegen.ir.FirBlackBoxCodegenTestGenerated$Properties$Lateinit$Local > testCapturedLocalLateinit FAILED
org.jetbrains.kotlin.codegen.ir.FirBlackBoxCodegenTestGenerated$Closures$CapturedVarsOptimization > testCapturedInCrossinline FAILED
org.jetbrains.kotlin.codegen.ir.FirBlackBoxCodegenTestGenerated$LocalClasses > testRecaptureVarCapturedInLocalClass3 FAILED
org.jetbrains.kotlin.codegen.ir.FirBlackBoxCodegenTestGenerated$Closures > testKt2151 FAILED
org.jetbrains.kotlin.codegen.ir.FirBlackBoxCodegenTestGenerated$Functions > testKt1739 FAILED

CAN BE UNMUTED
org.jetbrains.kotlin.codegen.ir.FirBlackBoxCodegenTestGenerated$JavaInterop$NotNullAssertions > testParamAssertionMessage FAILED
org.jetbrains.kotlin.codegen.ir.FirBlackBoxCodegenTestGenerated$Casts$Functions > testAsFunKSmall

VALIDATION ERROR
org.jetbrains.kotlin.codegen.ir.FirBlackBoxCodegenTestGenerated$Bridges > testKt12416 FAILED
org.jetbrains.kotlin.codegen.ir.FirBlackBoxCodegenTestGenerated$Bridges > testTwoParentsWithDifferentMethodsTwoBridges2 FAILED
org.jetbrains.kotlin.codegen.ir.FirBlackBoxCodegenTestGenerated$Bridges > testTwoParentsWithDifferentMethodsTwoBridges FAILED
org.jetbrains.kotlin.codegen.ir.FirBlackBoxCodegenTestGenerated$Bridges > testDiamond FAILED
```
Will commit an unmute and a fix to IrSetVariable, ASAP. Don't know the root of the validation error yet.

**Comment by udalov** [comment]
@kandersen I believe some of these has been already fixed in master, or if not, still reproducible there. I've seen validation errors in FIR tests in my remote runs too. So it's not necessarily caused by these changes.

**Comment by dnpetrov** [comment]
Yet, I see a bunch of failures that look relevant.
E.g., there is a failing assertion in org.jetbrains.kotlin.codegen.ir.FirBlackBoxCodegenTestGenerated$Closures#testKt2151 in code added in 33f4f69d14b5228e391296a0c3d03cbca1d7b486.

Please, investigate test failures in FirBlackBoxCodegenTestGenerated.

**Comment by sfs** [comment]
@dnpetrov The assertion failures are just errors in the FIR generated IR (`Fir2IrVisitor` creates `IrSetVariableImpl` with non-unit return type). @kandersen already has a fix for this and should have a separate PR out soon.

**Comment by kandersen** [comment]
Whew, there we go! Sorry for the delay, new Git gymnastics were learned during the commit of these changes :)

**Comment by sfs** [comment]
Thank you!

**Comment by dnpetrov** [comment]
Ok, changes look good to me.
I'll run tests (again) and push manually, if everything is ok.

**Comment by dnpetrov** [comment]
Now there are failing tests in Fir2IrTextTestGenerated. Looks like you should simply update corresponding testData. Still, please, look at those failures and make sure the IR after FIR2IR looks like what you want.

**Comment by sfs** [comment]
Fix tests and rebased on master. The tests in question only differ in the return type of `IrSetVariable`, which sometimes causes some casts to be move around.

**Comment by dnpetrov** [comment]
Ok, now everything is fine.
Pushed manually.
bc2b96f6344729f632229647d99561bafdaa7822
2b2ae8a5f1c85b7f08ba4157a92590b04ca6f34d
5760c0be9cdeffb00cee05711b30aff6aa1c586a
4f36e2ccfcb8d4cc3c75adf567a8986d7feff74e
4dc6583f313c2b50b623224a2a288d619b09f51b
577250d73f4f642c3f5c578e6afe2981bf5db89d
de33b83bb3a22613e6b28c8c27487ff48bfec984
50c477bee10404f9f3e76563a814f9b884d7ca6b

**Pull request closed without merging**
