### PR TITLE
KT-34258: Make sure to clean up stale files even if no Kotlin sources

### PR DESCRIPTION
**Pull request by gavra0**
If running incrementally, even if there aren't any Kotlin sources to
compile, there could be stale output files that need to be removed. E.g
stub generation must have generated .java files removed if all Kotlin
sources are removed. Kotlin compile task will be skipped only if there
are no Kotlin sources and task run is non-incremental.

Test: KaptIncrementalIT.testRemoveAllKotlinSources

### CODE REVIEW

**Comment by gavra0** [comment]
@altsvetkov Can you please have a look at this PR, as it impacts incremental compilation?

**Comment by gavra0** [comment]
@altsvetkov Can you please review this PR?

**Comment by yanex** [comment]
The commit looks good to me. I will merge it.

**Comment by yanex** [comment]
Merged to master (e07b2e30e2789a7110e3b861cbb63c5ff0de5c0e, 7f77cc55f3c31a46cd04da7161919475e219ce04). Thanks for the contribution!

**Pull request closed without merging**
