### PR TITLE
kotlinx.serialization: Fix interface delegation when delegate is initialized in a function

### PR DESCRIPTION
**Pull request by 770grappenmaker**
This fixes the following issues: (not from YouTrack because they are kotlinx.serialization related)
Kotlin/kotlinx.serialization#241
Kotlin/kotlinx.serialization#1039

Originally, if you tried to access methods implemented by a delegate, and the object was retrieved as a result of deserialization by kotlinx.serialization, you would get an NPE because the delegate field remained uninitialized. This fixes that issue.

The following snippet would throw an NPE before:
```kt
fun interface A {
    fun a()
}

fun interface B {
    fun b()
}

fun implA() = A { println("Hello, world!") }
fun implB() = B { println("Hello, kotlin!") }

@Serializable
data class Test(val text: String = "") : A by implA(), B by implB()

fun main() {
    val test: Test.() -> Unit = {
        a()
        b()
    }

    with(Test(), test)
    with(Json.decodeFromString("{}"), test)
}
```

Expected output:
```
Hello, world!
Hello, kotlin!
Hello, world!
Hello, kotlin!
```
Actual output (before fix):
```
Hello, world!
Hello, kotlin!
<NullPointerException>
```

### CODE REVIEW

**Comment by 770grappenmaker** [comment]
Update: I found a bug in my bugfix: because the constructor generated by ktx serialization contains different parameter (order), the preferred way of referencing value parameters is by using the fields (that are set by the deserializer). I added a transfomer for the intialization expression to use the `propertyByParamReplacer`.

**Comment by 770grappenmaker** [comment]
Would a couple of unit tests be helpful?

**Review by sandwwraith — COMMENTED** [review]
Code is OK, yes, please add tests

**Review by ahmedalishah31 — APPROVED** [review]
gh pr checkout 4727

**Comment by ahmedalishah31** [comment]
access

**Comment by sandwwraith** [comment]
@770grappenmaker Tests are auto-generated. You need to do the following:

1. Add .kt file to `boxIr` folder or `codegen` folder depending on what kind of test you want (codegen compares dumped bytecode, box is a regular 'black-box' compiler unit test which compiles and then executes test code)
2. Run `./gradlew generateTests`
3. Files `TestsGenerated` would be updated. Run newly generated tests, it will create `.txt` files in codegen for you. Check if they're valid and add them to commit.

**Comment by 770grappenmaker** [comment]
Right, that is the part where I got stuck on: I added a coderen test but I had no idea how to dump it, thanks. I'll add the tests ASAP.

**Comment by 770grappenmaker** [comment]
I added a code generation test, tell me what you think.

**Comment by 770grappenmaker** [comment]
Is there an issue to review my code regarding the war?

**Comment by sandwwraith** [comment]
Sorry for the delay, indeed I've been distracted by the news. I'll return to the PR soon

**Comment by 770grappenmaker** [comment]
Just wanted to add that a cherry-pick to the next release candidate version is appriciated, it would resolve workarounds for me because right now I have to deep-clone deserialized objects before I can use them.

**Comment by 770grappenmaker** [comment]
Any update on this?

**Comment by sandwwraith** [comment]
Yeah, I've rechecked it yesterday, everything fine.
Unfortunately I can't cherry-pick it to 1.6.20 since we have a strict policy that allows only critical fixes to be included between RCs and release.

**Review by sandwwraith — APPROVED** [review]

**Comment by sandwwraith** [comment]
Big thanks for all your time and efforts!

**Comment by 770grappenmaker** [comment]
No problem, thanks for merging!

**Pull request merged**
