### PR TITLE
[IR] Have JVM codegen respect the GenerateClassFilter supplied to GenerationState

### PR DESCRIPTION
**Pull request by kandersen**
This change originates with KTIJ-21907: the IR fragment compiler includes various, transitive dependencies of the fragment code including the file with the breakpoint.

If...
  1. the fragment sufficiently depends on its context that the file with the breakpoint is included; and...
  2. the file with the breakpoint contains _other_, unrelated declarations that call inline functions in a different file; and...
  3. that file is not included by the fragment compiler...
... then compilation of the files included due to 2. cause failures in the JVM codegen when it wants to inline the bytecode for those definitions.

The fragment compiler discards the generated code regardless, so we may as well not generate the bytecode. Alternatively, we could _include_ all the files, remedying 3., but at the limit that would mean including the entire project which does not seem desirable either.

### CODE REVIEW

**Comment by kandersen** [comment]
@udalov I would like a "design review" of this approach. This _works_, but feels a little icky. 

Do you have an idea for how to generalize the class filter appropriately? It has very few uses, so refactoring/redesigning it seems very feasible.

**Comment by udalov** [comment]
I think this is fine as a solution. I can merge it after a remote run. But I wonder, should we also handle `shouldGenerateClass` accordingly in JVM IR? Is similar problem possible with it?

**Comment by kandersen** [comment]
I wonder too :thinking: Would you just abort codegen down inside the IR ClassCodegen?

**Comment by udalov** [comment]
Thanks!

**Comment by kandersen** [comment]
Thank you! :)

**Pull request merged**
