### PR TITLE
idl2k cleanup

### PR DESCRIPTION
**Pull request by cy6erGn0m**
- Make it compilable
- Cleanup code
- Add tool compilation to complete maven build
- Regenerate stubs to get `operator` modifier when needed

### CODE REVIEW

**Comment by bashor** [comment]
ok

**Comment by cy6erGn0m** [comment]
@bashor fixed

**Comment by bashor** [comment]
ok

**Comment by cy6erGn0m** [comment]
@bashor thanks, merged manually

**Pull request closed without merging**
