### PR TITLE
FIR checker: apply (implemented) override checker to anonymous objects

### PR DESCRIPTION
**Pull request by jsjeon**
As described at https://youtrack.jetbrains.com/issue/KT-44695, (implemented) override checker checks regular classes only. Applying it to general `FirClass<*>`, however, can't report expected *_TYPE_MISMATCH_ON_OVERRIDE diagnostics for properties. That's because some direct overridden properties aren't populated properly. 1st commit address that first, and 2nd commit applies the override checker to general `FirClass<*>`.

### CODE REVIEW

**Comment by jsjeon** [comment]
cc @mglukhikh or @demiurg906 just in case this is not under your radar. :)

**Review by mglukhikh — DISMISSED** [review]
Looks good, I will re-check and merge.

**Comment by mglukhikh** [comment]
This PR introduces some resolve errors
```
      e: /testProject/libraries/tools/new-project-wizard/src/org/jetbrains/kotlin/tools/projectWizard/plugins/StructurePlugin.kt: (49, 63): None of the following functions are applicable: [org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/StringSettingType.Builder.title,org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/SettingBuilder.title]
      e: /testProject/libraries/tools/new-project-wizard/src/org/jetbrains/kotlin/tools/projectWizard/plugins/StructurePlugin.kt: (58, 63): None of the following functions are applicable: [org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/StringSettingType.Builder.title,org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/SettingBuilder.title]
      e: /testProject/libraries/tools/new-project-wizard/src/org/jetbrains/kotlin/tools/projectWizard/plugins/StructurePlugin.kt: (65, 63): None of the following functions are applicable: [org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/StringSettingType.Builder.title,org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/SettingBuilder.title]
      e: /testProject/libraries/tools/new-project-wizard/src/org/jetbrains/kotlin/tools/projectWizard/plugins/StructurePlugin.kt: (72, 63): None of the following functions are applicable: [org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/StringSettingType.Builder.title,org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/SettingBuilder.title]
```

**Comment by jsjeon** [comment]
> This PR introduces some resolve errors
> 
> ```
>       e: /testProject/libraries/tools/new-project-wizard/src/org/jetbrains/kotlin/tools/projectWizard/plugins/StructurePlugin.kt: (49, 63): None of the following functions are applicable: [org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/StringSettingType.Builder.title,org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/SettingBuilder.title]
>       e: /testProject/libraries/tools/new-project-wizard/src/org/jetbrains/kotlin/tools/projectWizard/plugins/StructurePlugin.kt: (58, 63): None of the following functions are applicable: [org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/StringSettingType.Builder.title,org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/SettingBuilder.title]
>       e: /testProject/libraries/tools/new-project-wizard/src/org/jetbrains/kotlin/tools/projectWizard/plugins/StructurePlugin.kt: (65, 63): None of the following functions are applicable: [org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/StringSettingType.Builder.title,org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/SettingBuilder.title]
>       e: /testProject/libraries/tools/new-project-wizard/src/org/jetbrains/kotlin/tools/projectWizard/plugins/StructurePlugin.kt: (72, 63): None of the following functions are applicable: [org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/StringSettingType.Builder.title,org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/SettingBuilder.title]
> ```

Probably I'm having an old test data, but running full pipeline test shows a similar error:
```
new-project-wizard.main: main-java-production, 129 files (11281 lines)
        1st error: None of the following functions are applicable: [org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/StringSettingType.Builder.title, org/jetbrains/kotlin/tools/projectWizard/core/entity/settings/SettingBuilder.title]
```
Will take a look at that.

**Comment by jsjeon** [comment]
Reproduced the issue with an existing bb test: https://github.com/JetBrains/kotlin/pull/4098/files#diff-ea786ad177bc848bee1486a970f51ddf579074a7be652d5e8b1b4ac07aed373c

Not sure why we didn't do so before, but doesn't it make sense to bail out the override check if base candidate is not overridable, e.g., private or final? `AbstractFirOverrideScope#getOverridden` checks modality, but I guess it's better/proper to do such checks before/when populating direct overridden symbols.

According to full pipeline test (with probably old test), 3rd commit resolved the issue.

**Comment by jsjeon** [comment]
https://teamcity.jetbrains.com/buildConfiguration/Kotlin_KotlinForGoogle_AggregateBranch/3307654

Seems like IDE test data needs an update after #4103. Done.

**Comment by mglukhikh** [comment]
Merged manually 👍

**Pull request closed without merging**
