### PR TITLE
Inspection detecting redundant Unit return type

### PR DESCRIPTION
**Pull request by nd**

### CODE REVIEW

**Comment by yole** [comment]
There's already RemoveExplicitTypeIntention which provides the same action as your intention on the `fun bar(): Unit = println("ok")` example. We should avoid showing such duplicated actions. Also, you don't need to reimplement the logic for deleting the type specification; simply `.setTypeReference(null)` should work.

**Comment by nd** [comment]
Reworked it so that RemoveExplicitTypeIntention also handles Unit return type in function with body

**Comment by yole** [comment]
Now the inspection highlights any return type of a function with an expression body as redundant, even if it is not Unit:

fun shazam(): Int = 1

**Comment by nd** [comment]
Thanks, fixed

**Comment by yole** [comment]
Thanks!

**Pull request merged**
