### PR TITLE
Implement Smart Enter Processor for adding a lambda block

### PR DESCRIPTION
**Pull request by cypressious**
Fixes #KT-6785

### CODE REVIEW

**Comment by cypressious** [comment]
Unfortunately, I haven't figured out how to make the unit tests work. I suspect it has to do with previous fixers only working on the syntax level so the call resolution stuff is broken in the test environment.

**Comment by cypressious** [comment]
Tests work after all if you use your own function instead of stdlib ones like `with`.

**Comment by cypressious** [comment]
Parameter names are not set anymore. Also the lambda is now in the same line.

**Comment by cypressious** [comment]
I simplified the whole logic. The caret is now set directly in the first pass so there is no need for a second pass anymore.

**Comment by yole** [comment]
Looks good now. Thanks a lot for your contribution!

**Comment by cypressious** [comment]
Great. I think I get the hang of the smart enter logic now. When I understood the multi-pass logic, everything became much more clearer.

**Pull request merged**
