### PR TITLE
Do not use hardcoded plugin ID for update checks

### PR DESCRIPTION
**Pull request by stigger**

### CODE REVIEW

**Comment by goodwinnk** [comment]
Would you mind merging it into one commit?

**Comment by stigger** [comment]
@goodwinnk Done.

**Comment by goodwinnk** [comment]
What exceptions are meant in commit message? Are they for Kotlin plugin? 

I think "Do not use hardcoded plugin ID for update checks" would be a better name, and some explanation why this is needed would be nice.

**Comment by stigger** [comment]
@goodwinnk Done

**Comment by goodwinnk** [comment]
Merged manually as 53946456cfe90100f1ffc4af9a0eefe5a60b2a35. Thank you!

**Pull request closed without merging**
