### PR TITLE
KT-12183 Implement an intention converting several calls with same receiver to with/apply/run

### PR DESCRIPTION
**Pull request by shiraji**
#KT-12183 Fixed

https://youtrack.jetbrains.com/issue/KT-12183

### CODE REVIEW

**Comment by mglukhikh** [comment]
What about chained calls like `a.foo().bar()` or `a.x.bar()`? There are no such tests, and I'm not sure they are handled correctly here.

**Comment by mglukhikh** [comment]
Also, seems important to distinguish `apply()` from two other functions here because it generates its result differently. I'd say that by default `apply()` should have less priority or even should not be shown if we do not want to use its result. `rcv.run()` and `with(rcv)` looks more logical in these situations.

**Comment by shiraji** [comment]
OK, then I would just remove intention for `apply()`. Then later, we can make it back if someone find a way to implement what @cypressious said https://youtrack.jetbrains.com/issue/KT-12183#comment=27-1866609 . What do you think?

**Comment by mglukhikh** [comment]
Yes, it's possible way. I just do not like an idea to have three effectively identical intentions.

**Comment by shiraji** [comment]
I have done a lot of changes here. Could you review this PR again, please?

**Comment by mglukhikh** [comment]
Sorry please, will merge it today and tomorrow :). We're in release rush now.

**Comment by shiraji** [comment]
Of course!

**Comment by mglukhikh** [comment]
I have to say that the code is not clean enough, because large part exists in both ConvertToScopeIntention and ConvertToApplyIntention. This should be solved before merging into master. I see that they have different base element types, but really it's not an obstacle. You can try to solve the problem yourself if you wish, or I can do it myself when we're out of release rush -- your choice.

**Comment by shiraji** [comment]
Let me work on that.

Are you suggesting they all have the same base element type, or create a Util class for delegation?

**Comment by shiraji** [comment]
OK, now `ConvertToScopeIntention` is the parent of all 3 intentions.

**Comment by mglukhikh** [comment]
So OK, I have finally merged it, thanks.

**Comment by shiraji** [comment]
Thanks! And congra to releasing 1.1!!!

**Pull request closed without merging**
