### PR TITLE
JVM_IR inliner fixes: inline lambdas in inline functions

### PR DESCRIPTION
**Pull request by pyos**
Extracted from #2646

### CODE REVIEW

**Comment by max-kammerer** [comment]
> Not sure what Steven's change has to do with this, as CallableReferenceLowering completely ignores inline lambdas. If you're planning on generating classes for them, the situation will become even worse as classes can't have reified type parameters.

Another possible approach to keep IrFunctionExpression as long as possible (now it's unrolled into function+function reference in provisionalFunctionExpressionPhase): seems it will allow to keep reified parameters as long as possible. But this approach conflicts with logic in  inlineCallableReferenceToLambdaPhase...

**Comment by pyos** [comment]
I still believe the correct approach is to make LocalDeclarationsLowering handle captured type parameters regardless of exactly what happens to inline lambdas. Even with non-reified ones, although the current logic works, it's kind of weird to have an IR equivalent of

```
fun <T> f() = g()
fun g() { /* T used here */ }
```

**Comment by max-kammerer** [comment]
Yes, it's the rightest  approach. But not sure that the easiest.

**Comment by max-kammerer** [comment]
Many thanks!

**Pull request merged**
