### PR TITLE
Improvements for arrays in stdlib (Fixes KT-1313 and KT-6577)

### PR DESCRIPTION
**Pull request by kharvd**
Implemented asIterable and indexOf(predicate) for arrays.

https://youtrack.jetbrains.com/issue/KT-1313
https://youtrack.jetbrains.com/issue/KT-6577

### CODE REVIEW

**Comment by kharvd** [comment]
Added more tests for asIterable

**Comment by orangy** [comment]
Thinking more about it, shouldn't we have asList() instead? It will cover asIterable() cases, and will trigger performance checks when appropriate – size is known and indexed access available.

**Comment by kharvd** [comment]
Sounds reasonable. Added asList() as well.

**Comment by orangy** [comment]
Working on integrating it into master. I will squash some commits and resolve issues in other pull request and then merge.

**Comment by orangy** [comment]
Fixed issues, moved asList to JVM-specific place, updated tests, merged manually.

**Pull request closed without merging**
