### PR TITLE
KT-20795 "replace explicit parameter with it" creates invalid code in case of overload ambiguities

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-20795

### CODE REVIEW

**Comment by yanex** [comment]
Broken case (1):

```
fun foo() {
    val a: (Int) -> Unit = { a -> println(a) }
}
```

**Comment by t-kameyama** [comment]
PTAL

**Comment by yanex** [comment]
Review: OK.

**Comment by yanex** [comment]
Merged into `master`. Thanks!

**Pull request closed without merging**
