### PR TITLE
Add always-do-smart-step setting to debugger

### PR DESCRIPTION
**Pull request by emrekultursay**
https://youtrack.jetbrains.com/issue/KT-31558

This feature already exists in Java debugger and should also exist
in Kotlin debugger in order to provide a consistent experience.

The core of the feature is documented below:
https://www.jetbrains.com/help/idea/stepping-through-the-program.html#step-into

### CODE REVIEW

**Comment by emrekultursay** [comment]
Ping.

**Comment by yalishevant** [comment]
Thank you for the PR, we will receive it but a bit later. For enabling this feature we need to fix SmartStepInto behavior before. There is a number of issues like [KT-35669](https://youtrack.jetbrains.com/issue/KT-35669), [KT-35701](https://youtrack.jetbrains.com/issue/KT-35701), [KT-31804](https://youtrack.jetbrains.com/issue/KT-31804), [KT-33738](https://youtrack.jetbrains.com/issue/KT-33738) and other, on what we are currently working. 
ETA: IJ 2021.2 - 2021.3

**Comment by nikita-nazarov** [comment]
Hello @emrekultursay. Thanks for your contribution! It was a conscious and discussed decision to disable this feature, and as @yalishevant mentioned, the Kotlin debugger stepping is not in an appropriate state for enabling it now due to the complexity of the Kotlin language. Our team is currently working on the debugger quality, and we will definitely add this setting in the future. But it will be more comfortable to do it from our side.

**Comment by emrekultursay** [comment]
FYI, we implemented and enabled this feature in Android Studio Dual (Java+Native) debugger.  Android Studio users can enable always-do-smart-step when debugging Kotlin as well as Java.

**Pull request closed without merging**
