### PR TITLE
KT-17580: Enable 'when' as statement exhaustiveness check for sealed classes

### PR DESCRIPTION
**Pull request by fitermay**
This feature was already in the code. Just needed to enable for statements.

### CODE REVIEW

**Comment by mglukhikh** [comment]
Sorry, but NON_EXHAUSTIVE_WHEN is intentionally not reported on sealed classes, it's a very controversial warning :(. About an issue, we need here an intention only, not an inspection or compiler warning.

**Comment by mglukhikh** [comment]
You can here, for example, take `AddWhenRemainingBranchesFix` and convert it to an intention, it's relatively easy. Then `NON_EXHAUSTIVE_WHEN` for enums can use this intention as quick-fix via `IntentionWrapper`.

**Comment by fitermay** [comment]
A sealed class is a type of enumeration, I'm surprised it is controversial. I will convert to intention.

**Comment by fitermay** [comment]
Hi,
I made the changes but in a slightly different way than suggested. Hope it's ok

**Comment by mglukhikh** [comment]
Yes, I think this way is also possible. Will check everything manually and merge.

**Pull request closed without merging**
