### PR TITLE
[JVM_IR] Do not generate property reference setter if inaccessible.

### PR DESCRIPTION
**Pull request by madsager**
Fixes KT-45064.

### CODE REVIEW

**Comment by pyos** [comment]
It would be better to either match the old backend in psi2ir by replacing this line https://github.com/JetBrains/kotlin/blob/a94086224d5ce2b4bfc581e7e20aea3c77ab5c51/compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/ReflectionReferencesGenerator.kt#L385 with `val mutable = ReflectionTypes.isNumberedKMutablePropertyType(type)`, or record the correct mutability in the frontend in the first place by passing `mutable = ...` here https://github.com/JetBrains/kotlin/blob/a94086224d5ce2b4bfc581e7e20aea3c77ab5c51/compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/tower/ResolvedAtomCompleter.kt#L373

**Comment by madsager** [comment]
Thanks @pyos! That does look cleaner, I'll try that out tomorrow and update the PR.

**Comment by madsager** [comment]
Yup, that works well and works for JS as well. Updated.

**Comment by udalov** [comment]
Thanks! Merged manually in 8852323a76e. I've changed the message to refer to psi2ir, and moved the test to `box/callableReference/property`.

**Comment by madsager** [comment]
> Thanks! Merged manually in [8852323](https://github.com/JetBrains/kotlin/commit/8852323a76eb6f528f361a9415f9df422489a1ee) (1.5.0 [ca1df95](https://github.com/JetBrains/kotlin/commit/ca1df9505280d70fcebe0c5ef40b9bf531b14aa0)). I've changed the message to refer to psi2ir, and moved the test to `box/callableReference/property`.

Thank you!

**Pull request closed without merging**
