### PR TITLE
Fixes KT-1494 Inspection to highlight missing documentation for public declarations

### PR DESCRIPTION
**Pull request by manas-chaudhari**
https://youtrack.jetbrains.com/issue/KT-1494

Currently, this checks for explicitly public declarations. Need suggestions on handling these scenarios:
- Should overriden public elements also be highlighted? What if the element in super class is protected and it has been made public in overriding class?
- When visibility is not specified, it is public implicitly. In this case should inspection report problems?

### CODE REVIEW

**Comment by yole** [comment]
* Since docs are inherited in Kotlin, you should not report an overridden public method if the base class method has documentation.
* If an element was protected and is now public, it needs documentation.
* The "public" keyword is highlighted as redundant in Kotlin, so you definitely should report problems where the visibility is implicitly public.

**Comment by manas-chaudhari** [comment]
Have taken care of above scenarios. Can proceed to review.

Another issue which bothers me:
- `main` gets highlighted for Missing Documentation. I am not sure if it is a good idea to make it an exception. If exceptions need to be made, are there other such keywords?

**Comment by manas-chaudhari** [comment]
Thanks. Will send over an update asap.

**Comment by manas-chaudhari** [comment]
Updated. Please check

**Comment by manas-chaudhari** [comment]
Have fixed the duplicate method issue. Also added a test for quickfix.

**Comment by yole** [comment]
Thanks for your contribution! I've squashed the commits in this PR, disabled the inspection by default and merged the PR.

**Pull request closed without merging**
