### PR TITLE
KT-28607 Extract/Introduce variable fails if caret is just after expression

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-28607

### CODE REVIEW

**Comment by igoriakovlev** [comment]
Please check for KT-28607 at YT for comments for this PR.

**Comment by t-kameyama** [comment]
Fixed

**Comment by igoriakovlev** [comment]
Hi @t-kameyama,

You forgot about KDoc comment, like:
for (x in a.list/** xxx **/) {

Also all theese commits must be squashed.

Thank you!

**Comment by t-kameyama** [comment]
Fixed and squashed.

**Comment by igoriakovlev** [comment]
Thank you for your help!

**Pull request merged**
