### PR TITLE
Add android.annotation annotations

### PR DESCRIPTION
**Pull request by tnorbye**

### CODE REVIEW

**Comment by tnorbye** [comment]
Filed https://youtrack.jetbrains.net/issue/KT-29586 for the compatibility impact of this. (I don't have permission to tag the issue with "for-language-committee" as instructed in https://kotlinlang.org/foundation/submitting-incompatible-changes.html)

**Comment by dzharkov** [comment]
Thanks!
Everything looks fine but you needed to run `:generateTests` gradle task to add actual JUnit tests for the test-data you've attached (or you can just fixup the following commit https://github.com/JetBrains/kotlin/commit/8b8bdb41c1b9e8b3335e88d807a56ac98df16a6b) 

Also, please add something like `^KT-29586 Fixed` to the body of the commit message to link the change and the issue.

**Comment by tnorbye** [comment]
Accidentally closed, oops!

**Comment by dzharkov** [comment]
Merged manually.
Thanks for the contribution!

**Pull request closed without merging**
