### PR TITLE
FIR checker: introduce DECLARATION_SIGNATURE_OR_DEFAULT positioning strategy

### PR DESCRIPTION
**Pull request by jsjeon**
and fix diagnostic `CONFLICTING_OVERLOADS` to use it

### CODE REVIEW

**Comment by mglukhikh** [comment]
Looks great but I don't understand the differences between PSI & LT. Will try to fix.

**Comment by mglukhikh** [comment]
I found problems both in diagnostic tests and in LT strategies, often they gave wrong offsets. Will provide the fix today.

**Comment by mglukhikh** [comment]
See here: https://github.com/JetBrains/kotlin/commit/151092fd0601a477301794bb96aa8b7fe6b4f7cf

**Review by mglukhikh — APPROVED** [review]

**Comment by mglukhikh** [comment]
Merged manually 👍

**Comment by jsjeon** [comment]
Thanks for the fix for LT strategies!

**Pull request closed without merging**
