### PR TITLE
KT-19762 Add inspection for unclosed `(Auto)Closeable` with quickfix to wrap usage in `use` 

### PR DESCRIPTION
**Pull request by DeFuex**
https://youtrack.jetbrains.com/issue/KT-19762

Old PR -> #1933

### CODE REVIEW

**Comment by mglukhikh** [comment]
I still do not see generated tests. Please generate tests and run them.

**Comment by oy-paddy** [comment]
雷猴

**Comment by mglukhikh** [comment]
Also, there is already `ConvertTryFinallyToUseCallIntention` which performs similar transformation but assumes there is `try...finally` and `resource.close()` is performed inside `finally`. May be some parts of code could be reused.

**Comment by DeFuex** [comment]
i created a new pr, since i had some issues with rebasing -> #2082

**Pull request closed without merging**
