### PR TITLE
Added an extension function on Char objects to get numeric value.

### PR DESCRIPTION
**Pull request by AdamMc331**
Ticket: https://youtrack.jetbrains.net/issue/KT-21569

### CODE REVIEW

**Comment by AdamMc331** [comment]
@ilya-g Following up on this to see if you have any questions. Let me know if there are changes that should be made. :)

**Comment by AdamMc331** [comment]
Thanks for the update! Will follow that conversation.

**Comment by AdamMc331** [comment]
@ilya-g popping in and rebased this branch. It looks like there's still no decision on the attached ticket. 

Figured I would nudge this and say I'm still happy to contribute this change and make any necessary adjustments. Let me know what I can do to help.

**Comment by ilya-g** [comment]
Thanks for PR, but we've decided to implement the functions to get the digit value of char a bit different in JVM: basically they will use https://docs.oracle.com/javase/8/docs/api/java/lang/Character.html#digit-char-int- under the hood.

**Pull request closed without merging**
