### PR TITLE
Update D8 used for dexing tests to version 2.1.96.

### PR DESCRIPTION
**Pull request by madsager**

### CODE REVIEW

**Comment by madsager** [comment]
@dnpetrov

**Comment by madsager** [comment]
Hmm, please hold off on this. I must have messed something up along the way. It looks like this is failing a lot of tests on teamcity in the current state. I'll investigate.

**Comment by madsager** [comment]
Updating to 2.1.96 instead which has a fix for invalid D8 assertions.

Turns out that D8 got a little more strict on the 2.2 branch. There it hits assertions because of invalid locals information generated by kotlinc. If we run without assertions the code generated is correct, so this is not an issue hitting end users. However, it does point at invalid locals information from kotlinc. I'll work on fixing those issues separately. For now, updating to 2.1.96 allows us to check that D8 can compile sam wrappers using invoke-dynamic.

**Comment by udalov** [comment]
Thanks! Merged manually in 41f5ac393a1.

We've enabled [dependency verification](https://docs.gradle.org/current/userguide/dependency_verification.html) for our build recently, so I've updated hashes in 81a85667633.

**Comment by madsager** [comment]
Thanks Alex, I'll make sure to update the hashes when updating to a 2.2 version.

**Pull request closed without merging**
