### PR TITLE
Support `EnumSet` on `kotlin.collections`.

### PR DESCRIPTION
**Pull request by mirromutth**
`java.util.EnumSet` has better performance than `HashSet` or `TreeSet` on `Enum`, because it using bits to store enums.

### CODE REVIEW

**Comment by mirromutth** [comment]
I try support `EnumSet` on JS platform, and use `enumSetOf` and `enumSetAllOf` for replace `EnumSet.of` and `EnumSet.allOf` (it only support JVM), their relationship looks like `XxxxEnum.values` and `enumValues<XxxxEnum>`

**Comment by mirromutth** [comment]
@ilya-g I think it work for JVM and JS platform now :-)

But I append `Int.bits`, `Long.bits`, `Int.trailingZeros` and `Long.trailingZeros` (also `java.lang.Integer.bitCount`, `java.lang.Long.bitCount`, `java.lang.Integer.numberOfTrailingZeros` and `java.lang.Long.numberOfTrailingZeros`) those useful for bitmap. (It is also support JS platform)

**Comment by mirromutth** [comment]
I should check my commits and make sure it have no merge commit and make a YouTrack before PR :-|

**Comment by ilya-g** [comment]
You can rebase your branch on master and force-push it. This PR will be updated with the new commits.

**Comment by mirromutth** [comment]
I will reopen this PR when my branch cleared

**Pull request closed without merging**
