### PR TITLE
KT-71262 Make sure that spawned konan drivers copy konan overrides

### PR DESCRIPTION
**Pull request by liutikas**

### CODE REVIEW

**Comment by jsjeon** [comment]
cc @SvyatoslavScherbina

**Review by homuroll — APPROVED** [review]

**Comment by liutikas** [comment]
What's missing for this to be merged?

**Comment by homuroll** [comment]
@liutikas Don't worry, I'll run the CI and will merge it myself.

**Comment by homuroll** [comment]
Landed in master: https://github.com/JetBrains/kotlin/commit/01608164e6c99c53b770713700dc4c61e2023545

**Pull request closed without merging**
