### PR TITLE
JVM_IR: try to fix SyntheticAccessorLowering.isAccessible again

### PR DESCRIPTION
**Pull request by pyos**
The condition on the relationship between the current class and the type of the receiver for protected members was the opposite of what the JVMS says, and yet somehow mostly worked?

 #KT-48331 Fixed
 #KT-20542 Fixed

### CODE REVIEW

**Comment by dnpetrov** [comment]
There's some code in `MethodSignatureMapper::mapToCallableMethod` that I'd like to be rewritten a little bit more explicitly - there might be a bug, see comment at https://github.com/pyos/kotlin/commit/cbf583fa171e3d46debd2d8121ded8c3ee4aa942#diff-f14a26272a357e37fdd94bd0e684e9c05f531c92beda190758793f8e6633bce1L385.
Everything else looks ok.

**Comment by pyos** [comment]
The code isn't OK after all - it broke protected super calls.

**Comment by pyos** [comment]
The new version should be better, and also fixes KT-20542.

**Comment by dnpetrov** [comment]
LGTM. I'll run tests and push.

**Comment by dnpetrov** [comment]
Pushed
7ce5556de32090ee5b4af2c6f268cec88a41f7d8
b1a8e8c7e69c940401ed10e93f4494054114d1ae

**Pull request closed without merging**
