### PR TITLE
KT-29444 "Make public" intention does not remove additional white-space to conform to proper style

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-29444

### CODE REVIEW

**Comment by mglukhikh** [comment]
I approve it but ask @goodwinnk to look at this PR shortly. NB: I suspect this PR can break some other tests. @t-kameyama Which tests did you run locally?

**Comment by goodwinnk** [comment]
I think it's not an expected behavior to reformat the whole declaration on modifier replacement. Can you narrow the applicability range to modifier only?

**Comment by t-kameyama** [comment]
I fixed and ran `IntentionTestGenerated$ChangeVisibility` test.

**Comment by goodwinnk** [comment]
Great fix, thank you!

I have merged it already as https://github.com/JetBrains/kotlin/commit/6f7830a4b2585bd517e725050f0722f74644136b with formatting check in `primaryConstructor.kt` test and test-data fixes in change signature tests.

**Pull request closed without merging**
