### PR TITLE
KT-13674 Add quickfix for FINAL_UPPER_BOUND

### PR DESCRIPTION
**Pull request by shiraji**
https://youtrack.jetbrains.com/issue/KT-13674

### CODE REVIEW

**Comment by mglukhikh** [comment]
Quick-fix you have implemented is not `RemoveFinalUpperBoundFix`. I'd name it like `InlineTypeParameterFix`, because it removes not a bound but a parameter itself, replacing its usages with usages of the bound. I'll integrate it in the source with some renaming & polishing but in fact it's not a solution of KT-13674.

**Comment by shiraji** [comment]
What would be the expected solution for this issue?

**Comment by mglukhikh** [comment]
As stated, it should remove a bound and leave parameter as is.

**Comment by mglukhikh** [comment]
However, I integrated your fix in master & 1.0.5, so thank you, this fix is also helpful.

**Comment by shiraji** [comment]
Thanks. I misunderstand the word "bound".

```
data class DC<T : Int>(val x: T, val y: String)
```

```
data class DC<T>(val x: T, val y: String)
```

Let me work on this, too.

**Comment by mglukhikh** [comment]
OK, with pleasure.

**Pull request closed without merging**
