### PR TITLE
Fix KT-11839 maven goal to execute kotlin script

### PR DESCRIPTION
**Pull request by yarulan**

### CODE REVIEW

**Comment by yarulan** [comment]
https://youtrack.jetbrains.com/issue/KT-11839

**Comment by cy6erGn0m** [comment]
Looks good to me, have pulled it into `rr/pull/857` and waiting for CI

**Comment by cy6erGn0m** [comment]
The only question is about static initialization: will look at it a bit later

**Comment by cy6erGn0m** [comment]
Merged into master and 1.0.3

**Comment by cy6erGn0m** [comment]
Thanks, @yarulan !

**Comment by yaroslav-ulanovych** [comment]
@cy6erGn0m No problem! Happy to see it merged.

**Pull request closed without merging**
