### PR TITLE
Update ReadMe.md

### PR DESCRIPTION
**Pull request by Trygets**
As a request form the JetBrains Marketing team we mention JB everywhere we can to make stronger associations of Kotlin is a product of JetBrains

### CODE REVIEW

**Comment by abelkov** [comment]
Are you from the JetBrains marketing team?

**Comment by Trygets** [comment]
I'm from the Kotlin marketing team :) 
https://jetbrains.team/m/Alex.Anisimov

**Comment by udalov** [comment]
But who's @1anisim then? https://github.com/JetBrains/kotlin/commit/5e46e5355d1

**Comment by Trygets** [comment]
It is me again :)
I have completely forgotten that that had created another account for JB related things 
Let me close this PR and create another one from a proven account.

**Pull request closed without merging**
