### PR TITLE
KT-23977 wrong hint Unit redundant

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-23977

### CODE REVIEW

**Comment by mglukhikh** [comment]
Could you please check that the case from https://youtrack.jetbrains.com/issue/KT-24066 also works after your fix?

**Comment by t-kameyama** [comment]
Added fix for https://youtrack.jetbrains.com/issue/KT-24066

**Comment by mglukhikh** [comment]
In general it's Ok but it seems to me we can done both these things in more simple way. I'll make a few experiments and merge it (as it is or with some polishing).

**Comment by mglukhikh** [comment]
Ok, I merged it. You can look at fixing / polishing commit: https://github.com/JetBrains/kotlin/commit/e07f83ddbc0cb1f558caef1f6d0e1db548fe9698. In particular: you took the first argument of function type, but should take the last one; it's better to use argument mapping to determine corresponding value parameter; it's better to use `getTargetFunctionDescriptor` to determine which function we are returning from.

**Pull request closed without merging**
