### PR TITLE
Add arm32 softfp as target platform for Kotlin Native

### PR DESCRIPTION
**Pull request by kellermanrivero**
Dear developers, 

This is a early-draft PR to include support for Linux Arm32 Soft FP targets. I would like to get early feedback on this idea so I'm publishing this PR as-is. Since most of the configuration is similar to Linux Arm32 Hard FP, this is mostly a copy-paste driven solution and final compiler flags for soft-fp variant may still need some tweaks. 

This PR assumes there's a GCC toolchain compiled with `--with-float=softfp `.

### CODE REVIEW

**Comment by sbogolepov** [comment]
Hi! First of all, thanks for the PR :)
Unfortunately, we can’t accept it because every new Kotlin/Native target is a burden. For example:
* We have to build and maintain toolchains as targets are highly coupled to them.
* Every new target increases the size of compiler distribution and CI build times.
* Targets should be added and maintained in the official kotlinx libraries (many of the existing targets are not supported yet!).

That is why we are very conservative when it comes to adding to targets to Kotlin/Native compiler. Of course, the current situation can and should be improved, but it’s quite a task. See https://youtrack.jetbrains.com/issue/KT-43974 for more information.

**Comment by kellermanrivero** [comment]
Hi,

Thanks for your response. Have you explored changing from Hard ABI to Soft ABI? For instance, Google dropped hard-float support in their NDK since extra performance gained by using Hard ABI is not worth it compared burden caused to maintain that target.

I wonder if Jetbrains could follow a similar approach, for instance you could support Soft-FP ABI ("-mfloat-abi=softfp") instead of Hard ABI, so you kill two birds with one stone. With this flag you could actually support two CPU architectures (with and without floating point support) and you get burden reduced on your side.

Does it makes sense to you? What are your thoughts?

**Comment by sbogolepov** [comment]
What you suggest will make Kotlin/Native unusable for some of our current users. For example, let's imagine that we switched to `-mfloat-abi=softfp` in the next Kotlin release. What would happen to programs written in Kotlin/Native that are running in armhf environment, that is, C libraries that they are using are passing float arguments via special registers?

**Comment by kellermanrivero** [comment]
You're right, hard and soft-fp ABI are not compatible. I think I misunderstood from your last comment that since actual hard target is still not fully supported in kotlin ecosystem (I mean in other libraries owned by you) then it was not fully adopted, so for me it makes sense to go to more broader audience target. 

However, if you have a "market share" of users/developers, already using hard float target then removing hard float will make Kotlin unusable for them.

**Comment by sbogolepov** [comment]
Yep, there are users of the `linuxArm32Hfp` target and we don't want to break their experience.

**Comment by VenkateswaranJ** [comment]
@sbogolepov `linuxArm32Hfp` it's removed in 1.9.0?

**Comment by sbogolepov** [comment]
@VenkateswaranJ not quite. https://kotlinlang.org/docs/native-target-support.html#deprecated-targets

**Pull request closed without merging**
