### PR TITLE
KT-22807: allow asynchronous testing in Kotlin/JS with QUnit

### PR DESCRIPTION
**Pull request by gcx11**
https://youtrack.jetbrains.com/issue/KT-22807

### CODE REVIEW

**Comment by anton-bannykh** [comment]
Don't see anything wrong with it at glance. Let me run the tests and get back to you.

**Comment by anton-bannykh** [comment]
Apart from `Any` -> `Any?` (which is nitpicking) I see nothing wrong. The code seems to be working and reporting failing/passing tests correctly.
cc @ilya-g

**Comment by ilya-g** [comment]
Why should it be `Any?` though? 
Both `Unit` and `Promise` have `Any` common supertype, right?

**Comment by anton-bannykh** [comment]
@ilya-g A `() -> Unit` lambda is translated to a function, which returns `undefined` in the current backend. Which means that an `external` function gets `undefined` as the result of the invocation.

A `() -> Any` lambda always returns something, e.g. `Unit` instance. Which means that a test framework will be receiving a `Unit` instance if it gets a Kotlin lambda with type `() -> Any`.

This is probably fine, because:
- These lambdas are generated as JS code (for now) and kind of bend the type system a little bit here
- Most test frameworks ignore the return value they don't understand

While all that is true, changing the lambda type to `() -> Any?` allows us to create lambdas which explicitely return `undefined` if needed (e.g. a test framework which asserts nothing is returned for some reason).

But as I said, this is basically nitpicking, is based on the current backend gotchas, and basically doesn't matter much.

**Comment by gcx11** [comment]
@anton-bannykh @ilya-g I have made changes to the return type, can this be merged?

**Comment by anton-bannykh** [comment]
@gcx11 done. Thanks!

**Pull request merged**
