### PR TITLE
Kotlin compiler and JSpecify nullness annotations: recognize both old (0.2) and new (0.3) package locations.

### PR DESCRIPTION
**Pull request by kevinb9n**
A first attempt to resolve [KT-55037](https://youtrack.jetbrains.com/issue/KT-55037/Support-jspecify-annotations-moved-to-the-new-package-org.jspecify.annotations-in-jspecify-0.3).

**NOT TESTED YET**

Note: I've searched exhaustively for all references to jspecify in this tree; the mentions in the following directories did not appear to me to need updates:

* compiler/test-infrastructure-utils/tests/org/jetbrains/kotlin/codeMetaInfo
* compiler/tests-common-new/tests/org/jetbrains/kotlin/test
* core/descriptors.jvm/src/org/jetbrains/kotlin/load/java
* jps/jps-common/test
* (or changelogs, license, etc.)

**What's next** I think the top priority would be supporting the new annotations:

* [`@NullUnmarked`](https://jspecify.dev/docs/api/org/jspecify/annotations/NullUnmarked.html) simply cancels the effects of `@NullMarked`
* [`@NonNull`](https://jspecify.dev/docs/api/org/jspecify/annotations/NonNull.html) is what it sounds like

These would need new tests but note that the current `foreignAnnotationTests` that reference `@NullnessUnspecified` can be converted to test `@NullUnmarked`. At that point the `@NullnessUnspecified` annotations should really be removed, since that annotation doesn't actually exist in JSpecify!

### CODE REVIEW

**Comment by kevinb9n** [comment]
@mglukhikh This one's for you! Note I haven't been able to build, so it's not tested yet. I was hoping kicking off the PR might do something.

**Comment by mglukhikh** [comment]
@kevinb9n Thank you! We will review it soon, and then merge.

**Comment by kevinb9n** [comment]
cool, and I'll keep trying to get a working build.

**Comment by mglukhikh** [comment]
@dzharkov I created a MR at Space and added you as the reviewer.

**Comment by mglukhikh** [comment]
@kevinb9n Hopefully we merge it around the New Year. No more work is required here. However, Pull Requests to support [KT-53834](https://youtrack.jetbrains.com/issue/KT-53834/Support-for-JSpecify-NullUnmarked) or [KT-53835](https://youtrack.jetbrains.com/issue/KT-53835/Support-for-JSpecify-NonNull) or [KT-50008](https://youtrack.jetbrains.com/issue/KT-50008/JSpecify-Nullable-annotation-on-type-parameter-bound-prevents-type-variable-usages-from-being-platform-types) will be greatly appreciated (better after merge of this one).

**Comment by mglukhikh** [comment]
Merged manually :+1:

**Pull request closed without merging**
