### PR TITLE
#KT-21502 Fixed  Intention to convert map.put(k, v) into map[k] = v

### PR DESCRIPTION
**Pull request by devbridie**
Adds a `ReplacePutWithArrayAssignIntention` which converts expressions of `mutableMap.put(a,b)` to `mutableMap[a] = b`.

### CODE REVIEW

**Comment by mglukhikh** [comment]
Mostly it's good. However, we shortly discussed it and decided that it's better to have an inspection, not an intention here. You can leave conversion to me or convert it yourself, your choice. In the latter case, you should derive from `AbstractKotlinInspection` and move your tests to `inspectionsLocal` directory in `testData`.

**Comment by devbridie** [comment]
Okay! I will convert it to an inspection.

**Comment by mglukhikh** [comment]
Thanks! Then I'w waiting for your changes

**Comment by devbridie** [comment]
I have converted it to an inspection. This PR should be squashed before merging.

**Comment by mglukhikh** [comment]
Yes of course. Will merge it soon.

**Comment by mglukhikh** [comment]
Thank you, polished, added to J2K and merged

**Pull request closed without merging**
