### PR TITLE
KT-19355 fix for "Variable expected" error after J2K for ++/--

### PR DESCRIPTION
**Pull request by achmyr**
https://youtrack.jetbrains.com/issue/KT-19355

### CODE REVIEW

**Comment by darthorimar** [comment]
@achmyr thank you for your pull request :smiley: 

Please, add tests for the new Java to Kotlin converter: `org.jetbrains.kotlin.nj2k.NewJavaToKotlinConverterSingleFileTestGenerated`.
(The "old" Java to Kotlin converter will be soon replaced by the new one, so there is no reason to create tests for it :)

Also, it worth adding a test for the `RemoveUnnecessaryParenthesesIntention` as it is the most common usecase of `KtPsiUtil#areParenthesesNecessary`

**Comment by achmyr** [comment]
@darthorimar I have made necessary changes, but struggling to figure out which gradle command would properly run tests from `kotlin/idea/tests/org/jetbrains/kotlin/idea/intentions/IntentionTestGenerated.java`

**Comment by darthorimar** [comment]
@achmyr If you want to do it via terminal: `./gradlew idea:test --tests 'org.jetbrains.kotlin.idea.intentions.IntentionTestGenerated$RemoveUnnecessaryParentheses'
`

**Comment by achmyr** [comment]
@darthorimar I've made amendments to the test scenarios and tests passing. Now all necessary changes done.

**Comment by darthorimar** [comment]
Thank you :-)

**Pull request merged**
