### PR TITLE
KT-13551 Add inspection + intention to replace `.let { it.foo() }` with `.foo()`

### PR DESCRIPTION
**Pull request by shiraji**
#KT-13551 Fixed

https://youtrack.jetbrains.com/issue/KT-13551

I'm having a problem with following case.

```kotlin
e?.let {
    it.to("").to("")
}
```

will be this.

```kotlin
e?.to("").to("")
```

And then IDEA report following error.

This error will be disappear if I hit any key to anywhere in editor.

### CODE REVIEW

**Comment by yole** [comment]
You're getting the error because the PSI structure that you get when you replace a call expression with its argument is different from the PSI structure that Kotlin builds for this text. You need to fix this. Please use the Tools | View PSI Structure... menu item in the debug IDEA (the one started when you run the "IDEA" run configuration in the Kotlin project) to see the differences between the two.

**Comment by shiraji** [comment]
I didn't know such tool. 

Maybe I used the tool a wrong way but I could not find the difference of PSI structure.

Here is the code I checked it.

```kotlin
fun foo(text: String?) {
    text?.to("").to("")
}
```

When there is error, PSI structure looks the following

```
JetFile: Dummy.kt(0,51)
  PACKAGE_DIRECTIVE(0,0)
    <empty list>
  IMPORT_LIST(0,0)
    <empty list>
  FUN(0,50)
    PsiElement(fun)('fun')(0,3)
    PsiWhiteSpace(' ')(3,4)
    PsiElement(IDENTIFIER)('foo')(4,7)
    VALUE_PARAMETER_LIST(7,22)
      PsiElement(LPAR)('(')(7,8)
      VALUE_PARAMETER(8,21)
        PsiElement(IDENTIFIER)('text')(8,12)
        PsiElement(COLON)(':')(12,13)
        PsiWhiteSpace(' ')(13,14)
        TYPE_REFERENCE(14,21)
          NULLABLE_TYPE(14,21)
            USER_TYPE(14,20)
              REFERENCE_EXPRESSION(14,20)
                PsiElement(IDENTIFIER)('String')(14,20)
            PsiElement(QUEST)('?')(20,21)
      PsiElement(RPAR)(')')(21,22)
    PsiWhiteSpace(' ')(22,23)
    BLOCK(23,50)
      PsiElement(LBRACE)('{')(23,24)
      PsiWhiteSpace('\n    ')(24,29)
      DOT_QUALIFIED_EXPRESSION(29,48)
        SAFE_ACCESS_EXPRESSION(29,41)
          REFERENCE_EXPRESSION(29,33)
            PsiElement(IDENTIFIER)('text')(29,33)
          PsiElement(SAFE_ACCESS)('?.')(33,35)
          CALL_EXPRESSION(35,41)
            REFERENCE_EXPRESSION(35,37)
              PsiElement(IDENTIFIER)('to')(35,37)
            VALUE_ARGUMENT_LIST(37,41)
              PsiElement(LPAR)('(')(37,38)
              VALUE_ARGUMENT(38,40)
                STRING_TEMPLATE(38,40)
                  PsiElement(OPEN_QUOTE)('"')(38,39)
                  PsiElement(CLOSING_QUOTE)('"')(39,40)
              PsiElement(RPAR)(')')(40,41)
        PsiElement(DOT)('.')(41,42)
        CALL_EXPRESSION(42,48)
          REFERENCE_EXPRESSION(42,44)
            PsiElement(IDENTIFIER)('to')(42,44)
          VALUE_ARGUMENT_LIST(44,48)
            PsiElement(LPAR)('(')(44,45)
            VALUE_ARGUMENT(45,47)
              STRING_TEMPLATE(45,47)
                PsiElement(OPEN_QUOTE)('"')(45,46)
                PsiElement(CLOSING_QUOTE)('"')(46,47)
            PsiElement(RPAR)(')')(47,48)
      PsiWhiteSpace('\n')(48,49)
      PsiElement(RBRACE)('}')(49,50)
  PsiWhiteSpace('\n')(50,51)
```

After typing space and delete the space to remove the error. The result is following which is the same result

```
JetFile: Dummy.kt(0,51)
  PACKAGE_DIRECTIVE(0,0)
    <empty list>
  IMPORT_LIST(0,0)
    <empty list>
  FUN(0,50)
    PsiElement(fun)('fun')(0,3)
    PsiWhiteSpace(' ')(3,4)
    PsiElement(IDENTIFIER)('foo')(4,7)
    VALUE_PARAMETER_LIST(7,22)
      PsiElement(LPAR)('(')(7,8)
      VALUE_PARAMETER(8,21)
        PsiElement(IDENTIFIER)('text')(8,12)
        PsiElement(COLON)(':')(12,13)
        PsiWhiteSpace(' ')(13,14)
        TYPE_REFERENCE(14,21)
          NULLABLE_TYPE(14,21)
            USER_TYPE(14,20)
              REFERENCE_EXPRESSION(14,20)
                PsiElement(IDENTIFIER)('String')(14,20)
            PsiElement(QUEST)('?')(20,21)
      PsiElement(RPAR)(')')(21,22)
    PsiWhiteSpace(' ')(22,23)
    BLOCK(23,50)
      PsiElement(LBRACE)('{')(23,24)
      PsiWhiteSpace('\n    ')(24,29)
      DOT_QUALIFIED_EXPRESSION(29,48)
        SAFE_ACCESS_EXPRESSION(29,41)
          REFERENCE_EXPRESSION(29,33)
            PsiElement(IDENTIFIER)('text')(29,33)
          PsiElement(SAFE_ACCESS)('?.')(33,35)
          CALL_EXPRESSION(35,41)
            REFERENCE_EXPRESSION(35,37)
              PsiElement(IDENTIFIER)('to')(35,37)
            VALUE_ARGUMENT_LIST(37,41)
              PsiElement(LPAR)('(')(37,38)
              VALUE_ARGUMENT(38,40)
                STRING_TEMPLATE(38,40)
                  PsiElement(OPEN_QUOTE)('"')(38,39)
                  PsiElement(CLOSING_QUOTE)('"')(39,40)
              PsiElement(RPAR)(')')(40,41)
        PsiElement(DOT)('.')(41,42)
        CALL_EXPRESSION(42,48)
          REFERENCE_EXPRESSION(42,44)
            PsiElement(IDENTIFIER)('to')(42,44)
          VALUE_ARGUMENT_LIST(44,48)
            PsiElement(LPAR)('(')(44,45)
            VALUE_ARGUMENT(45,47)
              STRING_TEMPLATE(45,47)
                PsiElement(OPEN_QUOTE)('"')(45,46)
                PsiElement(CLOSING_QUOTE)('"')(46,47)
            PsiElement(RPAR)(')')(47,48)
      PsiWhiteSpace('\n')(48,49)
      PsiElement(RBRACE)('}')(49,50)
  PsiWhiteSpace('\n')(50,51)
```

**Comment by shiraji** [comment]
Fix it but it seems not best idea. Could you give me suggestion how to resolve this issue?

**Comment by shiraji** [comment]
Sorry accidentally hit close button.

**Comment by mglukhikh** [comment]
I've rewritten the intention and merged it manually. Thank you. You can see changed code in the master branch, if you're interested.

**Comment by shiraji** [comment]
Thanks. I will take a look.

**Pull request closed without merging**
