### PR TITLE
KT-18236 Add inspection for potentially wrongly placed unary operators

### PR DESCRIPTION
**Pull request by shiraji**
#KT-18236 Fixed

https://youtrack.jetbrains.com/issue/KT-18236

### CODE REVIEW

**Comment by cypressious** [comment]
Why not also unary plus? It could be overloaded.

**Comment by shiraji** [comment]
Good point. I will add that.

**Comment by shiraji** [comment]
done

**Comment by mglukhikh** [comment]
Thanks, merged into master

**Pull request closed without merging**
