### PR TITLE
Git: Ignore dependencies/dependencies.properties

### PR DESCRIPTION
**Pull request by saschpe**
It seems to be a user-specific generated file.

### CODE REVIEW

**Comment by 4u7** [comment]
Just wondering where did it come from? I don't have any in my working copy

**Comment by saschpe** [comment]
Judging from it's contents, it's IntelliJ (I'm using 2019.2.1):
```
#
#Thu Sep 05 13:27:32 CEST 2019
markdown.build.id=0.1.25
idea.build.id=191.6707.61
```

**Comment by 4u7** [comment]
Found that It is generated by `writeVersions` task in https://github.com/JetBrains/kotlin/blob/master/prepare/ide-lazy-resolver/build.gradle.kts
We don't run this task during development process, only on CI. Looks like you somehow triggered it. Have you called `writeVersions` manually?

**Comment by saschpe** [comment]
Could have been `./gradlew build` or `./gradlew install` as well.

**Comment by 4u7** [comment]
I got the problem and will fix it slightly other way. The problem is dependencies dir is not a best place for this artifact, I'll move it to the better place. Thank you!

**Pull request closed without merging**
