### PR TITLE
jvm-abi-gen: Do not write kotlin.Metadata default values (KT-39492)

### PR DESCRIPTION
**Pull request by sfs**
This does not affect compilation, but it causes problems in IntelliJ.

### CODE REVIEW

**Comment by udalov** [comment]
Thanks!

**Comment by nkoroste** [comment]
Thank you! what version of Kotlin do you think this will land in?

**Comment by udalov** [comment]
@nkoroste 1.6.20

**Comment by alexjlockwood** [comment]
Just curious, is there an estimate as to when 1.6.20 would be released with this bug fix?

**Comment by udalov** [comment]
@alexjlockwood It's currently planned to be released in February, but can be postponed a little.

**Pull request merged**
