### PR TITLE
FIR: fix some errors in local variable assignment analyzer

### PR DESCRIPTION
**Pull request by pyos**
* wrong method was called from FirDataFlowAnalyzer.exitFunctionCall;
 * map from function to affected properties should be keyed by symbol, not FirFunction, as the latter may change;
 * arguments of `return` and assignment statements should be visited, as they may contain lambdas.

### CODE REVIEW

**Comment by demiurg906** [comment]
Thank you!
I've sent this PR, https://github.com/JetBrains/kotlin/pull/4846 and https://github.com/JetBrains/kotlin/pull/4847 to remote run together

**Comment by pyos** [comment]
This and #4846 both touch compiler/tests-spec/testData/diagnostics/notLinked/dfa/pos/53.fir.kt, so one of them will need to be rebased on top of the other.

**Comment by demiurg906** [comment]
Yep, I know. A've already did it

**Comment by demiurg906** [comment]
Merged manually

**Pull request closed without merging**
