### PR TITLE
KT-52637 SCSS support

### PR DESCRIPTION
**Pull request by mpetuska**
[KT-52637](https://youtrack.jetbrains.com/issue/KT-52637/KJS-Gradle-Add-SCSS-webpack-config)
* DSL to KGP to enable SCSS support - just like for CSS. 
* Both, SCSS and CSS support implementations were optimised to allow more flexible webpack rule addition in the future and reduce code duplication.
* Lazy API introduced for both Webpack rules
* Exposed new `rules` WebpackConfig property which can be used by the users to add their own custom webpack rule implementations
* BREAKING: `cssSupport` is no longer a property but rather  DSL function. This is required to facilitate generic `rules` container

New usage:
```kotlin

abstract class CustomWebpackRule
@javax.inject.Inject
constructor(name: String) : org.jetbrains.kotlin.gradle.targets.js.webpack.KotlinWebpackRule(name) {
    init {
        test.set("/\\.txt\$/")
    }
    override fun validate() = true
    override fun dependencies(versions: NpmVersions) = listOf()
    override fun loaders() = listOf()
}
kotlin {
    target {
        browser {
            commonWebpackConfig {
                cssSupport {
                    enabled.set(true)
                }
                scssSupport {
                    enabled.set(true)
                }
                rules {
                    rule<CustomWebpackRule>("customRule") {
                        enabled.set(true)
                    }
                }
            }
        }
    }
}
```

### CODE REVIEW

**Comment by mpetuska** [comment]
FYI: The implementation of rules could be greatly simplified by not using discrete classes for each rule but instead providing them via a single container class and storing rules in NamedDomainObjectContainer. The actual rules for css and scss support would then get registered and configured via appropriate DSLs

**Comment by mpetuska** [comment]
Hi guys. I'm sure you're all busy, but could you at least provide some ETA for the initial review?

**Comment by ilgonmic** [comment]
Hi, sorry, I was partially available. I’ll take a look on Tuesday (21 June)

**Comment by mpetuska** [comment]
No worries. Thanks for the ETA.

**Comment by ilgonmic** [comment]
Looks good to me, thank you.
Could you please rebase on master and regenerate NPM versions? Because I made similar changes in parallel with versions.

**Comment by mpetuska** [comment]
@ilgonmic should be all dandy now.

**Comment by ilgonmic** [comment]
Thank you!
I run CI check, if it will be green, I'll merge

**Comment by mpetuska** [comment]
Splendid, can't wait for ut to land in the next release!

**Comment by mpetuska** [comment]
Fair enough. However I'd love to see KGP eventually fully utilising gradle's lazy API. Right now there's quite a mixed bag of lazy and regular properties being used, which makes it somewhat hard to integrate with from 3rd party plugin's perspective.

**Comment by mpetuska** [comment]
As a side note, I had some further thoughts about the API and thought that it would be better to replace `validate`, `loaders` and `dependencies` override functions with gradle lazy properties instead (getting rid of validate method entirely and just validating within the prop providers if needed). That way custom rules could be registered without having to declare separate classes.

I was about to start working on a PR for this, but I guess this would need to break cssSupport to bring lazy props back and as such should be left for 1.8. Happy to contribute this at a later date, just let me know when master is ready for such PR.

**Comment by danngyn** [comment]
Does this feature also work for with browser `binaries.library()` setup? Ideally any `.scss` files will be transpiled to `.css`, or included in the 'fat' output `.js` file  depending on some custom webpack configurations?

This is a great feature btw, would benefit developers a lot. Much appreciate your works.

**Comment by mpetuska** [comment]
Not sure, all it does is just add a webpack rule. So if you can achieve that with only webpack rules in a regular js project, then the same should be configurable with this feature too.

**Comment by danngyn** [comment]
> Not sure, all it does is just add a webpack rule. So if you can achieve that with only webpack rules in a regular js project, then the same should be configurable with this feature too.

By 'regular js project' do you mean `binaries.executable()`?

The webpack rules work for `binaries.executable()` but when switching to `binaries.library()` it does nothing - I believe the webpack does not touch when exporting the kotlin/js project as library.

```
    js(IR) {
        binaries.library()
        browser {
            commonWebpackConfig {
                cssSupport.enabled = true
            }
        }
    }
```
I suppose it's safe to assume this SCSS support feature only works for  `binaries.executable()` setup?

**Comment by mpetuska** [comment]
By 'regular js project' i mean the one that's using vanilla js or typescript and npm/yarn

**Comment by mpetuska** [comment]
Also it works for binaries.library test task too (since main compilation for such binaries does not use webpack)

**Comment by danngyn** [comment]
Gotcha! and thanks, looking forward to try it out.

**Pull request closed without merging**
