### PR TITLE
KT-45676: fix backing field annotation resolve

### PR DESCRIPTION
**Pull request by gharrma**
Please see the bug for more details: https://youtrack.jetbrains.com/issue/KT-45676

### CODE REVIEW

**Comment by PetukhovVictor** [comment]
@gharrma thanks for the pull request. I've ran internal build and tests with your change. Also could you add some tests for this change?

**Comment by gharrma** [comment]
Thanks! I added a regression test which fails without the fix.

**Comment by PetukhovVictor** [comment]
Both the build as a whole and all our tests are green with your change so I'm merging your PR. Thanks a lot for the contribution! We'll consider cherry picking this change into Kotlin 1.5.0. I'll let you know about it.

**Comment by PetukhovVictor** [comment]
FYI: the fix is included in 1.5.0 (1.5.0 RC).

**Pull request merged**
