### PR TITLE
Always add a local variable for its live ranges.

### PR DESCRIPTION
**Pull request by madsager**
There used to be code that extended a previous range instead.
However, that does not work as that extension could have the
local cover code where it does not exists. Since we no longer
extend the range of locals, we should always introduce a new
one even if there was another one for a previous range.

### CODE REVIEW

**Comment by ilmirus** [comment]
Thanks! I will take over the change: https://github.com/JetBrains/kotlin/tree/rr/ilmir/coroutines/extention-in-lvt

**Comment by madsager** [comment]
Thanks @ilmirus! Let me know if I can help. :)

**Comment by ilmirus** [comment]
@madsager This change is in master and is heading to 1.5.30. Thanks again! This draft can now be closed.

**Comment by madsager** [comment]
Thank you!

**Pull request closed without merging**
