### PR TITLE
KT-7718

### PR DESCRIPTION
**Pull request by nd**

### CODE REVIEW

**Comment by yole** [comment]
The intended formatting for this code is to wrap before the colon, not after it.

**Comment by goodwinnk** [comment]
@yole Wrapping is out of the scope of KT-7718. The fix looks valid to me, I going to test it on buildserver to see are there any accidental test fails in other test groups.

**Comment by yole** [comment]
Sure, just pointing out that the formatting is not optimal in any case

**Comment by goodwinnk** [comment]
Merged manually into 1.0.5 and master branches with slight modification in commit message and test.
Thank you!

**Pull request closed without merging**
