### PR TITLE
KT-45789 Transitive npm dependencies

### PR DESCRIPTION
**Pull request by mpetuska**
Closes [KT-45789](https://youtrack.jetbrains.com/issue/KT-45789)

### CODE REVIEW

**Comment by ilgonmic** [comment]
I am wondering what situation will occur, if direct and transitive dependency will be the same but different versions (with different cases when version ranges are compatible and incompatible).
It seems the most questionable in this issue

**Comment by mpetuska** [comment]
In any case, I think we can both agree that direct dependencies should take priority. I'll code that in.

**Comment by mpetuska** [comment]
To be clear, my first point was in context of version clashes between two transitive dependency sources, not between transitive and direct.

**Comment by mpetuska** [comment]
How's this:
1. If there's a direct version - use that and terminate resolution
2. If there's a clash between two transitive versions, take higher and warn

**Comment by ilgonmic** [comment]
Basically it is ok. But what if there will be versions like `^x.y.z` and `~a.b.c`. Do we consider such cases as necessary for resolution?

**Comment by mpetuska** [comment]
Do you think it should be toggled behind some feature flag? Or is it ok to just add it on top of existing workflow?

**Comment by ilgonmic** [comment]
I think it is ok without feature flag, because it affects mainly experimental `binaries.library()`

**Comment by mpetuska** [comment]
Ready for another look now.

**Comment by mpetuska** [comment]
A gentle reminder to have a look at this before I go ahead solving new merge conflicts :)

**Comment by ilgonmic** [comment]
I’ll take a look, will try tomorrow

**Review by ilgonmic — APPROVED** [review]

**Comment by ilgonmic** [comment]
LGTM, I'll run it on CI

**Comment by ilgonmic** [comment]
Merged in https://github.com/JetBrains/kotlin/commit/3e6253cedef703c4341bdc26d8ad2f5f8683a669
Thanks!

**Pull request closed without merging**
