### PR TITLE
[WIP] FIR: fix Java type enhancement

### PR DESCRIPTION
**Pull request by pyos**

### CODE REVIEW

**Comment by pyos** [comment]
Some of the code here touched by this PR is commonized in #4535, so it's probably better to do that one first.

**Comment by pyos** [comment]
@mglukhikh I've pushed *all* I have so far (including that other PR) into this branch, in case you're curious about the scope. Warnings are still not implemented though.

The tests are looking much better, but unfortunately type parameter bound (and probably supertype enhancement) breaks IDE mode (`:idea-frontend-fir:idea-fir-low-level-api:test`) because `FirThreadSafeSymbolProviderWrapper`'s `getClassLikeSymbolByFqName` cannot be recursively called with the same class id, but to correctly enhance `A<B>` we need to know the nullability of A's type parameter.

**Comment by mglukhikh** [comment]
@pyos So what's better to review now, this one or https://github.com/JetBrains/kotlin/pull/4535? Should we just close one of these two PRs and deal only with another one?

**Comment by pyos** [comment]
Well, the question is how long would it take to merge such a large PR... I'd prefer to merge at least some part of it instead of having to rebase the entire thing all the time.

**Comment by mglukhikh** [comment]
So do you recommend to review & merge https://github.com/JetBrains/kotlin/pull/4535 first as a base for this PR?

**Comment by pyos** [comment]
Yes, I still think that'd probably be better.

**Comment by pyos** [comment]
Will submit everything as separate pull requests.

**Pull request closed without merging**
