### PR TITLE
KT-25807: Fix Parcelize annotation implementing Parcelable.Creator<T>

### PR DESCRIPTION
**Pull request by rbares**
The JVM backend for `@Parcelize` currently ignores the generic type on `Parcelable.Creator<T>`, Consequently code requiring the correct `Parcelable` return type must cast from `Object`. This is particularly unsuitable for generated code such as AIDL, see https://youtrack.jetbrains.com/issue/KT-25807

Until the IR implementation in https://github.com/JetBrains/kotlin/pull/3271 is merged and becomes default, this PR provides a fix by implementing the generic interface as follows:
- Returning the relevant `Parcelable` type (`T`)
- Specifying the overridden methods, enabling the backend to generate suitable synthetic bridges
- Providing explicit class and field signatures to specify the type

Tests are updated accordingly, supported by a partial cherry-pick of https://github.com/JetBrains/kotlin/pull/3271/commits/e3c3e67e687f84886882048e7e339c28166b5056 from https://github.com/JetBrains/kotlin/pull/3271, with Steven's blessing. It should be noted that the unit tests for `android-extensions-compiler` were broken on master and do not appear to be included in CI.

These can be run as follows:
```
gradlew :plugins:android-extensions-compiler:test --tests "org.jetbrains.kotlin.android.parcel.*"
```

### CODE REVIEW

**Comment by udalov** [comment]
I've merged #3271 to master, could you please rebase your PR?

**Comment by rbares** [comment]
Rebased, dropping the cherry pick. Please note that the `openParcelize` test for the IR backend in `ParcelIrBoxTestGenerated` also fails on master. The relevant tests for this PR can be run as follows:
```
gradlew :plugins:android-extensions-compiler:test --tests "org.jetbrains.kotlin.android.parcel.ParcelB*"
```

**Comment by rbares** [comment]
Seen committed in 00ec50ff73bb690b0454a9ceba87a239ae98faf6, 8a9610d3afac2e13166413503fdd36707ef9b847, b39a65305dab7deaed27b9ca3aa1c9bb4d0060f5. Much appreciated.

**Comment by yanex** [comment]
@rbares Thank you for your contribution!

**Pull request closed without merging**
