### PR TITLE
ExternalTargetApi: Implement -sources.jar publishing APIs

### PR DESCRIPTION
**Pull request by sellmair**

### CODE REVIEW

**Review by AmrAfifiy — COMMENTED** [review]
LGTM but I have some questions

Overall is there a way for users to disable publication of a target or a compilation? Also is there a way to disable sources publishing?

**Comment by sellmair** [comment]
@AmrAfifiy : 
Right now, you would not be able to disable publication of a target. 
Which compilations get published is fully under your control as you have the control over what artifact go into the apiElementsPublished configuration .

However, sources publications do have a DSL in our regular target. 
You can find a test checking its behaviour in this MR here:

https://github.com/JetBrains/kotlin/pull/5152/files#diff-0effe80456b837b779b24cca22ae7713e80eccce70ec56fb135b67fb9ab72c62R147

**Comment by sellmair** [comment]
Oh the api `publishSources` is a KMP api on the KotlnTarget and therefore is universally available 👍

**Comment by sellmair** [comment]
Merged by Space

**Pull request closed without merging**
