### PR TITLE
KT-9934 Display Quick Documentation for reserved words

### PR DESCRIPTION
**Pull request by shiraji**
#KT-9934 Fixed

@semoro 
As we discussed at Slack, I let you implement the part for reading documentation from resources. 

https://youtrack.jetbrains.com/issue/KT-9934

### CODE REVIEW

**Comment by goodwinnk** [comment]
Thank you for this pull-request. I see this commit more like a framework, but I don't think it's a good idea to merge it to master at the current state. Current message "It is modifier" doesn't explain anything, and I think does more harm. 

Also `defined in` should be removed for keyword documentation.

I would suggest to select some modifier and write a fully functional prototype for it and disable the feature for other modifiers.

I'm closing this PR for now, but feel free to open a new one, if you decide to continue working on this feature.

**Comment by shiraji** [comment]
I don't mind closing this PR, however, the word "It is modifier" is place holder not actual one. 
As @semoro and I discussed in slack, the doc will come from other resources and I was told to wait until you guys provide the documentation.

**Comment by goodwinnk** [comment]
I think implementing the feature for one or some subset of modifiers will make the change immediately valuable and independent from any further work. Reading documentation for some external source is appealing idea but may postpone the actual implementation significantly (actually already did :( ). 

P.S. I didn't expect such a fast answer after a year this PR is inactive. If you want to continue your work, I'm ready to reopen it.

**Comment by goodwinnk** [comment]
I like an idea to start from `lateinit` or `tailrec`, and leave other keywords for future contributions. 

> I believe what I will need to do is adding cases to this line https://github.com/JetBrains/kotlin/pull/1435/files#diff-d9206ebe78be3db8c8e3f9ac8aaac3c0R230
Yes, it would be enough for now.

Also please can you investigate removing `defined in` part, as it a bit misleading for keywords.

**Comment by shiraji** [comment]
> leave other keywords for future contributions

That's good idea.

> defined in

OK. I will do that.

**Comment by shiraji** [comment]
Hi, @goodwinnk 

Now, I remember what I did. 
Do you really want to remove `defined in` https://github.com/JetBrains/kotlin/pull/1435/files#diff-63ffa34b0bc6b249f69826b481717bd9R5 ?
This is the test case for quick doc of the variable name `lateinit`, not keyword.

**Comment by shiraji** [comment]
Updated it!

**Comment by shiraji** [comment]
@goodwinnk could you review this PR?

**Comment by goodwinnk** [comment]
Nice! I'm going to accept it after the remote run. The only thing I noticed are very long string literals, but I'm going to refactor them in this commit https://github.com/JetBrains/kotlin/commit/685659164b8138b9046f9071927fa09e327b12a9.

**Comment by shiraji** [comment]
Nice. Thanks for the refactoring!

**Comment by goodwinnk** [comment]
Done, your commit is in master (https://github.com/JetBrains/kotlin/commit/d3895c519ce6502380ad9e5da0fe1a20df031cfd). 

Thank you for the contribution!

I forgot to say that it's a profound idea to use links to articles with more information.

**Comment by shiraji** [comment]
Thanks! 

Could you create an issue that adds other keywords for future contributors? Like what you guys are doing for adding documentation of standard libraries. https://youtrack.jetbrains.com/issue/KT-20357 ?

**Comment by goodwinnk** [comment]
I have updated state in https://youtrack.jetbrains.com/issue/KT-9934. Technically it's still open.

**Pull request closed without merging**
