### PR TITLE
Fix typos in docs

### PR DESCRIPTION
**Pull request by Inego**

### CODE REVIEW

**Comment by ilya-g** [comment]
@Inego please rebase your branch on master to eliminate the merge commit.

**Comment by Inego** [comment]
@ilya-g I think I'd better make just two commits, please wait....

**Comment by Inego** [comment]
Done.

**Comment by ilya-g** [comment]
There shouldn't be commit by @elizarov in this branch. If the changes there were intentional, please squash them with your commit.

**Comment by Inego** [comment]
@elizarov Since my edits were based on yours (https://github.com/JetBrains/kotlin/commit/e2427cbb17b11ce851fdaec70917cf653851d4f9), I cherry picked your commit in my branch, and fixed the conflict. Can I just squash those commits as @ilya-g suggests?

**Comment by ilya-g** [comment]
That commit is already in master, so if you rebased your branch on top of it, all remaining changes here are yours and you can squash them as you want.

**Comment by Inego** [comment]
Now it must be OK.

**Comment by elizarov** [comment]
Thanks!

**Comment by ilya-g** [comment]
A follow-up commit 5f2762ed20ece598ab0acf21458bc5c4adf143c6 was required to keep expect/actual docs in sync. Also the corresponding PR in Kotlin/Native: https://github.com/JetBrains/kotlin-native/pull/2937

**Comment by Inego** [comment]
Does this mean I had to run the code generator before pushing here?

BTW, there's a problem with documentation concerning code generation:

image

The "README" link leads to the 404 page now.

**Comment by ilya-g** [comment]
No, this is a manual step. Thanks for spotting dead relative link, fixed.

**Pull request merged**
