### PR TITLE
Fix the link of ReadMe.md for Kotlin Standard Library for JavaScript

### PR DESCRIPTION
**Pull request by lamtrinhdev**
Fix the link of ReadMe.md for Kotlin Standard Library for JavaScript

### CODE REVIEW

**Comment by lamtrinhdev** [comment]
Dear @bashor , @ilya-g ,

Could you please help me to review it?

Thanks,
Lam

**Comment by lamtrinhdev** [comment]
Dear @skuzmich ,

Sorry tagging you because I see you are the last the modify the link at `js/ReadMe.md`. I have a minor update. Could you help me to review this PR?

Thanks,
Lam

**Review by broadwaylamb — APPROVED** [review]
Thank you!

**Comment by lamtrinhdev** [comment]
Dear @broadwaylamb ,

Thank you for your review. I do not have permission to merge. Could you help me to merge it?

Thanks,
Lam

**Pull request merged**
