### PR TITLE
KT-21223 Inspection: incomplete destructuring

### PR DESCRIPTION
**Pull request by kvirolainen**
https://youtrack.jetbrains.com/issue/KT-21223

### CODE REVIEW

**Comment by vladimirdolzhenko** [comment]
Sorry for the long delay.

Could you please update your PR according to the latest code base changes and add i18n support ?

**Comment by vladimirdolzhenko** [comment]
If you don't mind I could make appropriate amendments on behalf of you and merge it after that.

**Comment by kvirolainen** [comment]
@vladimirdolzhenko, it would be great, thank you

**Comment by vladimirdolzhenko** [comment]
Merged as https://github.com/JetBrains/kotlin/commit/5b1d019bb0507a9bc9324f63f7db747c786b1c2d.

Thank you for the contribution.

**Pull request closed without merging**
