### PR TITLE
KT-26047 Refactor -> Rename: Overridden method renaming in generic class doesn't rename base method

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-26047

### CODE REVIEW

**Comment by t-kameyama** [comment]
I think it was fixed in https://github.com/JetBrains/kotlin/commit/0c4134470dfcd09805499b1a0834ea1410c6501b, so added tests.

**Comment by t-kameyama** [comment]
I think it was fixed in https://github.com/JetBrains/kotlin/commit/0c4134470dfcd09805499b1a0834ea1410c6501b, so this pull request is tests only.

**Comment by igoriakovlev** [comment]
We could't accept this because there are some conflicts exists.
Please resolve it.

**Comment by igoriakovlev** [comment]
Thank you for your work.

**Pull request merged**
