### PR TITLE
KT-45777: Refactor RuntimeModuleData to support classpath snapshotting

### PR DESCRIPTION
**Pull request by hungvietnguyen**

### CODE REVIEW

**Comment by hungvietnguyen** [comment]
Hi, I just cleaned up the PR a bit to make it easier to review.

Also, I added a prototype at the following link to show how this PR will be used. The goal is to create `JavaClassDescriptor`s for .class files, as shown below. (`JavaClassDescriptor`s will allow us to extract ABI info from class files using the existing `IncrementalJvmCache` class to improve incremental Kotlin compilation -- https://youtrack.jetbrains.com/issue/KT-45777.)

https://github.com/google/kotlin/commit/71b3d9cc38c5d133eb53c65e5db2e58a8e3fcfb2#diff-d7427ade67ef6b09b22db8af0cf1850d146faa1efafb3448fb98a82b88793548R38:
```
    fun create(relativePathToClass: String, classContents: ByteArray): JavaClassDescriptor {
        val binaryJavaClass: BinaryJavaClass = createBinaryJavaClass(relativePathToClass, classContents)

        val moduleDescriptor = DeserializationComponentsForJava.createModuleData(
            NoOpKotlinClassFinder,
            BuiltInsKotlinClassFinder(),
            BinaryJavaClassFinder(binaryJavaClass),
            "generic-module-name",
            CustomErrorReporter,
            NoSourceJavaSourceElementFactory
        ).deserializationComponentsForJava.components.moduleDescriptor

        return moduleDescriptor.findClassAcrossModuleDependencies(binaryJavaClass.classId()) as JavaClassDescriptor
    }
```

Also cc @udalov and @gavra0 for feedback as we discussed this approach before on Slack.

Thanks!

**Comment by gavra0** [comment]
This looks ok to me, but I'd like someone from the compiler team to take a look.

**Review by udalov — APPROVED** [review]

**Comment by hungvietnguyen** [comment]
Thank you for the reviews! This PR has passed TeamCity tests as well, so looking forward to it getting merged. :)

**Comment by hungvietnguyen** [comment]
This PR has been merged: https://github.com/JetBrains/kotlin/commit/170184dce4bb08f03a873fcfc8535d1fc1735293, https://github.com/JetBrains/kotlin/commit/eb94167ff2da0f4205612d0eb98cba9f1bde71bd

**Pull request closed without merging**
