### PR TITLE
#KT-3380 Fixed

### PR DESCRIPTION
**Pull request by Tip-Sy**
Function addElement overloaded with an Element as parameter

### CODE REVIEW

**Comment by cy6erGn0m** [comment]
I see no big difference against appendChild except return type. Unfortunately it is not obvious for user which element will be returned: parent or child as it looks like a builder function

See example:
{code}
body.addElement(div1).addElement(div2).addElement(div3)
{code}

Is it obvious for user which of the following trees will be built:

```
body
    div1
    div2
    div3
```

or 

```
body
    div1
        div2
            div3
```

This is why I believe it is error-prone approach

**Comment by alextkachman** [comment]
Traditionally (???) convention is append returns original (parent) element and there is also appendTo

**Comment by Tip-Sy** [comment]
@cy6erGn0m I agree with you, the behaviour of this function is really confusing.

@alextkachman I don't think returning the parent is a convention for append functions, see [this example](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild)

Personnaly, I would see it like this:

```
body.appendTo(div1).appendTo(div2).appendTo(div3)

body
    div1
        div2
            div3
```

VS.

```
body.addElement(div1).addElement(div2).addElement(div3)

body
    div1
    div2
    div3
```

But according to the behaviour of `Element.addElement(name: String...)`, I thought I had to return the child element as well.

**Comment by cy6erGn0m** [comment]
@Tip-Sy body.appendTo(div1) should add body to div according to the name. addElement still doesn't hint you what is the result. 

I believe you don't need this actually. Look to Kara or Yested frameworks.

**Comment by Tip-Sy** [comment]
Ah I realize that I mistook append*To* for append*Child* in my comment (I've corrected it). To clarify things up: appendTo returns the parent element, whereas appendChild returns the child.

You're right, no need to add this function actually.

**Pull request closed without merging**
