### PR TITLE
add samples for CharJVM.kt

### PR DESCRIPTION
**Pull request by KirillMakarov**
I choose to use `assertPrints` instead of `assertTrue`, because 
`println('a'.isDigit()) // false`
 is more readable than 
`println("'a'.toDigit() is ${'a'.isDigit()}") // false`

### CODE REVIEW

**Comment by ilya-g** [comment]
> I choose to use assertPrints instead of assertTrue

It might be more readable when a sample contains just one assertion, but when there are several of them, you'd get the following output if you actually run sample:
```
true
true
false
false
```

So it would be hard to correlate which expression yield which result.

**Comment by KirillMakarov** [comment]
I think blank line between true and false statements in output will help, because samples are grouped by true/false. How we can add blank line in samples? Maybe we should add `assertPrints("","")` between true and false statements? What do you think?

**Comment by KirillMakarov** [comment]
It is easy to fix, but we should choose the best option

**Comment by ilya-g** [comment]
Another option to get more compact but not less expressive samples for `is*` extensions is the following:
```
val chars = listOf('a', 'β', '+', '1')
val (letters, notLetters) = chars.partition { it.isLetter() }

assertPrints(letters, "[a, β]")
assertPrints(notLetters, "[+, 1]")
```

WDYT?

**Comment by KirillMakarov** [comment]
Ok, great idea, I will change

**Comment by ilya-g** [comment]
We have implemented this idea in PR #1738

**Pull request closed without merging**
