### PR TITLE
Rr/compile service 8

### PR DESCRIPTION
**Pull request by ligee**
New daemon control
Cleanup after compilation (fixes e.g. jar locking issues)
Fixing log-based daemon tests on windows

### CODE REVIEW

**Comment by ligee** [comment]
Merged into beta 3

**Comment by bashor** [comment]
how about master?

**Comment by ligee** [comment]
It was merged into master before branching beta 3. With the message I meant that it is in the mainline since beta 3.

**Comment by bashor** [comment]
ok

**Pull request closed without merging**
