### PR TITLE
KT-37744 "Convert lambda to reference" inspection quick fix create incompilable code when type is inferred from lambda parameter

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-37744

### CODE REVIEW

**Comment by yanex** [comment]
Failing case 1:

```
fun overloadFun(p: Int) {}
fun overloadFun(p: String) {}

fun <T> ambiguityFun(vararg fn: (T) -> Unit) {}

fun overloadContext() {
    ambiguityFun({ <caret> x: String -> overloadFun(x) }, ::overloadFun)
}
```

**Comment by yanex** [comment]
I would recommend moving out the type parameter check with early returns to avoid clunky constructs such as `?.let {}`, `?.any { it.type.isTypeParameter() } == true)` and others.

**Comment by t-kameyama** [comment]
PTAL

**Comment by yanex** [comment]
Review: OK.

**Comment by yanex** [comment]
Merged into `master`. Thanks!

**Pull request closed without merging**
