### PR TITLE
KT-22665 "Create object" quick fix produce wrong code for enum

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-22665

### CODE REVIEW

**Comment by klunnii** [comment]
1. `Create object` quick fix is no longer available. Please, consider the context:
``` kotlin
enum class SampleEnum {}

fun usage(sample: SampleEnum) {
    SampleEnum.RED // suggesting object creation is still correct here
}
```
2. Provided test unfortunatly fails. Would you please rebase your commit on recent master and check it?

**Comment by t-kameyama** [comment]
Fixed in cd961a1

**Comment by t-kameyama** [comment]
Fixed in 86c7c58

**Comment by klunnii** [comment]
Merged. Thank you!

**Pull request merged**
