### PR TITLE
FIR: join KotlinDeserializedJvmSymbolsProvider and JavaSymbolProvider

### PR DESCRIPTION
**Pull request by pyos**
I'm told that removal of redundant cache layers in ba1fc81b96618f32e3e14cb5441a40acdc04afb5 hurt performance due to unnecessary repeated file reads, so this is an attempt to fix that: when a Java class is loaded through a KotlinDeserializedJvmSymbolsProvider, it goes into KotlinDeserializedJvmSymbolsProvider's cache, and JavaSymbolProvider no longer has a cache of its own. This keeps the "at most one cache, and it must be postprocessing-aware" property required for not breaking IDE mode while reverting to the old "read the class file once" behavior.

cc @dzharkov

### CODE REVIEW

**Comment by dzharkov** [comment]
Thank you for your contribution! Merged manually.

**Comment by jsjeon** [comment]
This broke `kt-212-master` branch in `intellij-community` repo, in particular FIR UAST. cc @darthorimar 

Some of later commits seem mechanical refactoring, but the culprit is the very first one. I can confirm reverting these 6 restored green status of that branch. The failure looks not trivial, e.g.,
```kt
package test.pkg

class Context {
    inline fun <reified T> ownSystemService1() = getSystemService(T::class.java)
    inline fun ownSystemService2() = getSystemService(String::class.java)
}


inline fun <reified T> Context.systemService1() = getSystemService(T::class.java)
inline fun Context.systemService2() = getSystemService(String::class.java
```
fails with:
```
java.lang.RuntimeException: While resolving call getSystemService#(<getClass>(R|T|).R?C|kotlin/jvm/java|)

Caused by: java.lang.IllegalStateException: Unexpected FirClassLikeSymbol null for class org.jetbrains.kotlin.fir.symbols.impl.ConeClassLikeLookupTagImpl, with classId java/lang/Class
	at org.jetbrains.kotlin.fir.types.ConeTypeContext$DefaultImpls.getParameter(ConeTypeContext.kt:241)
	at org.jetbrains.kotlin.fir.types.ConeInferenceContext$DefaultImpls.getParameter(ConeInferenceContext.kt:32)
	at org.jetbrains.kotlin.fir.resolve.inference.InferenceComponents$ctx$1.getParameter(InferenceComponents.kt:16)
	at org.jetbrains.kotlin.resolve.calls.inference.model.NewConstraintSystemImpl.getParameter(NewConstraintSystemImpl.kt)
	at org.jetbrains.kotlin.fir.resolve.inference.CalculatorForNestedCall.collectRequiredDirectionsForVariables(CompletionModeCalculator.kt:133)
	at org.jetbrains.kotlin.fir.resolve.inference.CalculatorForNestedCall.computeDirections(CompletionModeCalculator.kt:84)
	at org.jetbrains.kotlin.fir.resolve.inference.CalculatorForNestedCall.computeCompletionMode(CompletionModeCalculator.kt:67)
	at org.jetbrains.kotlin.fir.resolve.inference.CompletionModeCalculatorKt.computeCompletionMode(CompletionModeCalculator.kt:39)
	at org.jetbrains.kotlin.fir.resolve.inference.FirCallCompleter.completeCall(FirCallCompleter.kt:133)
	at org.jetbrains.kotlin.fir.resolve.inference.FirCallCompleter.completeCall(FirCallCompleter.kt:70)
	at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirExpressionsResolveTransformer.transformQualifiedAccessExpression(FirExpressionsResolveTransformer.kt:147)
	at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirExpressionsResolveTransformer.transformQualifiedAccessExpression(FirExpressionsResolveTransformer.kt:81)
	at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirExpressionsResolveTransformer.transformPropertyAccessExpression(FirExpressionsResolveTransformer.kt:170)
	at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirExpressionsResolveTransformer.transformPropertyAccessExpression(FirExpressionsResolveTransformer.kt:53)
	at org.jetbrains.kotlin.fir.expressions.FirPropertyAccessExpression.transform(FirPropertyAccessExpression.kt:37)
	at org.jetbrains.kotlin.fir.expressions.impl.FirArgumentListImpl.transformArguments(FirArgumentListImpl.kt:41)
	at org.jetbrains.kotlin.fir.expressions.impl.FirArgumentListImpl.transformArguments(FirArgumentListImpl.kt:17)
	at org.jetbrains.kotlin.fir.FirCallResolver.resolveCallAndSelectCandidate(FirCallResolver.kt:78)
	at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirExpressionsResolveTransformer.transformFunctionCall(FirExpressionsResolveTransformer.kt:369)
```

**Comment by pyos** [comment]
What's the name of the file that contains the function?

**Comment by pyos** [comment]
This fixes the problem: https://github.com/JetBrains/kotlin/pull/4576

**Pull request closed without merging**
