### PR TITLE
Build: Upgrade gradle to 6.6.1

### PR DESCRIPTION
**Pull request by KotlinIsland**
> [We recommend that you use Gradle 6.6.1 over the initial release of Gradle 6.6](https://github.com/gradle/gradle/releases/tag/v6.6.1)

### CODE REVIEW

**Comment by vladimirdolzhenko** [comment]
I guess it is applicable to https://github.com/JetBrains/kotlin/blob/master/idea/testData/perfTest/native/_common/gradle/wrapper/gradle-wrapper.properties as well

**Review by ddolovov — APPROVED** [review]

**Comment by 4u7** [comment]
@ddolovov @vladimirdolzhenko We need to update our internal repository as well

**Comment by 4u7** [comment]
And also kotlin-native which is usually done by @ilmat192 
https://github.com/JetBrains/kotlin-native/blob/master/gradle/wrapper/gradle-wrapper.properties

**Comment by ilmat192** [comment]
Done for Kotlin/Native: https://github.com/JetBrains/kotlin-native/commit/c302ae895ee6e213f73f389887754d7578fdb302

**Pull request closed without merging**
