### PR TITLE
JVM IR: Support -Xno-call-assertions

### PR DESCRIPTION
**Pull request by sfs**
CC @kandersen

### CODE REVIEW

**Comment by dnpetrov** [comment]
@sfs Please, take a look at `JvmArgumentNullabilityAssertionsLowering`.
It was supposed to remove assertions that are not required (including those that are not required because of call assertions disabled).
If it doesn't remove some particular assertions even with the corresponding flag enabled, it should most likely be fixed there.

**Comment by sfs** [comment]
@dnpetrov Thanks for the pointer, I completely missed this lowering. Seems like the rules for null checks are more complicated than just checking a flag. I'll have a look at the lowering!

**Comment by sfs** [comment]
@dnpetrov I've had a look at `JvmArgumentNullabilityAssertionsLowering`. The problem was that it did not remove all `NOT_NULL` assertions even if the `-Xno-call-assertions` flag was set.

I've refactored the lowering to ensure that we visit all type casts in the IR. The way I understand it, there has to be some special handling for dispatch and extension receiver parameters as well as calls to type erased bridges. Based on the code this special handling only extends to type casts which are immediately in the argument position.

I've also removed the descriptor usage from the code, since there is an equivalent facility for recognizing type adjusted special bridges in the IR.

**Comment by dnpetrov** [comment]
@sfs Am I missing something, or you don't process results of `IrGetField`?

**Comment by sfs** [comment]
@dnpetrov You're right, I missed the special case for receiver parameters on `IrGetField` and `IrSetField`! I've added these and also changed `testNullabilityAssertionOnDispatchReceiver` to properly check for this optimization. I've also rebased on master.

**Comment by dnpetrov** [comment]
Ok, I'll run tests and merge manually.

**Comment by dnpetrov** [comment]
Merged manually (cf3e4608f3b605711ebe88c73aa78d0604c2734b).

**Pull request closed without merging**
