### PR TITLE
build: add kotlin-compiler-embeddable to BOM

### PR DESCRIPTION
**Pull request by gastaldi**
Added missing library in BOM

### CODE REVIEW

**Comment by ilya-g** [comment]
Could you elaborate on why do you need this dependency listed here?

**Comment by gastaldi** [comment]
This library is used in a project (Quarkus). The BOM is missing other dependencies too

**Comment by ilya-g** [comment]
> The BOM is missing other dependencies too

What other dependencies do you mean?

**Comment by gastaldi** [comment]
I don't have a complete list but I miss `org.jetbrains.kotlin:kotlin-maven-allopen` too, which is used as a dependency to the Maven plugin :smile:

**Comment by ilya-g** [comment]
AFAIK dependency versions listed in the `dependencyManagement` section do not affect neither the plugin versions nor dependencies of plugins.

**Comment by gastaldi** [comment]
Cool, then I think this is the only one missing

**Pull request merged**
