### PR TITLE
KT-47553 : Sequence.plus implementation optimization

### PR DESCRIPTION
**Pull request by ahmed3elshaer**
Rewriting Sequence<T>.plus functions with sequence builders to improve the performance
Based on benchmarks in [this comment](https://youtrack.jetbrains.com/issue/KT-47553/Sequence.plus-implementation-optimization#focus=Comments-27-6665321.0-0)

Fixed [KT-47553](https://youtrack.jetbrains.com/issue/KT-47553/Sequence.plus-implementation-optimization)

### CODE REVIEW

**Comment by fzhinkin** [comment]
Hey! As soon as a fix for [KT-58588](https://youtrack.jetbrains.com/issue/KT-58588/) is integrated, the builder-based approach will no longer be superior to the existing flatten-based implementation.

I'm suggesting waiting for [KT-58588](https://youtrack.jetbrains.com/issue/KT-58588/), reevaluating the performance and then deciding whether the fix is still needed.

Figures I got so far (JDK17, MacOS-aarch64, Kotlin 1.9.10) are:
```
Benchmark                                Mode  Cnt         Score        Error  Units
SequenceBenchmark.builderPlusCount      thrpt   10     11210.375 ±     22.996  ops/s
SequenceBenchmark.builderPlusFirst      thrpt   10  72028030.192 ± 756328.976  ops/s
SequenceBenchmark.builderPlusLast       thrpt   10     11562.847 ±    180.677  ops/s
SequenceBenchmark.optStandardPlusCount  thrpt   10     12872.071 ±    161.030  ops/s
SequenceBenchmark.optStandardPlusFirst  thrpt   10  98632309.847 ± 489632.414  ops/s
SequenceBenchmark.optStandardPlusLast   thrpt   10     14448.294 ±    269.413  ops/s
```

Where optStandard* corresponds to flatten-based implementation with the `FlatteningSequence` being taken from [KT-58588](https://youtrack.jetbrains.com/issue/KT-58588/).

**Comment by ahmed3elshaer** [comment]
Hey @fzhinkin thanks for the heads up, i will wait until KT-58588 fix is merged and then i will do another benchmarking and report to you.

Out of curiosity in the benchmark results, the less the number the better the performance right?

**Comment by ahmed3elshaer** [comment]
Hey @fzhinkin thanks for the heads up, i will wait until KT-58588 fix is merged and then i will do another benchmarking and report to you.

Out of curiosity in the benchmark results, the less the number the better the performance right?

**Comment by fzhinkin** [comment]
@ahmed3elshaer sorry for the late reply. I've executed benchmarks in the throughput mode, so larger numbers correspond to a better performance (as more operations per time unit could be done).

**Comment by fzhinkin** [comment]
@ahmed3elshaer, optimizations from KT-58588 landed last week, you can try it by using recent dev versions, like [2.0.0-dev-4660](https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev/org/jetbrains/kotlin/kotlin-stdlib/2.0.0-dev-4660/) (please note that it requires [dev repo](https://mvnrepository.com/repos/space-kotlin-dev)).

I also recommend verifying the performance using JDK 21, as with the previous LTS release (17) results may be unstable from run to run depending on how functions were inlined (I experienced that issue when I tried to verify the performance before writing this message: from run to run "library" and "standard" were either slower than "builder", or faster; with JDK 21 "library" and "standard" were always faster).

**Comment by fzhinkin** [comment]
I cloned the repository with original benchmarks and updated versions of dependencies, tuned benchmark params (added forks, reduced warmup iterations) and also split an action running benchmarks into two - one running them w/ JDK17 and another one using JDK21:
https://github.com/fzhinkin/sequence-test

Here is the run: https://github.com/fzhinkin/sequence-test/actions/runs/6573912699

And here are results extracted from it:

- results with JDK17 (the greater is the score, the faster is the implementation):
```
Benchmark                             Mode  Cnt         Score        Error  Units
SequenceBenchmark.builderPlusCount   thrpt   50      4240.231 ±     34.718  ops/s
SequenceBenchmark.builderPlusFirst   thrpt   50  21286917.654 ± 481400.516  ops/s
SequenceBenchmark.builderPlusLast    thrpt   50      4190.961 ±     56.411  ops/s
SequenceBenchmark.libraryPlusCount   thrpt   50      5488.381 ±     23.354  ops/s
SequenceBenchmark.libraryPlusFirst   thrpt   50  28418851.128 ± 151395.019  ops/s
SequenceBenchmark.libraryPlusLast    thrpt   50      4628.054 ±    453.158  ops/s
SequenceBenchmark.standardPlusCount  thrpt   50      5493.496 ±     24.774  ops/s
SequenceBenchmark.standardPlusFirst  thrpt   50  30403898.871 ±  87304.815  ops/s
SequenceBenchmark.standardPlusLast   thrpt   50      5396.635 ±     32.119  ops/s
```

- results with JDK21 (the greater is the score, the faster is the implementation):
```
Benchmark                             Mode  Cnt          Score        Error  Units
SequenceBenchmark.builderPlusCount   thrpt   50       5930.512 ±     52.753  ops/s
SequenceBenchmark.builderPlusFirst   thrpt   50   32317225.335 ± 140974.236  ops/s
SequenceBenchmark.builderPlusLast    thrpt   50       6106.265 ±     36.033  ops/s
SequenceBenchmark.libraryPlusCount   thrpt   50       7684.469 ±     26.561  ops/s
SequenceBenchmark.libraryPlusFirst   thrpt   50  165316260.195 ± 570854.638  ops/s
SequenceBenchmark.libraryPlusLast    thrpt   50       9046.098 ±     61.817  ops/s
SequenceBenchmark.standardPlusCount  thrpt   50       7853.750 ±     81.724  ops/s
SequenceBenchmark.standardPlusFirst  thrpt   50  141832535.893 ± 399883.073  ops/s
SequenceBenchmark.standardPlusLast   thrpt   50       9035.473 ±     56.341  ops/s
```

Builder-based implementation shows worse results compared to the default implementation from 2.0's stdlib.
Thus, I'm closing this PR. Feel free to reopen it or open another one if there is another way to improve plus's performance.

**Pull request closed without merging**
