### PR TITLE
[IR] Delete IrMessageLogger interface

### PR DESCRIPTION
**Pull request by scaventz**
There are a few tests failing, but they don't seem to be related to our changes:
- AntTaskTestGenerated
- FriendPathsTest
- LauncherReplTest
- LauncherScriptTest  
  

^KT-68174 fixed

### CODE REVIEW

**Review by broadwaylamb — CHANGES_REQUESTED** [review]
Thank you for your contribution!

There are still some compilation errors which need to be fixed. You can find them [here](https://teamcity.jetbrains.com/buildConfiguration/Kotlin_KotlinPublic_AggregateBranch/4664825?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true) (just log in as guest).

**Review by broadwaylamb — COMMENTED** [review]
The build is now [green](https://teamcity.jetbrains.com/buildConfiguration/Kotlin_KotlinPublic_AggregateBranch/4667817).

Thank you! A few more suggestions and then let's wait for reviews from other subsystem owners.

**Comment by broadwaylamb** [comment]
Also, please rebase onto the fresh master, there are conflicts.

**Comment by scaventz** [comment]
@broadwaylamb Thank you! Updated.

**Review by broadwaylamb — CHANGES_REQUESTED** [review]
Please fix the compilation error here:
https://github.com/scaventz/kotlin/blob/48ada3ea2f1231edbcfbaa6b7a5f19e6a46b6608/js/js.tests/test/org/jetbrains/kotlin/js/test/converters/JsIrDeserializerFacade.kt#L67

**Comment by scaventz** [comment]
Updated, after another around of `./gradlew :compiler:test` and `./gradlew dist`.

**Review by broadwaylamb — CHANGES_REQUESTED** [review]
It seems like it stopped compiling again due to changes in master:

```
e: file://<...>/kotlin/wasm/wasm.tests/test/org/jetbrains/kotlin/wasm/test/converters/WasmDeserializerFacade.kt:94:48 Unresolved reference 'irMessageLogger'.
```

**Review by broadwaylamb — APPROVED** [review]

**Comment by broadwaylamb** [comment]
Landed in https://github.com/JetBrains/kotlin/commit/a5530c713528c6ca2e3a4f838d04ee216ed14483.

Thanks again!

**Review by armandRobled — COMMENTED** [review]
GithubPatche-1_armandorobleee

**Comment by scaventz** [comment]
Thank you for sparing time on this!

**Pull request closed without merging**
