### PR TITLE
KT-22714 Avoid to generate unecessary checkcast

### PR DESCRIPTION
**Pull request by mikaelpeltier**
- StackValue already avoid to generate checkcast from a type or an
array to java.lang.Object. Add a new case to avoid to generate a
checkcast from an array to an array of java.lang.Object when arrays
have the same dimensions.

Fix of https://youtrack.jetbrains.com/issue/KT-22714

### CODE REVIEW

**Comment by max-kammerer** [comment]
@mikaelpeltier Why do you need 'JVM_TARGET: 1.8' in tests? Seems both tests could be moved to  codegen/box and codegen/bytecodeText

**Comment by mikaelpeltier** [comment]
It is perhaps not mandatory, following a discussion with @dnpetrov, I used JVM_TARGET 1.8 to check that my change does not break something with the stack frame generation. Nevertheless, if you estimate that it is not needed, I can move my test into `codegen/box` and `codegen/bytecodeText`. 
Tell me what you prefer.

**Comment by max-kammerer** [comment]
Yes, smth could be broken, but:
1. I didn't see anything in your test that could do it (and i can't  come up with smth)
2. we also run common tests with switched default jvm target to 1.8 (see :compiler:codegenTarget8Jvm8Test)
so, pls move tests

**Comment by mikaelpeltier** [comment]
Tests moved and PR tested by:
./gradlew dist
./gradlew jvmCompilerTest

**Comment by max-kammerer** [comment]
Thanks! Merged manually

**Pull request closed without merging**
