### PR TITLE
Solves issue KT-43615.

### PR DESCRIPTION
**Pull request by stephanenicolas**
It seems to work well locally.

### CODE REVIEW

**Comment by max-kammerer** [comment]
Is it possible to add any tests?

**Comment by max-kammerer** [comment]
cc @gavra0

**Comment by gavra0** [comment]
I'm able to reproduce now, and I'm looking into it. Most likely the root cause is something else.

**Comment by max-kammerer** [comment]
@gavra0 Thank you for investigation!

**Pull request closed without merging**
