### PR TITLE
FIR/UAST: commonize reference expressions

### PR DESCRIPTION
**Pull request by jsjeon**
This PR is about commonizing reference expressions:

* `.`-qualified reference expression: This trivial change, though, caused an assertion failure in `AbstractTypeMapper`, which is used to make sure an underlying `KtType` is able to be mapped to JVM type. It can't handle a type with a flexible type as a type argument, e.g., `Stream<String..String?>`, whereas FE1.0 counterpart can. It turns out that it's just an unnecessarily strong restriction in `AbstractTypeMapper`. 2nd commit relaxed that.

* simple reference expression: 3rd commit partially commonizes it. The missing part is destructuring declaration, which needs a temporary variable. (There are many more that need temp var-based desugaring.)

* double colon expressions, such as class literal (`Foo::class`) and callable reference (`Foo::bar`): before commonizing that, 4th commit commonizes/utilizes multi resolve APIs/utils.

* safe qualified expression (e.g., `x?.foo`)

* `this` and `super` references (a.k.a. expression with labels): It seems like there are no tests for _labeled_ `this` and `super`, so added. Alas, not fully tested yet in FIR UAST side due to the lack of other expression conversions.

### CODE REVIEW

**Review by darthorimar — APPROVED** [review]

**Review by xiexed — APPROVED** [review]

**Comment by jsjeon** [comment]
Hi @demiurg906, could you take a look at the 2nd commit (relaxing simple type requirement in `AbstractTypeMapper`)? Thanks!

**Comment by jsjeon** [comment]
This is temporarily(?) rebased on top of https://github.com/JetBrains/kotlin/pull/4451, and test data are updated accordingly. Once that PR is merged, I'll update this one again.

**Comment by demiurg906** [comment]
@jsjeon commit about type mapper is OK

**Comment by darthorimar** [comment]
Merged manually, thank you!

**Pull request closed without merging**
