### PR TITLE
JVM IR: keep dispatch receiver in $delegate methods

### PR DESCRIPTION
**Pull request by udalov**
Otherwise we generate incorrect IR where a static function accesses an
instance field of the containing class.

 #KT-48350 Fixed

### CODE REVIEW

**Comment by udalov** [comment]
@pyos Please take a look

**Comment by pyos** [comment]
The intention behind moving the receiver was to make the method unoverridable, but that doesn't seem to actually work anyway:

```
import kotlin.reflect.*
import kotlin.reflect.jvm.isAccessible

val a = 1
val b = 2

open class C {
    open val x by run { ::a }
    open val y by ::b

    val xc = ::x.apply { isAccessible = true }.getDelegate()
    val yc = ::y.apply { isAccessible = true }.getDelegate()
}

class D : C() {
    override val x by run { ::b }
    override val y by ::b

    val xd = ::x.apply { isAccessible = true }.getDelegate()
    val yd = ::y.apply { isAccessible = true }.getDelegate()
}

fun main() {
    println(D().run { "xc = $xc\nyc = $yc\nxd = $xd\nyd = $yd" })
}
```
```
xc = val a: kotlin.Int
yc = val b: kotlin.Int
xd = val b: kotlin.Int
yd = val b: kotlin.Int
```
with and without this PR. Though maybe the behavor of *unoptimized* delegates is weird?

On a related note, there's an oversight in kotlin-reflect - `isAccessible` does not change visibility of `getX$delegate`.

**Comment by dnpetrov** [comment]
@udalov please, add bytecodeListing test for the case described above (https://github.com/JetBrains/kotlin/pull/4553#issuecomment-903962793).

**Comment by udalov** [comment]
@pyos @dnpetrov So what do you think?

**Review by pyos — APPROVED** [review]

**Review by dnpetrov — APPROVED** [review]
LGTM.

**Comment by udalov** [comment]
Thanks!

**Pull request merged**
