### PR TITLE
FIR: load Java annotation defaults after binding the class symbol

### PR DESCRIPTION
**Pull request by pyos**

### CODE REVIEW

**Comment by mglukhikh** [comment]
This commit breaks build of `idea-maven` module from Kotlin project. I'll try to investigate the reason when I have time.

```
java.lang.IllegalStateException: Expected FirResolvedTypeRef with ConeKotlinType but was FirJavaTypeRef org.jetbrains.idea.maven.dom.references.MavenSourceDirectoryConverter
	at org.jetbrains.kotlin.fir.backend.Fir2IrVisitor.visitGetClassCall(Fir2IrVisitor.kt:995)
	at org.jetbrains.kotlin.fir.backend.Fir2IrVisitor.visitGetClassCall(Fir2IrVisitor.kt:48)
	at org.jetbrains.kotlin.fir.expressions.FirGetClassCall.accept(FirGetClassCall.kt:24)
	at org.jetbrains.kotlin.fir.backend.Fir2IrVisitor.convertToIrExpression$fir2ir(Fir2IrVisitor.kt:467)
	at org.jetbrains.kotlin.fir.backend.generators.CallAndReferenceGenerator.convertArgument(CallAndReferenceGenerator.kt:578)
	at org.jetbrains.kotlin.fir.backend.generators.CallAndReferenceGenerator.applyArgumentsWithReorderingIfNeeded(CallAndReferenceGenerator.kt:531)
	at org.jetbrains.kotlin.fir.backend.generators.CallAndReferenceGenerator.applyCallArguments$fir2ir(CallAndReferenceGenerator.kt:472)
	at org.jetbrains.kotlin.fir.backend.generators.CallAndReferenceGenerator.convertToIrConstructorCall(CallAndReferenceGenerator.kt:393)
	at org.jetbrains.kotlin.fir.lazy.AbstractFir2IrLazyDeclaration$createLazyAnnotations$1.invoke(AbstractFir2IrLazyDeclaration.kt:43)
	at org.jetbrains.kotlin.fir.lazy.AbstractFir2IrLazyDeclaration$createLazyAnnotations$1.invoke(AbstractFir2IrLazyDeclaration.kt:41)
	at org.jetbrains.kotlin.ir.declarations.lazy.SynchronizedLazyVar.getValue(lazyUtil.kt:28)
	at org.jetbrains.kotlin.ir.declarations.lazy.SynchronizedLazyVar.getValue(lazyUtil.kt:39)
	at org.jetbrains.kotlin.fir.lazy.Fir2IrLazySimpleFunction.getAnnotations(Fir2IrLazySimpleFunction.kt:36)
	at org.jetbrains.kotlin.ir.interpreter.UtilsKt.hasAnnotation(Utils.kt:102)
	at org.jetbrains.kotlin.ir.interpreter.IrCompileTimeChecker.isMarkedWith(IrCompileTimeChecker.kt:55)
	at org.jetbrains.kotlin.ir.interpreter.IrCompileTimeChecker.isContract(IrCompileTimeChecker.kt:33)
	at org.jetbrains.kotlin.ir.interpreter.IrCompileTimeChecker.visitCall(IrCompileTimeChecker.kt:95)
	at org.jetbrains.kotlin.ir.interpreter.IrCompileTimeChecker.visitCall(IrCompileTimeChecker.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl.accept(IrCallImpl.kt:47)
	at org.jetbrains.kotlin.fir.backend.evaluate.IrConstTransformer.visitCall(IrConstTransformer.kt:37)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:199)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl.accept(IrCallImpl.kt:47)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:33)
	at org.jetbrains.kotlin.ir.expressions.IrBranch.transformChildren(IrWhen.kt:55)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBranch(IrElementTransformerVoid.kt:251)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBranch(IrElementTransformerVoid.kt:255)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBranch(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrBranchImpl.transform(IrWhenImpl.kt:56)
	at org.jetbrains.kotlin.ir.expressions.IrWhen.transformChildren(IrWhen.kt:37)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpression(IrElementTransformerVoid.kt:131)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitWhen(IrElementTransformerVoid.kt:247)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitWhen(IrElementTransformerVoid.kt:248)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitWhen(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrWhen.accept(IrWhen.kt:29)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:33)
	at org.jetbrains.kotlin.ir.expressions.impl.IrTypeOperatorCallImpl.transformChildren(IrTypeOperatorCallImpl.kt:47)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpression(IrElementTransformerVoid.kt:131)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitTypeOperator(IrElementTransformerVoid.kt:244)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitTypeOperator(IrElementTransformerVoid.kt:245)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitTypeOperator(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrTypeOperatorCallImpl.accept(IrTypeOperatorCallImpl.kt:40)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:33)
	at org.jetbrains.kotlin.ir.declarations.impl.IrVariableImpl.transformChildren(IrVariableImpl.kt:81)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitDeclaration(IrElementTransformerVoid.kt:57)
	at org.jetbrains.kotlin.fir.backend.evaluate.IrConstTransformer.visitDeclaration(IrConstTransformer.kt:59)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitVariable(IrElementTransformerVoid.kt:101)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitVariable(IrElementTransformerVoid.kt:102)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitVariable(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.declarations.impl.IrVariableImpl.accept(IrVariableImpl.kt:74)
	at org.jetbrains.kotlin.ir.IrElement$DefaultImpls.transform(IrElement.kt:32)
	at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:19)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.transformChildren(IrBody.kt:62)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBody(IrElementTransformerVoid.kt:108)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlockBody(IrElementTransformerVoid.kt:117)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlockBody(IrElementTransformerVoid.kt:118)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlockBody(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBody.kt:54)
	at org.jetbrains.kotlin.ir.expressions.IrBody.transform(IrBody.kt:27)
	at org.jetbrains.kotlin.ir.declarations.IrFunction.transformChildren(IrFunction.kt:68)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitDeclaration(IrElementTransformerVoid.kt:57)
	at org.jetbrains.kotlin.fir.backend.evaluate.IrConstTransformer.visitDeclaration(IrConstTransformer.kt:59)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFunction(IrElementTransformerVoid.kt:69)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:72)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:73)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSimpleFunction(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:29)
	at org.jetbrains.kotlin.ir.IrElement$DefaultImpls.transform(IrElement.kt:32)
	at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:19)
	at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
	at org.jetbrains.kotlin.ir.declarations.IrClass.transformChildren(IrClass.kt:66)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitDeclaration(IrElementTransformerVoid.kt:57)
	at org.jetbrains.kotlin.fir.backend.evaluate.IrConstTransformer.visitDeclaration(IrConstTransformer.kt:59)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitClass(IrElementTransformerVoid.kt:66)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitClass(IrElementTransformerVoid.kt:67)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitClass(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:55)
	at org.jetbrains.kotlin.ir.IrElement$DefaultImpls.transform(IrElement.kt:32)
	at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:19)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.transformChildren(IrFileImpl.kt:71)
	at org.jetbrains.kotlin.fir.backend.evaluate.IrConstTransformerKt.evaluateConstants(IrConstTransformer.kt:25)
	at org.jetbrains.kotlin.fir.backend.Fir2IrConverter$Companion.createModuleFragment(Fir2IrConverter.kt:316)
	at org.jetbrains.kotlin.fir.analysis.FirAnalyzerFacade.convertToIr(FirAnalyzerFacade.kt:91) 
...
```

**Comment by mglukhikh** [comment]
The error ^ is probably provoked with the following piece of library code

```
public interface MavenDomBuild extends MavenDomBuildBase {

  /**
   * Returns the value of the sourceDirectory child.
   * <pre>
   * <h3>Element http://maven.apache.org/POM/4.0.0:sourceDirectory documentation</h3>
   * 3.0.0+
   * </pre>
   *
   * @return the value of the sourceDirectory child.
   */
  @NotNull
  @Required(value = false, nonEmpty = true)
  @Convert(value = MavenSourceDirectoryConverter.class, soft = false)
  GenericDomValue<PathReference> getSourceDirectory();
...
}
```

**Comment by pyos** [comment]
Yeah, I was afraid fir2ir would break on these, but was unable to construct a case where the FirJavaTypeRef would actually reach IR conversion.

Anyway, the new version of the PR simply delays converting the defaults, so this should work.

**Comment by mglukhikh** [comment]
Merged manually 👍

**Pull request closed without merging**
