### PR TITLE
KT-37748 "Convert anonymous function to lambda expression" intention does not add necessary lambda type parameter

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-37748

### CODE REVIEW

**Comment by igoriakovlev** [comment]
This branch has a conflicts. Please solve it and I review PR as soon as possible. Thank you.

**Comment by t-kameyama** [comment]
@igoriakovlev 
I've rebased this branch onto latest master (5efbe6ae15e), please review.

**Comment by igoriakovlev** [comment]
@t-kameyama 
I suppose that this commit broken the test
**JavaToKotlinConverterSingleFileTestGenerated$ToKotlinClasses.testLibraryFunctions**
Please check it and fix (or tell me if I am wrong)

**Comment by t-kameyama** [comment]
@igoriakovlev Fixed the test.

**Comment by igoriakovlev** [comment]
Thank you for your work.
I merged this PR but there is related bug in this area exists.
May be you will be interested to fix it also.
https://youtrack.jetbrains.com/issue/KT-39393

**Pull request merged**
