### PR TITLE
Implement inspection for redundant lambda arrow

### PR DESCRIPTION
**Pull request by cypressious**
Fixes #KT-11991

### CODE REVIEW

**Comment by yole** [comment]
Basically same comments as for https://github.com/JetBrains/kotlin/pull/1206

**Comment by cypressious** [comment]
@yole, I'll be on vacation for a week. I can fix it next week, or you can
apply the changes yourself, whatever is more convenient for you.

Kirill Rakhman

Am 24.07.2017 2:44 nachm. schrieb "Dmitry Jemerov" <notifications@github.com

**Comment by yole** [comment]
OK, I'll fix those myself.

**Comment by cypressious** [comment]
@yole fixed after review and rebased

**Comment by yole** [comment]
Merged manually. Thanks a lot for your contribution!

**Pull request closed without merging**
