### PR TITLE
[Gradle] Use platform classloader as parent in K2Native isolated class loader

### PR DESCRIPTION
**Pull request by danysantiago**
Fixes [KT-65761](https://youtrack.jetbrains.com/issue/KT-65761)

### CODE REVIEW

**Comment by danysantiago** [comment]
Moving to draft... I was further testing and it seems `ClassLoader.getPlatformClassLoader()` is not available.? Is the JDK used to compile the plugin at least 9 or greater? I wouldn't like to use `ClassLoader. getSystemClassLoader()` even though that would also solve the issue...

**Comment by dkrasnoff** [comment]
> I guess the question is, is that OK? It sort of defeats the purpose of an 'isolated' class loader, not entirely but to some degree.
I'll run this branch against our integration tests to check that it is OK.

But to merge this PR you need to add [an integration test](https://github.com/JetBrains/kotlin/tree/b000b3a90b0a0d62e1d4929024f5eae6e54fbf63/libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/kotlin/org/jetbrains/kotlin/gradle) for you fix. [Here is readme](https://github.com/JetBrains/kotlin/blob/b000b3a90b0a0d62e1d4929024f5eae6e54fbf63/libraries/tools/kotlin-gradle-plugin-integration-tests/Readme.md) how to do that.

**Comment by danysantiago** [comment]
Added an integration test, thanks for the hints @dkrasnoff.

**Comment by ALikhachev** [comment]
@danysantiago Thanks for the contribution. It was merged with a change to use either the platform class loader or the bootstrap class loader depending on running JDK version.
https://github.com/JetBrains/kotlin/compare/5b58ca7f6c43bfc3108e298e46d3372a3bb4dc67..2513befb5bfaf635d51705bb3e90abbee45868d8

**Comment by danysantiago** [comment]
Great! Thanks for taking care of this @ALikhachev! 🙏🏼

**Pull request closed without merging**
