### PR TITLE
[JVM Stdlib] Consistently box with `valueOf`.

### PR DESCRIPTION
**Pull request by madsager**
valueOf performs caching for some values and is recommended
instead of directly allocating new instances.

### CODE REVIEW

**Comment by madsager** [comment]
@ilmirus was there a specific reason to not use `valueOf` for boxing when generating coroutines code?

**Comment by madsager** [comment]
And @pyos points out that there is already an issue for this here: https://youtrack.jetbrains.com/issue/KT-43008. @udalov

**Comment by udalov** [comment]
The explanation is at the top of the file: https://github.com/JetBrains/kotlin/pull/4324/files#diff-3b495e0ff12d7946160dc5170f30097bfeea54f4d09e1a95c6e642651d874e3bL15. Apparently HotSpot doesn't fully eliminate allocations produced by `valueOf` as opposed to direct constructor invocations, which leads to substantial performance cost for coroutines code that deals with primitives. @elizarov might know more details.

So unfortunately we can't fix it like this right now without introducing performance regression in coroutines.

**Comment by elizarov** [comment]
We don't know full details on what parts of HotSpots are directly responsible, but it seems that HotSpot is specifically hacked to support allocation elimination in case of a single branch in the dataflow, as it is the case with the `valueOf` implementation itself, which either takes a value from the cache or returns a newly allocation value. These `valueOf` paths get reliably eliminated by HotSpot by duplicating and compiling those two code paths separately. However, the coroutines add another branching in the data flow, by returning either a boxed primitive or a `COROUTINE_SUSPENDED` marker which is beyond HotSpot's ability to optimize if we use `valueOf` in the corresponding code path. So, we cannot accept this change.

**Pull request closed without merging**
