### PR TITLE
[FIR] Introduce AnnotationUsedAsAnnotationArgumentChecker

### PR DESCRIPTION
**Pull request by Julia-Chekulaeva**

### CODE REVIEW

**Comment by mglukhikh** [comment]
It's very suspicious that no tests from group `FirOldFrontendDiagnosticsTestGenerated` were affected. Please run the whole group `compiler:fir:analysis-tests`. If some test from the group fails, change test data (if changes looks correct) or fix your checker otherwise. Also, find & check usages of `ANNOTATION_USED_AS_ANNOTATION_ARGUMENT` inside folder `compiler/testData/diagnostics/tests`, normally your checker should find diagnostics at the same places. 

Also, please don't forget to refresh IDE diagnostic components by running Generators > Generate FIR checker components and FIR/IDE Diagnostics.

**Comment by mglukhikh** [comment]
In fact it's only one old test with such diagnostics, `annotatedExpressionInsideAnnotation.kt`. Please check behavior of your checker in the situation from this test.

**Comment by Julia-Chekulaeva** [comment]
All tests from `compiler:fir:analysis-tests` passed, but when I modified my test file and added some case:
`@Ann4(
    @Ann1()<!SYNTAX{PSI}!><!>, // The old frontend reports it here
    ""
) fun a() {}`
which is similar to case from `annotatedExpressionInsideAnnotation.kt` file, my checher ignored this case. As I understood, this happens because syntax error occurs, and thus, the annotation list in this case is empty.

**Comment by mglukhikh** [comment]
Ok, I'll investigate myself what's going on here.

**Comment by mglukhikh** [comment]
Merged manually. This commit https://github.com/JetBrains/kotlin/commit/e0c8a6658b0e41844c36aef7982fb55e46a80cea fixes problem with `annotatedExpressionInsideAnnotation.kt` above.

**Pull request closed without merging**
