### PR TITLE
JVM_IR: avoid copying when optimizing ?:/?.

### PR DESCRIPTION
**Pull request by pyos**
Copying is slow, especially when the subtrees are large (with lambdas, etc.). It is also not always correct (e.g. discards reflection metadata), but all cases in which it isn't are probably rejected by the size check afterwards.

### CODE REVIEW

**Comment by dnpetrov** [comment]
There were some related changes made by @gogabr . Could you please rebase on master?

**Comment by pyos** [comment]
Done. Seems like he fixed one of the problems as well.

**Comment by dnpetrov** [comment]
Ok, looks good to me. I'll run tests and push manually.

**Comment by dnpetrov** [comment]
Pushed manually ( 887165a23b5d0899e7c0bff3888aaf1d28d632b6 )

**Pull request closed without merging**
