### PR TITLE
KT-23897 Inspections: report extension functions declared in same class

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-23897

### CODE REVIEW

**Comment by goodwinnk** [comment]
I have accepted commit with reformatting already.

**Comment by t-kameyama** [comment]
Fixed

**Comment by goodwinnk** [comment]
I'm afraid, that the original request wasn't correct. It was a wise for inspection to check usages before reporting. Please take a look at this example:

```
class Test(val str: String) {
    private fun Test.print() {
        println(str)
        println(this.str)
        println(this@Test.str)
        println(this@print.str)
    }

    fun test(test: Test) {
        test.print()
    }
}

fun main(args: Array<String>) {
    Test("one").test(Test("two"))
}
```

It was unfortunate that there were no tests for this situation, and I think only they should be commited as result.

**Comment by goodwinnk** [comment]
The original request might be still valid, but change signature should not be used as a fix, as for this case it's an error to remove the receiver at call place. 

The inspection should still be inapplicable if there's an access to surrounding this via label `this@ClassName`.

**Comment by t-kameyama** [comment]
Fixed. Please take a look.

**Comment by goodwinnk** [comment]
Wow, it was very fast fixes! 🚀 

I have squashed your commits and pushed them to master as e7a9614fb5eab5f1ed45ee8760566a0c53f8a954. 
As a follow-up commit, I have removed runtime usage for tests in fdc6372776b187ec4a08cb73f2b0b2d1630b2765, generally it better to avoid it, if it's not relevant for a test.

Thank you for the contribution!

**Pull request closed without merging**
