### PR TITLE
KT-35051 False positive "Remove redundant backticks" if variable inside the string and isn't followed by space

### PR DESCRIPTION
**Pull request by t-kameyama**
https://youtrack.jetbrains.com/issue/KT-35051

### CODE REVIEW

**Comment by yanex** [comment]
False negative introduced:

```
fun main() {
    val name = "Kotlin"
    val test = "${`name`}test"
}
```

**Comment by t-kameyama** [comment]
PTAL

**Comment by yanex** [comment]
Review: OK.

**Comment by yanex** [comment]
Merged to master manually (https://github.com/JetBrains/kotlin/commit/74ee68e57b3a146c77dcd4bdc370c30c26642938). Thank you!

**Pull request closed without merging**
