### PR TITLE
JVM: redo handling of regenerated constructor capture parameters

### PR DESCRIPTION
**Pull request by pyos**
^KT-51950 Fixed

### CODE REVIEW

**Comment by pyos** [comment]
@max-kammerer ping?

**Comment by max-kammerer** [comment]
@pyos Sorry for delay. PR is LGTM
There are 2 problems with test:
```
org.jetbrains.kotlin.js.test.JsCodegenInlineTestGenerated: org.jetbrains.kotlin.js.test.JsCodegenInlineTestGenerated$AnonymousObject
testKt51950
4/4 runs
[Kotlin](https://buildserver.labs.intellij.net/project/Kotlin) / Kotlin Dev / Tests (Windows) /
Compiler Tests (JS)
 / 
[#1.7.20-dev-992](https://buildserver.labs.intellij.net/buildConfiguration/Kotlin_KotlinDev_JSCompilerTests_WINDOWS/183868718)
[rra/mb/pr4806](https://buildserver.labs.intellij.net/buildConfiguration/Kotlin_KotlinDev_JSCompilerTests_WINDOWS?branch=rra%2Fmb%2Fpr4806&buildTypeTab=overview&mode=builds)
[PY_](https://buildserver.labs.intellij.net/buildConfiguration/Kotlin_KotlinDev_JSCompilerTests_WINDOWS/183868718?buildTab=changes&username=pyos)
pyos: 7
10 May 11:47
Stacktrace
======= Failed test run #1 ==========
  java.lang.IllegalStateException: IMPLEMENTING_FUNCTION_INTERFACE: Implementing function interface is prohibited in JavaScript (5,5) in /1.kt
    at org.jetbrains.kotlin.diagnostics.DiagnosticSink$2.report(DiagnosticSink.java:46)
    at org.jetbrains.kotlin.resolve.AnalyzingUtils.throwExceptionOnErrors(AnalyzingUtils.kt:63)
```

and 

```
[Kotlin/Native](https://buildserver.labs.intellij.net/project/Kotlin_KotlinDev_KotlinNative) / Tests /
Compiler Tests (for dist) opt.debug/cache.dist (Native, Linux x86_64)
 / 
#1.7.20-dev-992
org.jetbrains.kotlin.konan.blackboxtest.NativeCodegenBoxTestGenerated: org.jetbrains.kotlin.konan.blackboxtest.NativeCodegenBoxTestGenerated$BoxInline: org.jetbrains.kotlin.konan.blackboxtest.NativeCodegenBoxTestGenerated$BoxInline$AnonymousObject
testAllFilesPresentInAnonymousObject
4/4 runs
Kotlin / Kotlin Dev / Kotlin/Native / [Tests](https://buildserver.labs.intellij.net/project/Kotlin_KotlinDev_KotlinNativeTests) /
Compiler Tests (for dist) opt.debug/cache.dist (Native, Linux x86_64)
 / 
[#1.7.20-dev-992](https://buildserver.labs.intellij.net/buildConfiguration/Kotlin_KotlinDev_NativeCompilerTest_linux_x64_dist_mode_2_optimizationMode_d_cacheMode_d_memoryModel_d_gcType_u_gcScheduler_u_useThreadStateChecker_d/183868702)
rra/mb/pr4806
PY_
pyos: 7
10 May 12:06
Stacktrace
======= Failed test run #1 ==========
  java.lang.AssertionError: Test data file missing from the generated test class: compiler/testData/codegen/boxInline/anonymousObject/kt51950.kt
  Please regenerate tests (Generate[Tests](https://buildserver.labs.intellij.net/project/Kotlin_KotlinDev_KotlinNativeTests).kt)
  java.lang.AssertionError: Test data file missing from the generated test class: compiler/testData/codegen/boxInline/anonymousObject/kt51950.kt
  Please regenerate tests (GenerateTests.kt)
```

**Comment by max-kammerer** [comment]
There is also a problem with bootstrap:

```
e: org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during IR lowering
File being compiled: /mnt/agent/work/17e640964edd2053/kotlin/kotlin-native/backend.native/compiler/ir/backend.native/src/org/jetbrains/kotlin/backend/konan/ir/interop/cstruct/CStructVarCompanionGenerator.kt
The root cause java.lang.RuntimeException was thrown at: org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:50)
  at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:239)
  at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException$default(CodegenUtil.kt:235)
....
Caused by: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Couldn't inline method call: CALL 'public final fun irBlockBody$default (startOffset: kotlin.Int, endOffset: kotlin.Int, body: @[ExtensionFunctionType] kotlin.Function1<org.jetbrains.kotlin.ir.builders.IrBlockBodyBuilder, kotlin.Unit>, $mask0: kotlin.Int, $handler: kotlin.Any?): org.jetbrains.kotlin.ir.expressions.IrBlockBody [inline] declared in org.jetbrains.kotlin.ir.builders.ExpressionHelpersKt' type=org.jetbrains.kotlin.ir.expressions.IrBlockBody origin=DEFAULT_DISPATCH_CALL
Method: irBlockBody$default (Lorg/jetbrains/kotlin/ir/builders/IrBuilderWithScope;IILkotlin/jvm/functions/Function1;ILjava/lang/Object;)Lorg/jetbrains/kotlin/ir/expressions/IrBlockBody;:
   L0
    LINENUMBER 384 L0
   L1
    LINENUMBER 385 L1
    ALOAD 0
    INVOKEVIRTUAL org/jetbrains/kotlin/ir/builders/IrBuilderWithScope.getStartOffset ()I
    ISTORE 1
   L2
    LINENUMBER 384 L2
   L3
    LINENUMBER 386 L3
    ALOAD 0
    INVOKEVIRTUAL org/jetbrains/kotlin/ir/builders/IrBuilderWithScope.getEndOffset ()I
    ISTORE 2
   L4
    LINENUMBER 384 L4
    ALOAD 0
    LDC "<this>"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkNotNullParameter (Ljava/lang/Object;Ljava/lang/String;)V
    ALOAD 3
    LDC "body"
    INVOKESTATIC kotlin/jvm/internal/Intrinsics.checkNotNullParameter (Ljava/lang/Object;Ljava/lang/String;)V
    ICONST_0
    ISTORE 4
   L5
    LINENUMBER 389 L5
    NEW org/jetbrains/kotlin/ir/builders/IrBlockBodyBuilder
    DUP
   L6
    LINENUMBER 390 L6
    ALOAD 0
    INVOKEVIRTUAL org/jetbrains/kotlin/ir/builders/IrBuilderWithScope.getContext ()Lorg/jetbrains/kotlin/ir/builders/IrGeneratorContext;
    ALOAD 0
    INVOKEVIRTUAL org/jetbrains/kotlin/ir/builders/IrBuilderWithScope.getScope ()Lorg/jetbrains/kotlin/ir/builders/Scope;
   L7
    LINENUMBER 391 L7
    ILOAD 1
   L8
    LINENUMBER 392 L8
    ILOAD 2
   L9
    LINENUMBER 389 L9
    INVOKESPECIAL org/jetbrains/kotlin/ir/builders/IrBlockBodyBuilder.<init> (Lorg/jetbrains/kotlin/ir/builders/IrGeneratorContext;Lorg/jetbrains/kotlin/ir/builders/Scope;II)V
    ASTORE 5
   L10
    LINENUMBER 393 L10
    NOP
   L11
    ICONST_0
    ISTORE 6
   L12
    LINENUMBER 455 L12
    ALOAD 3
    ALOAD 5
    INVOKEINTERFACE kotlin/jvm/functions/Function1.invoke (Ljava/lang/Object;)Ljava/lang/Object; (itf)
    POP
   L13
    LINENUMBER 456 L13
    ALOAD 5
    INVOKEVIRTUAL org/jetbrains/kotlin/ir/builders/IrBlockBodyBuilder.doBuild ()Lorg/jetbrains/kotlin/ir/expressions/IrBlockBody;
   L14
    LINENUMBER 393 L14
    ARETURN
   L15
    LOCALVARIABLE $i$f$blockBody I L12 L14 6
    LOCALVARIABLE this_$iv Lorg/jetbrains/kotlin/ir/builders/IrBlockBodyBuilder; L11 L14 5
    LOCALVARIABLE $i$f$irBlockBody I L5 L15 4
    LOCALVARIABLE $this$irBlockBody_u24default Lorg/jetbrains/kotlin/ir/builders/IrBuilderWithScope; L0 L15 0
    LOCALVARIABLE startOffset I L2 L15 1
    LOCALVARIABLE endOffset I L4 L15 2
    LOCALVARIABLE body Lkotlin/jvm/functions/Function1; L0 L15 3
    MAXSTACK = 6
    MAXLOCALS = 7
File is unknown
```

**Comment by pyos** [comment]
Also fixed, I think.

**Comment by max-kammerer** [comment]
@pyos Thank you! Merged manually

**Pull request closed without merging**
