### PR TITLE
[IR] Align captured receiver variable naming with old BE

### PR DESCRIPTION
**Pull request by kandersen**

### CODE REVIEW

**Comment by kandersen** [comment]
Also fixed a `TODO` by @dnpetrov

**Comment by max-kammerer** [comment]
@romanart @homuroll Please take a look into LDL and psi2ir parts? Is it ok for JS/Native?

**Comment by romanart** [comment]
From Psi2ir/JS perspective - LGTM

**Comment by kandersen** [comment]
I managed to run the Kotlin/Native test suite locally, too. It does not seem affected by this change.

**Comment by kandersen** [comment]
@homuroll Friendly ping :)

**Comment by homuroll** [comment]
Looks good from the Native backend standpoint, but @kishmakov is investigating from the IDE standpoint.

**Comment by kishmakov** [comment]
Looks good from the IDE standpoint as well.

**Comment by max-kammerer** [comment]
Sorry for all I've forgot to merge pr(

**Comment by max-kammerer** [comment]
... and thank you for your work!

**Comment by kandersen** [comment]
Not to worry! And thank you! Part of the challenge here is definitely simply knowing the stakeholders on a PR like this :)

**Pull request merged**
