### PR TITLE
jvm-abi-gen: keep InnerClass attributes for all referenced types

### PR DESCRIPTION
**Pull request by pyos**
^KT-55233 Fixed

### CODE REVIEW

**Comment by sfs** [comment]
If I understand the problem in KT-55233 correctly then we're essentially stripping all `InnerClass` attributes for classes outside of the current module. That's... pretty bad. Nice catch!

The problem seems to be that the logic in `JvmAbiOutputExtension` is wrong. We currently check wether an `InnerClass` was kept, instead of checking that the class was not stripped. Would it be sufficient to record the stripped classes in `JvmAbiClassBuilerInterceptor` [here](https://github.com/JetBrains/kotlin/blob/c02d5e8dccebcb986751a4d239834313c440dd98/plugins/jvm-abi-gen/src/org/jetbrains/kotlin/jvm/abi/JvmAbiClassBuilderInterceptor.kt#L185) and change the check in `visitInnerClass`  under `JvmAbiOutputExtension` accordingly? Then we might be able to avoid having to sort the inner class attributes again?

---

On the other hand, I like the idea of using a `ClassRemapper` to record all inner class names that are used in a stripped class. Maybe we could still keep that logic, but change it to remove inner class attributes for declarations which are not referenced anymore in the ABI jar? For example:

```kotlin
class A {
  fun f(): Class<*> = Outer::class.java
}
```

shouldn't need any `InnerClass` attributes in the ABI jar.

**Comment by pyos** [comment]
>Maybe we could still keep that logic, but change it to remove inner class attributes for declarations which are not referenced anymore in the ABI jar?

That's exactly what it does...the remapper is applied between the writer and the filter, so bodies of stripped methods shouldn't be visited by it.

**Comment by sfs** [comment]
> That's exactly what it does...the remapper is applied between the writer and the filter, so bodies of stripped methods shouldn't be visited by it.

But doesn't it keep the classes in the current module unconditionally since `innerClassesToKeep` is initialized with `abiClassInfos.keys.toMutableSet()`?

**Comment by pyos** [comment]
That's because outer and inner classes of the current class should be kept even if they are otherwise unreferenced. It might be possible to have a more precise check here, I'm not sure.

**Comment by pyos** [comment]
Done. Now an InnerClasses entry is kept if the referenced class is:
1. the current class;
2. a public descendant of the current class;
3. mentioned in the ABI of the current class;
4. an ancestor of a class with an InnerClasses entry.

**Comment by sfs** [comment]
Awesome, thank you!

**Comment by udalov** [comment]
LGTM, thank you!

**Pull request merged**
