### PR TITLE
Generate conditional jumps with optimizations for loops, if possible.

### PR DESCRIPTION
**Pull request by punzki**
Also increased the coverage of bytecode text tests around conditions.

### CODE REVIEW

**Comment by max-kammerer** [comment]
@punzki Please rebase on master: there is conflict after #2153

**Comment by punzki** [comment]
> @punzki Please rebase on master: there is conflict after #2153

@max-kammerer Done!

**Comment by max-kammerer** [comment]
@punzki Please split all new/affected tests in more granular files, e.g. if/while/doWhile:
so negatedNonZeroCompare.kt ->
negatedNonZeroCompareInIf.kt
negatedNonZeroCompareInWhile.kt
negatedNonZeroCompareInDoWhile.kt

**Comment by punzki** [comment]
> @punzki Please split all new/affected tests in more granular files, e.g. if/while/doWhile:
> so negatedNonZeroCompare.kt ->
> negatedNonZeroCompareInIf.kt
> negatedNonZeroCompareInWhile.kt
> negatedNonZeroCompareInDoWhile.kt

@max-kammerer Done!

**Comment by max-kammerer** [comment]
@punzki Many Thanks!

**Pull request merged**
