### PR TITLE
JVM: correctly merge typed null values

### PR DESCRIPTION
**Pull request by pyos**
1. merge(null of type A, null of type B) = null of unknown type;
2. merge(null of type A, something of type B) = merge(unknown null, B).

^KT-52311 Fixed

### CODE REVIEW

**Comment by pyos** [comment]
@ilmirus I don't actually think TypedNullValue was the correct way to fix KT-51718. The problem there is that the variable containing an array is known to be NULL_VALUE, and OptimizationBasicInterpreter is hardcoded to produce a REFERENCE_VALUE when doing an AALOAD from something that's not an array:
```
var start: Start? = null // NULL_VALUE
var configuration: String? = null // NULL_VALUE
val starts: Array<Start>? = null // NULL_VALUE
if (starts != null && starts.isNotEmpty()) {
    start = starts[0] // REFERENCE_VALUE
    configuration = call2() // Ljava/lang/String;
}
// start = merge(NULL_VALUE, REFERENCE_VALUE) = REFERENCE_VALUE
// configuration = merge(NULL_VALUE, String) = String
```
In reality the array access cannot be executed, so we really should know that `start` after the merge is still a `NULL_VALUE`, and its type is really irrelevant. `TypedNullValue` only helps in that it forces AALOAD to produce something meaningful (from a null array of type `[LString;`).

I don't see any other instructions that behave so weirdly in OptimizationBasicInterpreter. I think the more correct approach is to not execute AALOAD on non-array types, and only consider any exceptional paths as successors.

**Comment by pyos** [comment]
This does not fail any tests, but I'm not convinced it won't break anything: https://github.com/pyos/kotlin/compare/kt-52311...kt-52311-2

Also that commit only makes an invalid AALOAD return null (which is disregarded when merged into any other reference), but does not prevent the analyzer from proceeding down the non-exceptional path, so `configuration` is still merged into String when it's really always null. I'm not sure how to do that given the API constraints (the analyzer cannot check the types).

**Review by ilmirus — APPROVED** [review]

**Comment by ilmirus** [comment]
Thanks! I've checked both the changes in our libraries and can confirm, that TypedNullValue is not the way to go. I will push the changes to master manually.

**Comment by udalov** [comment]
https://youtrack.jetbrains.com/issue/KT-54581/JVM-VerifyError-Bad-type-on-operand-stack-with-generic-inline-function-and-when-inside-try-catch-block

**Pull request closed without merging**
