### PR TITLE
Add inspection for empty ranges with start > endInclusive

### PR DESCRIPTION
**Pull request by cypressious**
Fixes #KT-18438

### CODE REVIEW

**Comment by cypressious** [comment]
I have no idea, why the added test is failing.

**Comment by mglukhikh** [comment]
This `<file>temp:///src/test.kt</file>` should be replaced with just `<file>test.kt</file>`

**Comment by cypressious** [comment]
@mglukhikh thanks, fixed the tests and rebased onto master.

**Comment by mglukhikh** [comment]
Thanks you, merged.

**Pull request closed without merging**
