### PR TITLE
KT-8708 Function to strip leading whitespaces

### PR DESCRIPTION
**Pull request by cy6erGn0m**
Function to strip leading whitespace characters before the specified delimiter character (pipe by default). Intended to be partial solution of [KT-6620 Indent safe """ syntax](https://youtrack.jetbrains.com/issue/KT-6620)

`trimMargin` is very similar to `stripMargin` in Scala and Groovy so we can think it is a common solution.

`trimMargin` is works slightly different than `stripMarign` in Scala and Groovy. The main difference is that by default `trimMargin` removes only whitespaces on the contrary `stripMargin` removes all control characters that I believe is wrong. 

However if user really need exact the same behaviour he always can specify custom `whitespacePredicate` like this:

```kotlin
trimMargin { it <= ' ' }
```

### CODE REVIEW

**Comment by abreslav** [comment]
I have some reservations about the need to put the annoying `|` on every line. Can we not do it more conveniently? What do other languages do?

**Comment by cy6erGn0m** [comment]
@abreslav I see no solution to detect indent automatically that will work predictable in any case. In both Scala and Groovy there is `stripMargin` that requires | on every line. Also in Groovy there is `stripIndent` but it requires higher user attention: all lines should have indentation (including first line). We can include it too but not sure we have to

**Comment by abreslav** [comment]
@cy6erGn0m Maybe I'm being naïve, but it seems to me that it would be enough to check if the first line is empty and ignore it in this case, otherwise it's pretty straightforward to strip the indent of the first (nonempty) line from all other lines.

**Comment by cy6erGn0m** [comment]
@abreslav what if we have

```
"""
    a
  b
""
```

Shouldn't we find minimal common indentation level (except blank lines)?

**Comment by abreslav** [comment]
@cy6erGn0m could you write down a summary of what we decided here, for others to be able to comment

**Comment by cy6erGn0m** [comment]
After all we decided to implement both trimMargin and trimIndent: the first one uses a specific prefix (|) and the second one detects common minimal indent and removes it from every line

**Comment by cy6erGn0m** [comment]
@ilya-g see changes

**Comment by andrewoma** [comment]
FYI, this is what I'm currently using - it's a variant of your trimIndent: https://github.com/andrewoma/kommon/blob/master/src/main/kotlin/com/github/andrewoma/kommon/lang/StringExtensions.kt#L27

I found it necessary to drop leading and trailing blank lines in my usage patterns (in particular splitting groups of SQL statements separated by semicolons.

**Comment by cy6erGn0m** [comment]
@andrewoma thank you for info. `trimIndent` drops first and last lines if they are empty

**Comment by cy6erGn0m** [comment]
`trimIndent` does drop but `trimMargin` doesn't so I have introduced the same behaviour for it too. See last commit that does it

**Comment by cy6erGn0m** [comment]
Merged manually

**Pull request closed without merging**
